### ISSUE TITLE
add download and install apk in android

### ISSUE THREAD

**Issue by ginoz** [larryaasen/upgrader#1]
add download and install apk in android

**Comment by gedw99** [comment]
I presume this is designed for when you don't want to use the Google play store ?

**Comment by ginoz** [comment]
> I presume this is designed for when you don't want to use the Google play store ?

yes, will support this feature?

**Comment by larryaasen** [comment]
@ginoz Thanks for opening this issue on upgrader. The 0.4.2 version of this package supports appcast which can be used for Android to specify a newer version of the app. I just updated the package to 0.4.3 with improved README documentation and example code for supporting appcast. I hope this satisfy's your Android requirements. Please let me know if this works for you.
https://pub.dartlang.org/packages/upgrader

@gedw99 This package is designed for use with apps on the Google Play Store, or any public or private store. The use of appcast makes the process of describing an app update easy. An appcast will work with both Android and iOS, but is probably not needed for iOS, unless you are using a private app store like App47.

**Comment by larryaasen** [comment]
I updated the examples with an Appcast for Android. It is now in version 0.5.1+1 of the package here: 822d52f. The format of the Appcast file is listed in the README.

**Comment by larryaasen** [comment]
@ginoz Can I close this issue?
