### ISSUE TITLE
Country Code Case Sensitive

### ISSUE THREAD

**Issue by fabricio-godoi** [larryaasen/upgrader#100]
I have an application that is only available in Brazil. Since the App Store is configured to Brazil only, I had to configure the countryCode in the library to "BR".

Since I didn't see it at first, I put "br" (in lowercase) in the configuration, but the ITunes library kept returning the wrong app version, thus not showing the update popup. Debugging the ITunes lib, I found out that it was returning sometimes the last (eg. 1.1.6) and most of the times the second last (eg. 1.1.4) app version that was deployed. The results always point out the propper application data (bundle id and app store URL), but the current version was not reliable.

Once I changed the countryCode to uppercase, it seems that the library always returns the final version (1.1.6). This was reproduced in two different computers with the same source code running in the IOs simulator.

I have no idea for what reason this was happening, but I suggest a simple toUppercase() in the code to prevent further misuse, or to update the README to specify this issue for now.

Best regards.

**Comment by larryaasen** [comment]
Thanks for pointing out this issue. I just added a fix to uppercase the country code, and published version 3.2.0 of the package with this fix. Please check it out.
https://pub.dev/packages/upgrader
