### ISSUE TITLE
Force update 

### ISSUE THREAD

**Issue by abdulrojak288** [larryaasen/upgrader#103]
I would like to disable possibility to hide/close popup if the app is not updated. Can it ?

**Comment by larryaasen** [comment]
The popup dialog will not be displayed unless there is an update available. After the user closes the dialog, it will not be display again for another 3 days. Make sure you do not call clearSavedSettings(), which is normally used for local testing. 
```
    // Only call clearSavedSettings() during testing to reset internal values.
    Upgrader().clearSavedSettings(); // Remove this for release builds
```

**Comment by abdulrojak288** [comment]
Can the pop up dialog be set can't be closed?
We really need a way to force update.
Because sometimes there are critical updates that cannot be delayed.

**Comment by Basher7** [comment]
@abdulrojak288 you can use my fork [https://github.com/Basher7/upgrader.git](https://github.com/Basher7/upgrader.git)

By this fork you can disable Android device back button by setting ```disableBackButton=true```
Also, For critical update set below line in your xml file

> ```<sparkle:tags><sparkle:criticalUpdate/></sparkle:tags>```

this will hide ```IGNORE``` and ```LATER``` button. Also set ```canDismissDialog=false``` and ```disableBackButton=true```. By this user must be update application if he want to use it.

N.B: this functionality works only for UpgraderAlert

**Comment by wer-mathurin** [comment]
@larryaasen 
Since you tag this as a possible enhancement.  Do you have an idea if you plan to support it soon?
We plan to add this functionality in one of our project, and forcing an update is one use case we need to cover.
As a workaround we can use the forked repository, but we'd love to see it happening here :-)

Best regards.

**Comment by larryaasen** [comment]
I don't have a good solution in mind but would like to see some suggestions.

**Comment by ameenbadri7** [comment]
Thank you it's working.

This my XML appcast file:
 
`<?xml version="1.0" encoding="utf-8"?>

<rss version="2.0"
    xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle">
    <channel>
        <title>Debt Now App - Appcast</title>
        <item>
            <title>Version 3.0.0</title>
            <description>Minor updates and improvements.</description>
            <pubDate>Sun, 1/1/2022 12:00:00 +0000</pubDate>
            <enclosure url="https://play.google.com/store/apps/details?id=XXXX.XXXX.XXXX" sparkle:version="3.0.0" sparkle:os="android" />
            <sparkle:tags>
                <sparkle:criticalUpdate/>
            </sparkle:tags>
        </item>
    </channel>
</rss>
`

and this is my code :

`UpgradeAlert(
              debugLogging: true,
              debugAlwaysUpgrade: true,
              // minAppVersion: '3.0.0',

              appcastConfig: cfg,
              shouldPopScope: () => false,
              countryCode: 'UK',
              showIgnore: false,
              showLater: false,
              canDismissDialog: false,
child:.......),),
`

**Comment by Navil** [comment]
Is there any update on this feature request? It seems like a pretty important functionality to me.

**Comment by kyeshmz** [comment]
Same, I think the title is not correct as it should just be that the dialog does not close on push if the version is not the same

**Comment by fotiDim** [comment]
I believe this is not an issue anymore. Testing with upgrader: 10.0.0. If I set

```
<sparkle:tags>
    <sparkle:criticalUpdate/>
</sparkle:tags>
```
then the dialog cannot be dismissed and only shows "UPDATE NOW".

The full XML:
```xml
<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0"
    xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle">
    <channel>
        <title>My app - Appcast</title>
        <item>
            <title>Version 2.0.0</title>
            <description>Critical update</description>
            <pubDate>Sun, 24/3/2024 07:00:00 +0000</pubDate>
            <enclosure url="https://play.google.com/store/apps/details?id=com.company.myapp" sparkle:version="2.0.0" sparkle:os="android" />
            <sparkle:tags>
                <sparkle:criticalUpdate/>
            </sparkle:tags>
        </item>
    </channel>
</rss>
```

I didn't set any special parameters in Upgrader and UpgradeAlert except for storeController:

```dart
static const appcastURL =
      'https://raw.githubusercontent.com/ORG/REPO/main/MYAPP.xml';
  final upgrader = Upgrader(
    storeController: UpgraderStoreController(
      onAndroid: () => UpgraderAppcastStore(appcastURL: appcastURL),
    ),
  );

...

@override
  Widget build(BuildContext context) {
    return UpgradeAlert(
      upgrader: upgrader,
      child: ...

```

**Comment by larryaasen** [comment]
@abdulrojak288 Look at the latest version of this package with a latest customization options. I think it now meets your needs. If not, please open a new issue with your details.
