### ISSUE TITLE
Question about AppCast

### ISSUE THREAD

**Issue by ComputelessComputer** [larryaasen/upgrader#104]
Hi, I was looking into this package and I have a few questions.

For Android, I have noticed an appcast xml file needs to be deployed such as GitHub.

So if I was to use this for Android,

1. Should I create an xml file in the project's directory and git push every time a new update should be notified?
2. Here in the example below, if I created a new update version should I add a new version by concatenating in the channel attribute?
```
<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0" xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle">
    <channel>
        <title>Debt Now App - Appcast</title>
        <item>
            <title>Version 1.15.0</title>
            <description>Minor updates and improvements.</description>
            <pubDate>Sun, 30 Dec 2018 12:00:00 +0000</pubDate>
            <enclosure url="https://play.google.com/store/apps/details?id=com.moonwink.treasury" sparkle:version="1.15.0" sparkle:os="android" />
        </item>
        <!------Add a new version by concatenating in the channel attribute?------>
        <title>Debt Now App - Appcast2</title>
        <item>
            <title>Version 1.15.1</title>
            <description>Minor updates and improvements.2</description>
            <pubDate>Sun, 31 Dec 2018 12:00:00 +0000</pubDate>
            <enclosure url="https://play.google.com/store/apps/details?id=com.moonwink.treasury" sparkle:version="1.15.1" sparkle:os="android" />
        </item>
    </channel>
</rss>
```

**Comment by larryaasen** [comment]
@ComputelessComputer  You can place your XML file anywhere, not just in the project's directory, as long as the app can access it from anywhere without credentials. Any time you have a new version, or want to force upgrade using the critical update, just update the XML file. You can have multiple versions in the file and keep adding new versions over time. However, it is not necessary to have more than one per platform.
