### ISSUE TITLE
Error: No named parameter with the name 'nullOk'.

### ISSUE THREAD

**Issue by him123** [larryaasen/upgrader#107]
I am using `upgrader: ^2.8.2` because my app is running in `sdk: ">=2.10.0 <3.0.0"`

but when I run the app it gives me following error

`../../flutter/.pub-cache/hosted/pub.dartlang.org/upgrader-2.8.2/lib/src/upgrade_messages.dart:76:48: Error: No named parameter with the name 'nullOk'.
      locale = Localizations.localeOf(context, nullOk: true);           
                                               ^^^^^^                   
../../flutter/packages/flutter/lib/src/widgets/localizations.dart:413:17: Context: Found this candidate, but the arguments don't match.
  static Locale localeOf(BuildContext context) {                        
                ^^^^^^^^                                                
../../flutter/.pub-cache/hosted/pub.dartlang.org/upgrader-2.8.2/lib/src/upgrader.dart:392:48: Error: No named parameter with the name 'nullOk'.
      locale = Localizations.localeOf(context, nullOk: true);           
                                               ^^^^^^                   
../../flutter/packages/flutter/lib/src/widgets/localizations.dart:413:17: Context: Found this candidate, but the arguments don't match.
  static Locale localeOf(BuildContext context) {                        
                ^^^^^^^^                                                
                                                                        
                                                                        
FAILURE: Build failed with an exception.`

Please help me how I can get rid of this error and use this dependency.

**Comment by him123** [comment]
I think solution may be https://api.flutter.dev/flutter/widgets/Localizations/maybeLocaleOf.html

**Comment by larryaasen** [comment]
One way I solve dependency issues like this is by temporarily removing all version numbers from the dependencies in the pubspec.yaml file, and running `flutter pub get`. It may resolve the dependency version by itself. Then, grab the version numbers from the pubspec.lock file and put them back in the pubspec.yaml file. Hope that works for you.

**Comment by larryaasen** [comment]
I just released version 2.8.3 to resolve the `nullOk` issue. See if that resolves the issue for you.
https://pub.dev/packages/upgrader/versions/2.8.3
