### ISSUE TITLE
Icon in dialog? 

### ISSUE THREAD

**Issue by thecreativedg** [larryaasen/upgrader#108]
Is it possible to add Icon like this? 

![alert_with_icon_2.png](https://user-images.githubusercontent.com/6277278/119053241-16ac8400-b9c6-11eb-90ea-22e18244d8cb.png)

**Comment by larryaasen** [comment]
The UI in upgrader is not designed to be customized like that.

**Comment by larryaasen** [comment]
@thecreativedg Look at the latest version of this package with a latest customization options. I think it now meets your needs. If not, please open a new issue with your details.
