### ISSUE TITLE
UpgraderAlert not getting app name on iOS

### ISSUE THREAD

**Issue by tjcode19** [larryaasen/upgrader#110]
flutter: upgrader: showDialog message: A new version of 'name-missing' is available! Version 1.0 is now available-you have 0.9.0.

**Comment by larryaasen** [comment]
The upgrader package does not contain the string `name-missing` so that must be in your app somewhere.

**Comment by tjcode19** [comment]
Thank you for your quick response. This is what is displaying on android *A new version of Chanelle MFB is available! Version 2.0.0 is now available-you have 0.9.0.* And we can see, it's showing the app name "Chanelle MFB" but in iOS , that app name is missing and I'm getting this *A new version of (app name is suppose to show here) is available! Version 1.0 is now available-you have 0.9.0.*

**Comment by larryaasen** [comment]
@tjcode19 On iOS you need to setup your Info.plist file to contain the correct Bundle display name. See example below.

<img width="809" alt="Screen Shot 2021-06-09 at 8 00 15 AM" src="https://user-images.githubusercontent.com/325973/121350503-c6578080-c8f8-11eb-8bc6-8f4aba2d6f38.png">

**Comment by tjcode19** [comment]
Thank you very much
