### ISSUE TITLE
iOS setup

### ISSUE THREAD

**Issue by amee13bit** [larryaasen/upgrader#118]
Was trying to setup upgrader for flutter app, everything works on android but not in ios?
do i have to put appstore link appcast fiel? or is there any addition setup needed for ios?
and also how to test in ios?

**Comment by larryaasen** [comment]
First, get the example to run on a simulator to make sure you can build it on iOS properly. There is nothing special to setup for iOS in your app. Once your app is properly configured and running in the iOS app store, it will also be configured properly for upgrader. Just make sure to include `UpgradeAlert` in your widget tree as you see in the examples.

**Comment by amee13bit** [comment]
So there is no need to add url in xml file ?
wrapping in upgrade alert will be enought right?

**Comment by larryaasen** [comment]
Can you attach the upgrade log here?

**Comment by amee13bit** [comment]
upgrader: button tapped: update now
flutter: upgrader: launching: https://apps.apple.com/us/app/top-kerala-psc-learning-app/id1545107052?uo=4
flutter: upgrader: launch to app store failed: PlatformException(Error, Error while launching https://apps.apple.com/us/app/top-kerala-psc-learning-app/id1545107052?uo=4, null, null)
