### ISSUE TITLE
Callback when there is no Update and dialog will not be displayed

### ISSUE THREAD

**Issue by skavinvarnan** [larryaasen/upgrader#119]
Need a callback when there is no Update available or the dialog is not shown for the session. 

The reason why this is needed is, when there is a critical release the app should not load any view. So completely everything will be based on callbacks, we already have callback for onLater, onIgnore, also need a callback with not dialog will be displayed. 

PS: I'm working on this will create a PR soon

**Comment by courtneypresto** [comment]
Did you end yo doing this @skavinvarnan? I agree this would be VERY helpful!

**Comment by larryaasen** [comment]
@skavinvarnan and @courtneypresto - I created a new PR https://github.com/larryaasen/upgrader/pull/156 with a callback that I think will work for you. Please check it out and let me know what you think: https://github.com/larryaasen/upgrader/pull/156

**Comment by larryaasen** [comment]
The PR #156 was merged and is now available in version https://pub.dev/packages/upgrader/versions/3.14.0. Check it out.
