### ISSUE TITLE
Cosmetic request

### ISSUE THREAD

**Issue by jodymac** [larryaasen/upgrader#120]
On the original Iphone SE, the upgrade card alert overflows due to items listed in the changes section of the app listing.  Can we make the the content of this card a Single Child Scroll View.  I imagine this would affect some of the older smaller screen phones as well when there are a lot of changes listed.

**Comment by larryaasen** [comment]
@jodymac Can you provide a screenshot of this problem?

**Comment by jodymac** [comment]
This is without any text modifcations on the original Iphone SE
![origIphoneSE](https://user-images.githubusercontent.com/25085716/129491428-630283fa-c27d-4707-97ae-e8486f60f862.png)

**Comment by jodymac** [comment]
I had larger text turned off, but it was still using the previous test size.  I reset it, but the problem still exists with the font reduced to system default.

**Comment by larryaasen** [comment]
This issue has now been fixed. Try version 3.5.1 that was just released.

**Comment by jodymac** [comment]
Perfect!  Impressive turn around time, thank you so much for your time and plugin!
