### ISSUE TITLE
Upgrader Functionality

### ISSUE THREAD

**Issue by rainbowMeh** [larryaasen/upgrader#121]
Hey
I want to ask about functionality
1. Can the Upgrader only show upgradeAlert to a specific version or version that greater then x.x.x ?
2. Can the Upgrader only show critical upgradeAlert to a specific version or range of version?

I try to use this XML code, but its still showing the upgrade
My application version is set to 1.0.4

```
<item>
  <title>Version 1.1.0</title>
  <sparkle:version>1.1.0</sparkle:version>
  <description>Minor updates and improvements.</description>
  <pubDate>Mon, 28 Jan 2013 14:30:00 +0500</pubDate>
  <sparkle:minimumSystemVersion>1.0.5</sparkle:minimumSystemVersion>
</item>
```

Thankyou!!

**Comment by larryaasen** [comment]
Can you post your upgrader console log here?

**Comment by rainbowMeh** [comment]
Hello @larryaasen 
Thankyou for the reply

Here's the upgrader log with the same XML that I commented before
```
I/flutter ( 6830): upgrader: languageCode: id
I/flutter ( 6830): upgrader: build UpgradeAlert
I/flutter ( 6830): upgrader: default operatingSystem: android ****.******.***.*************
I/flutter ( 6830): upgrader: operatingSystem: android
I/flutter ( 6830): upgrader: platform: TargetPlatform.android
I/flutter ( 6830): upgrader: package info packageName: ****
I/flutter ( 6830): upgrader: package info appName: ****
I/flutter ( 6830): upgrader: package info version: 1.0.4
I/flutter ( 6830): upgrader: appcast is available for this platform
I/flutter ( 6830): upgrader: appcast item count: 3
I/flutter ( 6830): upgrader: appcast best item version: 1.1.0
I/flutter ( 6830): upgrader: blocked: false
I/flutter ( 6830): upgrader: debugDisplayAlways: false
I/flutter ( 6830): upgrader: debugDisplayOnce: false
I/flutter ( 6830): upgrader: hasAlerted: false
I/flutter ( 6830): upgrader: appStoreVersion: 1.1.0
I/flutter ( 6830): upgrader: installedVersion: 1.0.4
I/flutter ( 6830): upgrader: minAppVersion: null
I/flutter ( 6830): upgrader: isUpdateAvailable: true
I/flutter ( 6830): upgrader: shouldDisplayUpgrade: true
I/flutter ( 6830): upgrader: shouldDisplayReleaseNotes: true
I/flutter ( 6830): upgrader: showDialog title: ****
I/flutter ( 6830): upgrader: showDialog message: ****
I/flutter ( 6830): upgrader: showDialog releaseNotes: ****
```

**Comment by larryaasen** [comment]
> I try to use this XML code, but its still showing the upgrade
It is showing the upgrade alert because the Appcast has a higher version 1.1.0 than the app version 1.0.4. Were you expecting something different?

> Can the Upgrader only show upgradeAlert to a specific version or version that greater then x.x.x ?
It will show the alert for the highest qualifying version in the Appcast.

> Can the Upgrader only show critical upgradeAlert to a specific version or range of version?
It is only a critical update when the app version is lower than the min version.

**Comment by rainbowMeh** [comment]
> It is showing the upgrade alert because the Appcast has a higher version 1.1.0 than the app version 1.0.4. Were you expecting something different?

In the XML, I already declare the minimum system version to get the update is 1.0.5. Logically, the app version 1.0.4 will not be having the update. But in this case, the upgrade alert still alerting for the update.
Am I using the `<sparkle:minimumSystemVersion>` tag right?

**Comment by tech-instacare** [comment]
facing same issue.

**Comment by larryaasen** [comment]
> facing same issue.

@tech-instacare Can you post your Flutter upgrader log here?

**Comment by larryaasen** [comment]
@rainbowMeh @tech-instacare Still facing this issue?

**Comment by rainbowMeh** [comment]
Hello
In the end, I forked it and changed some of the code, because I found out that the "minimumSystemVersion" is different than what I thought.  
Thankyou 😁
