### ISSUE TITLE
PlayStoreResults.releaseNotes exception: Bad state: No element

### ISSUE THREAD

**Issue by yassinsameh** [larryaasen/upgrader#123]
After looking through the source code, it seems that the package is searching for the text What's new and then using that section to display, however some apps don't have that "What's new" text in their release notes, like in my case and subsequently the error above was given. Could you change the implementation to (if What's new isn't found, just use the first section). Thank you :)

**Comment by larryaasen** [comment]
@yassinsameh Can you provide the app Play Store id?

@Williano Thoughts on this?

**Comment by Williano** [comment]
Yes I agree, I will have to look into it and modify it.

**Comment by lauroboeni** [comment]
@Williano any updates in this regards? :) I'm having the same issue with my app :)

**Comment by larryaasen** [comment]
@yassinsameh We need some way to reproduce this issue. Do you have a unit test or example using the bin/playstore_lookup.dart app?

**Comment by yassinsameh** [comment]
Hi @larryaasen , you can use the app id  com.konduko.standapp_v4 to test, or any app without the what's new section written would work actually.

> @yassinsameh We need some way to reproduce this issue. Do you have a unit test or example using the bin/playstore_lookup.dart app?

**Comment by Williano** [comment]
@lauroboeni I have started looking into it and will use the id provided by @yassinsameh to fix it.

**Comment by larryaasen** [comment]
I just released version 3.6.0 that has a fix in it 98ba5302a1ff0bc04c9793adfa400f212cc765d9. Thanks to @yassinsameh for the change: `orElse:()=> sectionElements[0]`. I added a unit test for this case and updated the documentation.
