### ISSUE TITLE
Issue with lastversion alerted during testing

### ISSUE THREAD

**Issue by ameya730** [larryaasen/upgrader#126]
![image](https://user-images.githubusercontent.com/68287548/133656368-fa3fae8e-c1b6-482d-90f2-175ae2c9c43b.png)

Hi,
I am using the upgrader plugin for my application. While testing I am getting the error 'Null check operator used on a null value' on _lastVersionAlerted. Please find attached the screenshot confirming the same.

Is this normal or am I making a mistake ?

Regards,
Ameya

**Comment by larryaasen** [comment]
Can you attach your upgrade console log?

**Comment by ameya730** [comment]
Hi Larry,
Sorry but there was a bit of an urgency in deploying the app. Hence, I used a different package for the moment.
In a couple of days, I'll create a dummy app, try to recreate the error and share the upgrade console log with you.
Regards,
Ameya

**Comment by larryaasen** [comment]
Seems like some of the log is missing and I need to see all of it. It should normally look like this:
```
flutter: upgrader: languageCode: en
flutter: upgrader: build UpgradeAlert
flutter: upgrader: default operatingSystem: ios 11.4
flutter: upgrader: operatingSystem: ios
flutter: upgrader: platform: TargetPlatform.iOS
flutter: upgrader: package info packageName: com.google.Maps
flutter: upgrader: package info appName: Upgrader
flutter: upgrader: package info version: 1.0.0
flutter: upgrader: countryCode: US
flutter: upgrader: blocked: false
flutter: upgrader: debugDisplayAlways: false
flutter: upgrader: debugDisplayOnce: false
flutter: upgrader: hasAlerted: false
flutter: upgrader: appStoreVersion: 5.79
flutter: upgrader: installedVersion: 1.0.0
flutter: upgrader: minAppVersion: null
flutter: upgrader: isUpdateAvailable: true
flutter: upgrader: shouldDisplayUpgrade: true
flutter: upgrader: shouldDisplayReleaseNotes: true
flutter: upgrader: showDialog title: Update App?
flutter: upgrader: showDialog message: A new version of Upgrader is available! Version 5.79 is now available-you have 1.0.0.
flutter: upgrader: showDialog releaseNotes: Thanks for using Google Maps! This release brings bug fixes that improve our product to help you discover new places and navigate to them.
```

**Comment by larryaasen** [comment]
@ameya730 Are you still having this issue?

**Comment by njonbayou** [comment]
Hi this issue seems persistent. Error throws to upgrader.dart line 715 as _CastError (null check used on null value). I have seen update window only once when i mistakenly did not include clearsavedsettings(), now the second time it threw this error. Can you help?
P.S: log i have is below
flutter: upgrader.ITunesResults.version: RangeError (index): Invalid value: Valid value range is empty: 0
flutter: upgrader.ITunesResults.trackViewUrl: RangeError (index): Invalid value: Valid value range is empty: 0
flutter: upgrader.ITunesResults.releaseNotes: RangeError (index): Invalid value: Valid value range is empty: 0
flutter: upgrader.ITunesResults.description: RangeError (index): Invalid value: Valid value range is empty: 0

**Comment by njonbayou** [comment]
Im guessing it doesnt see the ios app version. (BTW my app is iOS)

**Comment by larryaasen** [comment]
@njonbayou Seems like some of the upgrader log is missing and I need to see all of it. See comments above.

**Comment by njonbayou** [comment]
How can i retrieve it?

**Comment by njonbayou** [comment]
I have looped around this issue by first commenting out line 715, and then uncommenting back!

**Comment by larryaasen** [comment]
All of the lines that start with `flutter:` - turn on the log by using `debugLogging: true`.

**Comment by njonbayou** [comment]
Where exactly should i put debugLogging: true?

**Comment by larryaasen** [comment]
@njonbayou Like this:
```
          body: UpgradeAlert(
            debugLogging: true,
            child: Center(child: Text('Checking...')),
          )
```
