### ISSUE TITLE
How i can see alert without deploing app to Store?

### ISSUE THREAD

**Issue by rGradov** [larryaasen/upgrader#135]
I try to see this alert without deploing into stores. I mean, apple Sotre and Google play doesnt know about my app. how i can see this alert ( with mock data or with something else). because now i'm just see the infinity 'checking...' text.

**Comment by pomarec** [comment]
Are you searching for `debugAlwaysUpgrade` parameter ?

**Comment by larryaasen** [comment]
@rGradov Are you still having an issue?

**Comment by larryaasen** [comment]
@rGradov Did you try using the `debugDisplayAlways` parameter?
