### ISSUE TITLE
durationUntilAlertAgain don`t work?

### ISSUE THREAD

**Issue by PaulKsi** [larryaasen/upgrader#136]
Stack(children: <Widget>[
              UpgradeAlert(
                showIgnore: false,
                durationUntilAlertAgain: 1,
                showReleaseNotes: false,
                child: Center(child: Text('')),
              )
            ]),

durationUntilAlertAgain: 1, showing as 

The named parameter 'durationUntilAlertAgain' isn't defined.
Try correcting the name to an existing named parameter's name, or defining a named parameter with the name 'durationUntilAlertAgain'.dart(undefined_named_parameter)

**Comment by larryaasen** [comment]
`durationUntilAlertAgain` was added in version 2.8.0. What version are you using?

**Comment by larryaasen** [comment]
@PaulKsi Are you still having this issue?
