### ISSUE TITLE
minAppVersion format same as pubsec.yaml?

### ISSUE THREAD

**Issue by PaulKsi** [larryaasen/upgrader#137]
minAppVersion format should be same as pubsec.yaml?
for example -
1.1.4+14

**Comment by utkudenis** [comment]
Hi @larryaasen, how can ı set minappversion from appcast file both android and ios ? 
I tried <sparkle:minimumSystemVersion>1.1.0</sparkle:minimumSystemVersion> but didn't work. 
it is still null 
![image](https://user-images.githubusercontent.com/68633376/149830704-6aa40518-c8a1-4e7c-80af-9f2676157217.png)
![image](https://user-images.githubusercontent.com/68633376/149830783-b7922cdb-53e4-4bdf-88a7-2d041cc17738.png)
And for Turkish version, Release notes are still in english, 
Uygulamayı Güncelle? is not a good turkish grammer. It should be different and without '?'
and general text tecture(grammer,sentences, sequence) not good :( 
If there is an opportunity I want to impove turkish texts and style. Grammer of turkish is different from English.

**Comment by larryaasen** [comment]
Did you try isCriticalUpdate?

**Comment by larryaasen** [comment]
If you have improvements for Turkish, please send them over. Thanks.

**Comment by utkudenis** [comment]
I didn't find anything about isCriticalUpdate in readme and pub.dev can you share example or code bloc ?

**Comment by larryaasen** [comment]
I don’t have an example but the test file has it: https://github.com/larryaasen/upgrader/blob/f188f624d63e2cf627687754333d9d487d2c8173/test/testappcast.xml
