### ISSUE TITLE
Can bypass upgrade now

### ISSUE THREAD

**Issue by malvinpratama** [larryaasen/upgrader#139]
flutter: upgrader: languageCode: id
flutter: upgrader: build UpgradeAlert
flutter: upgrader: default operatingSystem: ios 15.0.2
flutter: upgrader: operatingSystem: ios
flutter: upgrader: platform: TargetPlatform.iOS
flutter: upgrader: package info packageName: com.usewamotor.usewa.ios
flutter: upgrader: package info appName: USewa Motor
flutter: upgrader: package info version: 1.0.9
flutter: upgrader: appcast is available for this platform
flutter: upgrader: appcast item count: 2
flutter: upgrader: appcast best item version: 1.0.10
flutter: upgrader: blocked: false
flutter: upgrader: debugDisplayAlways: false
flutter: upgrader: debugDisplayOnce: false
flutter: upgrader: hasAlerted: false

upgrader version 3.6.0

The story case is like this.

1. Open app and dialog show.
2. click update now.
3. back to app without update.
4. the dialog is disappear. so you can bypass dialog.

I think you shouldn't close the dialog (navigator pop).

**Comment by larryaasen** [comment]
In this case the user tapped the update button so there is nothing else for the user to do with the dialog, so it was closed. If you want the user to be forced to update, since you are using appcast, just add criticalUpdate to your item:
```
<sparkle:tags> <sparkle:criticalUpdate /> </sparkle:tags> 
```

**Comment by coup** [comment]
I am facing the same issue here is my config code.

1. Open the app
2. Upgrader Dialog appears
3. click on update button 
4. do nothing
5. go back to app 
**6. No dialog appears**  

how can i make the app to display the dialog until user not updates the app

```

UpgradeAlert(
      messages: OT360UpgraderMessage(),
      countryCode: 'US',
      showIgnore: false,
      showLater: false,
      canDismissDialog: false,
      shouldPopScope: () => false,
      child: contaner()

)
```

**Comment by larryaasen** [comment]
@coup Add this to UpgradeAlert: `durationToAlertAgain: const Duration()`
