### ISSUE TITLE
How to force updates?

### ISSUE THREAD

**Issue by cytryn** [larryaasen/upgrader#14]
So I have a few questions here on how the package works.

I want to force updates base on the semantic versioning. So if the app updates from 1.0.0 to 2.0.0, I want to be able to force my users to see the message and update, otherwise just pop the alert with default settings.

But for that I would need the version, what is the best way to do that? Because I don't see any public Futures or methods with callbacks.

something like that?
```
Upgrader().installAppStoreListingURL(myURL);
if (Upgrader().currentAppStoreVersion().someparsing() > Upgrader().currentInstalledVersion().someparsing()) {
 bool  _shouldForceUpgrade = true;
}
```

**Comment by larryaasen** [comment]
@cytryn When you say "force update/upgrade", are you saying you want the user to be prevented from running the app? Lock the user out of the app?

**Comment by cytryn** [comment]
> @cytryn When you say "force update/upgrade", are you saying you want the user to be prevented from running the app? Lock the user out of the app?

Exactly... I want to show a message to the user saying that there is a new version fixing a bug or something like that.

**Comment by cytryn** [comment]
> @cytryn When you say "force update/upgrade", are you saying you want the user to be prevented from running the app? Lock the user out of the app?

Exactly... I want to show a message to the user saying that there is a new version fixing a bug or something like that.

**Comment by larryaasen** [comment]
Unfortunately, this package is not able to provide the version back to the app. You can call `Upgrader().isUpdateAvailable()` directly. Look at the file upgrader_test.dart for an example of this.

**Comment by sarinupreti** [comment]
a minimum version feature should be added. so for use under certain version needs to force update the app in order to work. I need this feature as well.

**Comment by larryaasen** [comment]
@cytryn @sarinupreti There is update to this package that now supports minimum app version in PR https://github.com/larryaasen/upgrader/pull/39. Check it out.
