### ISSUE TITLE
Adding the plugin breaks web apps

### ISSUE THREAD

**Issue by Zazo032** [larryaasen/upgrader#145]
Using version `3.11.0`, when adding `UpgradeAlert` to a page that is also displayed on Flutter Web, the app breaks with the following error:
```
Unsupported operation: Platform._operatingSystem
```
If the plugin doesn't support web, there should be a no-op way to add the plugin without breaking mobile implementations. A solution could be to move `Platform` calls from `dart:io` to [`universal_platform`](https://pub.dev/packages/universal_platform)

**Comment by Zazo032** [comment]
Another option: [`universal_io`](https://github.com/dint-dev/universal_io)

**Comment by larryaasen** [comment]
The exception was thrown here:
`packages/upgrader/src/upgrader.dart 116:37`

**Comment by larryaasen** [comment]
Fixed in PR https://github.com/larryaasen/upgrader/pull/148.

**Comment by larryaasen** [comment]
Fixed.
