### ISSUE TITLE
The update button is not showing

### ISSUE THREAD

**Issue by mohammad-alnimer1** [larryaasen/upgrader#147]
I/flutter (13003): end
I/flutter (13003): upgrader: build UpgradeAlert
I/flutter (13003): upgrader: blocked: true
I/flutter (13003): upgrader: debugDisplayAlways: true
I/flutter (13003): upgrader: debugDisplayOnce: false
I/flutter (13003): upgrader: hasAlerted: false
I/flutter (13003): upgrader: shouldDisplayUpgrade: true
I/flutter (13003): upgrader: shouldDisplayReleaseNotes: true
I/flutter (13003): upgrader: showDialog title: Update App?
I/flutter (13003): upgrader: showDialog message: A new version of Salwa & Fairouz is available! Version 0.0.1 is now available-you have 2.2.3.
I/flutter (13003): upgrader: showDialog releaseNotes: de
![Screenshot_20211206-133639](https://user-images.githubusercontent.com/76480201/144839526-dde7e284-599b-4da8-becf-98432c6d5bcb.jpg)

**Comment by mohammad-alnimer1** [comment]
I/flutter (24889): upgrader: package info packageName: com.vibes.salwawfairouz
I/flutter (24889): upgrader: package info appName: Salwa & Fairouz
I/flutter (24889): upgrader: package info version: 2.0.0
I/flutter (24889): upgrader: appcast is available for this platform
I/flutter (24889): upgrader: appcast item count: 1
I/flutter (24889): upgrader: appcast best item version: 2.1.0
I/flutter (24889): upgrader: blocked: true
I/flutter (24889): upgrader: debugDisplayAlways: false
I/flutter (24889): upgrader: debugDisplayOnce: false
I/flutter (24889): upgrader: hasAlerted: false
I/flutter (24889): upgrader: appStoreVersion: 2.1.0
I/flutter (24889): upgrader: installedVersion: 2.0.0
I/flutter (24889): upgrader: minAppVersion: 2.1.0
I/flutter (24889): upgrader: isUpdateAvailable: true
I/flutter (24889): upgrader: shouldDisplayUpgrade: true
I/flutter (24889): upgrader: shouldDisplayReleaseNotes: true
I/flutter (24889): upgrader: showDialog title: Update App?
I/flutter (24889): upgrader: showDialog message: A new version of Salwa & Fairouz is available! Version 2.1.0 is now available-you have 2.0.0.
I/flutter (24889): upgrader: showDialog releaseNotes: desc

**Comment by larryaasen** [comment]
@mohammad-alnimer1 Can you post the code where you are using `UpgradeAlert`?

**Comment by mohammad-alnimer1** [comment]
final appcastURL = 'https://firebasestorage.googleapis.com/v0/b/flash-chat-9bbda.appspot.com/o/appcast.xml?alt=media&token=70bfe573-c2ab-46b7-bdb2-a3aeb6278d32';
    final cfg = AppcastConfiguration(url: appcastURL, supportedOS: ['android']);

    return MaterialApp(
      title: widget.appName,
      theme: widget.theme,
      debugShowCheckedModeBanner: false,
      home: UpgradeAlert(
        appcastConfig: cfg,
        showLater: false,
        showIgnore: false,
        // debugAlwaysUpgrade: true,
        minAppVersion: '2.1.0',
        debugLogging: true,

        dialogStyle: UpgradeDialogStyle.material,
        child:getWidget(),
      )
    );

**Comment by mohammad-alnimer1** [comment]
<rss xmlns:sparkle="https://play.google.com/store/apps/details?id=com.vibes.salwawfairouz" version="2.0">
<channel>
<title>Help Code TJCODE- Appcast</title>
<item>
<title>Version 2.1.0</title>
<description>desc</description>
<pubDate>Tue, 08 Jun 2021 12:00:00 +0000</pubDate>
<enclosure url="https://play.google.com/store/apps/details?id=com.vibes.salwawfairouz" sparkle:version="2.1.0" sparkle:os="android"/>
</item>
</channel>
</rss>

**Comment by mohammad-alnimer1** [comment]
<rss xmlns:sparkle="https://play.google.com/store/apps/details?id=com.vibes.salwawfairouz" version="2.0">
<channel>
<title>Help Code TJCODE- Appcast</title>
<item>
<title>Version 2.1.0</title>
<description>desc</description>
<pubDate>Tue, 08 Jun 2021 12:00:00 +0000</pubDate>
<enclosure url="https://play.google.com/store/apps/details?id=com.vibes.salwawfairouz" sparkle:version="2.1.0" sparkle:os="android"/>
</item>
</channel>
</rss>

**Comment by larryaasen** [comment]
@mohammad-alnimer1 I'm not sure what is wrong here. Can you attach a screenshot of the UpgradeAlert displayed in your app?

**Comment by Ghoral** [comment]
I have faced the same issue.
Steps:
1. Update alert pops up
2. Click on update now
3. Navigates to playstore but the button is still open (expected Update)

![Screenshot_20220105-102806_2 (1)](https://user-images.githubusercontent.com/49188349/148162042-654c3ef3-4c73-494f-82d4-8339f0ab8337.png)

**Comment by Ghoral** [comment]
I have used only update alert widget and no other configuration.
![code](https://user-images.githubusercontent.com/49188349/148162231-d7cac564-1a83-4b2c-8b4f-de596e3dbefe.png)

**Comment by larryaasen** [comment]
@Ghoral The screenshot you provided is taken from the Google Play Store. The upgrader package does not control the buttons displayed on the Play Store.

- What version is being displayed on the Play Store (can you add a screenshot?)
- What is the upgrader log showing? (can you attach the upgrader log?)

**Comment by Ghoral** [comment]
ok sure. but how can I get upgrader log ?

**Comment by Ghoral** [comment]
Upgrader Log 

I/flutter (15888): upgrader: appStoreVersion: 1.15.1
I/flutter (15888): upgrader: installedVersion: 1.15.0
I/flutter (15888): upgrader: minAppVersion: null
I/flutter (15888): upgrader: isUpdateAvailable: true
I/flutter (15888): upgrader: shouldDisplayUpgrade: true
I/flutter (15888): upgrader: shouldDisplayReleaseNotes: true
I/flutter (15888): upgrader: showDialog title: Update App?
I/flutter (15888): upgrader: showDialog message: A new version of APP_NAME is available! Version 1.15.1 is now available-you have 1.15.0.
I/flutter (15888): upgrader: showDialog releaseNotes: - notes
I/flutter (15888): upgrader: button tapped: update now
I/flutter (15888): upgrader: launching: https://play.google.com/store/apps/details?id=identifier
I/UrlLauncher(15888): component name for https://play.google.com/store/apps/details?id=identifier is {com.android.vending/com.google.android.finsky.activities.MainActivity}

Play store version 
![Screenshot_20220107-135044 (1)](https://user-images.githubusercontent.com/49188349/148513017-e52b0607-1ded-4666-9ff5-03b0b07805b1.png)

**Comment by larryaasen** [comment]
@Ghoral Based on the information provide it appears that upgrader is behaving as designed. Tapping on the Update button on the upgrader widget takes the user to the Play Store. I don't see a problem here with upgrader. Perhaps there is an issue with the Play Store. Maybe the account being used on the Play Store does not match the account used on the phone.

**Comment by Ghoral** [comment]
Hello @larryaasen.
I will do some workaround to see if I am missing something.

**Comment by AlaaGitHub2020** [comment]
I faced the same issue with my app !! Could you please tell me did you fixed it or did you know why the update did not show on the google store after navigator the user there ?! @Ghoral

**Comment by Ghoral** [comment]
@AlaaGitHub2020 No I haven't found any solution yet.

**Comment by deepak16paliwal** [comment]
@larryaasen it is still an issue because when we do live app from AppStore then Your Upgrader get that information but on AppStore it will take 30 minutes to 1 hour fetch that updated app.

**Comment by larryaasen** [comment]
@mohammad-alnimer1 Is this still an issue?

**Comment by innerk** [comment]
hi @larryaasen  yes it's still an issue on google play,
the button says open and not upgrade

**Comment by innerk** [comment]
@larryaasen already found the answer [here](https://stackoverflow.com/questions/32086791/google-play-store-showing-open-button-instead-of-update-button)

**Comment by larryaasen** [comment]
It seems that the Play Store button does not alway change from Open to Update immediately as we would expect. Maybe Google can fix that.
