### ISSUE TITLE
How to get to playstore/appstore onCLickUpdate ?

### ISSUE THREAD

**Issue by dukesx** [larryaasen/upgrader#149]
Hi , 

This may not be an issue but i cant seem to figure out, how will i redirect someone to playstore on clicking "update button" ? the damn function requires a bool and no "launcher" can work without async. I am stuck here.

**Comment by larryaasen** [comment]
@dukesx You don't need to use the onUpdate() callback. The code will automatically take the user to the playstore/app store when tapping on the update button.

**Comment by dukesx** [comment]
Oh okay ! thanks @larryaasen !
