### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by EdoardoVignati** [larryaasen/upgrader#151]
Hi. I'm wondering if in the README the `code` argument should be `countryCode`.

` UpgradeAlert(messages: UpgraderMessages(countryCode: 'es')); `

instead of:

` UpgradeAlert(messages: UpgraderMessages(code: 'es')); `

**Comment by larryaasen** [comment]
@EdoardoVignati The named parameter 'countryCode' isn't defined. Looking at the code you will see this, where `code` is the parameter:
```
  /// Provide a [code] to override the system-reported default locale.
  UpgraderMessages({String? code})
      : languageCode = (code ?? findLanguageCode()) {
    assert(languageCode.isNotEmpty);
  }
```

**Comment by EdoardoVignati** [comment]
Thank you very much for your reply. Probably I got confused about  UpgraderMessages and UpgraderAlert. Thank you again. Great plugin.
