### ISSUE TITLE
upgrader: Can't find an app in the Play Store with the id: xxx.xxx.xxx

### ISSUE THREAD

**Issue by tonyteo72** [larryaasen/upgrader#154]
I got the above error when using upgrader in my flutter project. I have upload my test app into Google Play Store as Internal Testing. I checked and my app id is correct in the Play Store. 

Does upgrader only work when my app is in Production release ?

**Comment by larryaasen** [comment]
Yes, the app page for the app must be on the Google Play store. If you can navigate to the app page in a browser, it will work.

**Comment by MaxiStefan** [comment]
Hi,

@larryaasen So is it correct that upgrader only works when the application is released on the Production track? I have so far tried internal app testing and closed testing and the API does not seem to be able to see new versions available, despite the testing page showing the Update Button.

Additionally, does upgrader then work on TestFlight or is it the same thing.

Thanks in advance!

**Comment by polarby** [comment]
Hi, I have the same problem. The app is currently in the Open testing track (Google play). Shouldn't that work as well?

**Comment by larryaasen** [comment]
The app needs to be available using the Play Store URL on Android like this: https://play.google.com/store/apps/details?id=com.moonwink.treasury
For iOS, the app must be released on the App Store, not on TestFlight.

**Comment by polarby** [comment]
@larryaasen Could it be that it will only detect apps if it is in testing mode in the US? I have the app only available for testers in Germany and even though the link you provided works, upgrader still can't find it...

**Comment by larryaasen** [comment]
@polarby Which link works for you?

**Comment by polarby** [comment]
The link you have posted: `https://play.google.com/store/apps/details?id=<xxx.xxx.xxx>` (without the <>). It still doesn't work out! Are there any other reasons why it might tell me: 
```
upgrader: Can't find an app in the Play Store with the id: xxx.xxx.xxx
```

**Comment by larryaasen** [comment]
@polarby  The app has to be published and have an active release. Is your app published?

**Comment by polarby** [comment]
It's weird, it took about a week (until available on mobile) after the approval and releasing the open testing version. At this point the app was already viewable on the web version of Google play. After the week it was able to detect the app. Thanks!

**Comment by larryaasen** [comment]
Glad it worked.
