### ISSUE TITLE
Doesn't work when app not available on the US App Store

### ISSUE THREAD

**Issue by skol101** [larryaasen/upgrader#16]
Any lookup (by id, by app bundle id) returns null if the app isn't available on the US App Store.

Please, fix or suggest a workaround.

**Comment by larryaasen** [comment]
@skol101 I assume the iTunes API is returning an empty response when the app is not available on the US App Store. In that case, there is no version of the app to upgrade, and thus there should not be a message or alert displayed to the user. Can you explain more about your issue, including the messages from the log, and possibly any screenshots?

**Comment by skol101** [comment]
The issue is that the plugin or iTunes Api call doesn't  check whether app is available on other markets. For instance, if I just open https://apps.apple.com/app/id1478293930 in the browser, the App Store will open even when the app isn't available on the US app store.

**Comment by larryaasen** [comment]
What country codes are valid for the 1478293930 app?

**Comment by skol101** [comment]
We've made it available in the US with the recent update, though not in Russia ('ru' I believe).

**Comment by larryaasen** [comment]
This package is not designed to handle App Stores outside of US. However, it may not be that difficult to add country support. The URL used by the iTunes class is:
https://itunes.apple.com/lookup?id=1478293930
which default the county to US. When I added the query parameter country=RU, 
https://itunes.apple.com/lookup?id=1478293930&country=RU
it returns no results:
```
{
 "resultCount":0,
 "results": []
}
```

This URL https://itunes.apple.com/lookup?id=1478293930&country=CA seems to return the Canadian store listing.

I may be able to get the store country ID from a plugin and use that in the URL. Let me look into that.

**Comment by hivesey** [comment]
Hi, 
I would like to express interest in having this plugin working for apps in the store outside the US too. Is that fix underway?

Thanks,

**Comment by larryaasen** [comment]
@hivesey This package does not support multiple countries for iOS. It only supports the US app store at this time. However, there is a quick patch you could make if you want to support only one country that is not US. To make that patch, fork this repo, and change the following line to the country code of your choice:
https://github.com/larryaasen/upgrader/blob/a22e996f6900ef2ce9eb7310d76cfde0cd2ebc05/lib/src/upgrader.dart#L147

**Comment by larryaasen** [comment]
@skol101 @hivesey  There is an update to this package that now supports using the country code from the locale, which merged in PR #39. Check it out.
