### ISSUE TITLE
[Feature request] add method call for minimum app version popup

### ISSUE THREAD

**Issue by KorbinianMossandl** [larryaasen/upgrader#160]
We would like to put our app into offline mode if the app is below the minimum app version.
So it would be really nice if we could add a method call to the force update popup to handle this case.

**Comment by larryaasen** [comment]
@KorbinianMossandl There is an updated callback method `willDisplayUpgrade` in version 4.0.0 that provides the minAppVersion, installedVersion, and appStoreVersion. You could implement this callback, determine if the app is below the minimum, and put the app in offline mode when it is below. See this section in the [README](https://pub.dev/packages/upgrader#customization).

**Comment by KorbinianMossandl** [comment]
that sounds like a perfect solution. i will give it a try. thanks!
