### ISSUE TITLE
Couldn't get PlayStoreResults.version

### ISSUE THREAD

**Issue by xuanzong06** [larryaasen/upgrader#165]
Hi I'm a new flutter developer , I have a question about troubling getting version from PlayStore using upgrader package

I wonder why I could not get PlayStoreResult.version information
Is there any INTERNET permission should I check?

Thanks!

I/flutter (21099): upgrader: languageCode: en
I/flutter (21099): upgrader: build UpgradeAlert
I/flutter (21099): upgrader: default operatingSystem: android sdk_gphone64_x86_64-userdebug 12
I/flutter (21099): upgrader: operatingSystem: android
I/flutter (21099): upgrader: platform: TargetPlatform.android
I/flutter (21099): upgrader: isAndroid: true, isIOS: false, isLinux: false, isMacOS: false, isWindows: false, isFuchsia: false, isWeb: false
I/flutter (21099): upgrader: package info packageName: com.seachaunt.seastco
I/flutter (21099): upgrader: package info appName: seastco
I/flutter (21099): upgrader: package info version: 0.1.0
I/flutter (21099): upgrader: countryCode: US
I/flutter (21099): upgrader: PlayStoreResults.version exception: Bad state: No element
I/flutter (21099): upgrader: PlayStoreResults.releaseNotes exception: RangeError (index): Invalid value: Valid value range is empty: 0
I/flutter (21099): upgrader: PlayStoreResults.description exception: RangeError (index): Invalid value: Valid value range is empty: 0
I/flutter (21099): upgrader: blocked: false
I/flutter (21099): upgrader: debugDisplayAlways: false
I/flutter (21099): upgrader: debugDisplayOnce: false
I/flutter (21099): upgrader: hasAlerted: false
I/flutter (21099): upgrader: appStoreVersion: null
I/flutter (21099): upgrader: installedVersion: 0.1.0
I/flutter (21099): upgrader: minAppVersion: null
I/flutter (21099): upgrader: isUpdateAvailable: false
I/flutter (21099): upgrader: shouldDisplayUpgrade: false
I/flutter (21099): upgrader: shouldDisplayReleaseNotes: false
D/EGL_emulation(21099): app_time_stats: avg=729.59ms min=235.23ms max=1223.94ms count=2

**Comment by larryaasen** [comment]
I'm not sure why it cannot parse the version number. Run this app that is part of the upgrader package and it may help you figure this out.
README: https://github.com/larryaasen/upgrader#command-line-app---android
```
$ dart playstore_lookup.dart id=com.google.android.apps.mapslite
```

**Comment by xuanzong06** [comment]
Hi Thanks for replying

After I run the command 
it return : Error when reading 'playstore_lookup.dart': No such file or directory.

**Comment by xuanzong06** [comment]
Hi below is I run command switch to upgrade dir and run result

yezac-MacBook-Pro:bin yezac$ dart playstore_lookup.dart id=com.google.android.apps.mapslite
Error: Couldn't resolve the package 'upgrader' in 'package:upgrader/src/play_store_search_api.dart'.
playstore_lookup.dart:10:8: Error: Not found: 'package:upgrader/src/play_store_search_api.dart'
import 'package:upgrader/src/play_store_search_api.dart';
       ^
playstore_lookup.dart:28:21: Error: Method not found: 'PlayStoreSearchAPI'.
  final playStore = PlayStoreSearchAPI();
                    ^^^^^^^^^^^^^^^^^^
playstore_lookup.dart:38:23: Error: Undefined name 'PlayStoreResults'.
  final description = PlayStoreResults.description(results);
                      ^^^^^^^^^^^^^^^^
playstore_lookup.dart:39:25: Error: Undefined name 'PlayStoreResults'.
  final minAppVersion = PlayStoreResults.minAppVersion(results);
                        ^^^^^^^^^^^^^^^^
playstore_lookup.dart:40:24: Error: Undefined name 'PlayStoreResults'.
  final releaseNotes = PlayStoreResults.releaseNotes(results);
                       ^^^^^^^^^^^^^^^^
playstore_lookup.dart:41:19: Error: Undefined name 'PlayStoreResults'.
  final version = PlayStoreResults.version(results);
                  ^^^^^^^^^^^^^^^^
yezac-MacBook-Pro:bin yezac$

**Comment by larryaasen** [comment]
@xuanzong06  You may need to download the GitHub repo to run this. It runs fine for me.

**Comment by hyoungphi** [comment]
@xuanzong06 Try $flutter pub get in the cloned repo. It worked to me

**Comment by hyoungphi** [comment]
@larryaasen I am at Korea.
At play_store_search_api.dart, requests to https://play.google.com/store/apps/details?id={app_id}. And playstore at Korea responses different.
It was succeeded to get information when I modify some code to requests to https://play.google.com/store/apps/details?id={app_id}&gl=US

I guess some rigon have different website and it might be the next version of playstore. I think google is doing A/B testing.

> Hi below is I run command switch to upgrade dir and run result
> 
> yezac-MacBook-Pro:bin yezac$ dart playstore_lookup.dart id=com.google.android.apps.mapslite Error: Couldn't resolve the package 'upgrader' in 'package:upgrader/src/play_store_search_api.dart'. playstore_lookup.dart:10:8: Error: Not found: 'package:upgrader/src/play_store_search_api.dart' import 'package:upgrader/src/play_store_search_api.dart'; ^ playstore_lookup.dart:28:21: Error: Method not found: 'PlayStoreSearchAPI'. final playStore = PlayStoreSearchAPI(); ^^^^^^^^^^^^^^^^^^ playstore_lookup.dart:38:23: Error: Undefined name 'PlayStoreResults'. final description = PlayStoreResults.description(results); ^^^^^^^^^^^^^^^^ playstore_lookup.dart:39:25: Error: Undefined name 'PlayStoreResults'. final minAppVersion = PlayStoreResults.minAppVersion(results); ^^^^^^^^^^^^^^^^ playstore_lookup.dart:40:24: Error: Undefined name 'PlayStoreResults'. final releaseNotes = PlayStoreResults.releaseNotes(results); ^^^^^^^^^^^^^^^^ playstore_lookup.dart:41:19: Error: Undefined name 'PlayStoreResults'. final version = PlayStoreResults.version(results); ^^^^^^^^^^^^^^^^ yezac-MacBook-Pro:bin yezac$

**Comment by larryaasen** [comment]
@hyoungphi So, what you are saying, is that `&gl=US` should be appended to the existing Play Store URL that is currently being used? If so, should the value always be `US`?

**Comment by larryaasen** [comment]
@hyoungphi I see this works and brings up the South Korea version of the Play Store.
https://play.google.com/store/apps/details?id=com.moonwink.treasury&gl=KR

**Comment by HectorHumanitcare** [comment]
Hi, I have been running the dart playstore_lookup.dart (id=com.google.android.apps.mapslite) with the following message: 
```
upgrader: PlayStoreResults.description exception: RangeError (index): Invalid value: Valid value range is empty: 0
upgrader: PlayStoreResults.description exception: RangeError (index): Invalid value: Valid value range is empty: 0
upgrader: PlayStoreResults.releaseNotes exception: RangeError (index): Invalid value: Valid value range is empty: 0
upgrader: PlayStoreResults.version exception: Bad state: No element
playstore_lookup description: null
playstore_lookup minAppVersion: null
playstore_lookup releaseNotes: null
playstore_lookup version: null
playstore_lookup all results:
#document
```
I also tried it in my app (with this pubspec.lock): 
```
upgrader:
    dependency: "direct main"
    description:
      name: upgrader
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.2.0"
```
With the same: `upgrader: PlayStoreResults.version exception: Bad state: No element`

For more context, I am from Spain so the url calls to the ES market, but I also tried adding &gl=US for the `dart playstore_lookup.dart` (so the url will be `https://play.google.com/store/apps/details?id=com.google.android.apps.mapslite&gl=US`) with the same results.

I have tried to look at the play_store_search_api.dart, more in concrete in:

```
 /// Return field version from Play Store results.
  static String? version(Document response) {
    String? version;
    try {
      final additionalInfoElements = response.getElementsByClassName('hAyfc');
      print(additionalInfoElements) //This prints []
      final versionElement = additionalInfoElements.firstWhere(
        (elm) => elm.querySelector('.BgcNfc')!.text == 'Current Version',
      );
      final storeVersion = versionElement.querySelector('.htlgb')!.text;
      // storeVersion might be: 'Varies with device', which is not a valid version.
      version = Version.parse(storeVersion).toString();
    } catch (e) {
      print('upgrader: PlayStoreResults.version exception: $e');
    }
```
And it doesn't find an element by ClassName 'hAyfc'. I don't know if it's temporary because yesterday I did obtain the information correctly (in my app and using playstore_lookup.dart). Or maybe google is doing some A/B test as @hyoungphi has mentioned, because even thought yesterday worked, it also failed sometimes. 

I don't know if someone have some information about it or has found the same problem. Just to check if it was temporary I will try to test it again on Monday and try to bring some updates (if i can).

**Comment by HectorHumanitcare** [comment]
I have seen that the problem is related to the issue #179, so the Google layout is different, so it doesn't find the information in the same place.

**Comment by larryaasen** [comment]
@HectorHumanitcare Try the latest version 4.6.0 to see if that works for you now.
https://pub.dev/packages/upgrader
