### ISSUE TITLE
upgrader is not showing update on clicking on play store link , only showing "open"

### ISSUE THREAD

**Issue by maysha18** [larryaasen/upgrader#167]
/flutter (32400): upgrader: appcast item count: 2
I/flutter (32400): upgrader: appcast best item version: 1.0.8
I/flutter (32400): upgrader: blocked: false
I/flutter (32400): upgrader: debugDisplayAlways: false
I/flutter (32400): upgrader: debugDisplayOnce: false
I/flutter (32400): upgrader: hasAlerted: false
I/flutter (32400): upgrader: appStoreVersion: 1.0.8
I/flutter (32400): upgrader: installedVersion: 1.0.7
I/flutter (32400): upgrader: minAppVersion: 1.0.7
I/flutter (32400): upgrader: isUpdateAvailable: true
I/flutter (32400): upgrader: isTooSoon: true
I/flutter (32400): upgrader: shouldDisplayUpgrade: false
I/flutter (32400): upgrader: shouldDisplayReleaseNotes: true
```
Also, please include the upgrader version number from the pubspec.lock file, which should look something like this:
```
  upgrader:
    dependency: "upgrader: ^3.14.0"
    description:
      path: ".."
      relative: true
    source: path
    version: "^3.14.0"

**Comment by larryaasen** [comment]
This is the key this your situation:
```
I/flutter (32400): upgrader: isTooSoon: true
```
That means it will not prompt the user because of this parameter:
```
durationUntilAlertAgain: duration until alerting user again, which defaults to 3 days
```

**Comment by maysha18** [comment]
but it still showing "open" in play store ??

**Comment by larryaasen** [comment]
The upgrader package does not control what is being displayed on the Play Store. It probably says open to alert the user to open the app since it has been installed. You can only test that upgrader opens the correct URL and sends the user to the correct page.
