### ISSUE TITLE
How to change the default text?

### ISSUE THREAD

**Issue by Adrek** [larryaasen/upgrader#17]
First, congratulate them on the application. It works very well.

Is there any way to **change** the default text "**A new version of [app_name] is available! Version [X.X] is now available you have [X.0.0]**" to customText ?. To be able to change it to any language like _buttonTitleIgnore, buttonTitleLater, buttonTitleUpdate, title or prompt_.

**Comment by larryaasen** [comment]
The latest upgrade to this package adds support for localizations and custom messages. Please see [Customizing the display](https://github.com/larryaasen/upgrader#customizing-the-display) section on README for more details. This was added by PR https://github.com/larryaasen/upgrader/pull/38.

**Comment by Adrek** [comment]
Thanks, really.
