### ISSUE TITLE
upgrader: instantiated. after Flutter upgrade to 3.0 and upgrader upgrader: ^4.1.1

### ISSUE THREAD

**Issue by ziyadmansy** [larryaasen/upgrader#171]
debug console:
upgrader: PlayStoreResults.description exception: RangeError (index): Invalid value: Valid value range is empty: 0
I/flutter (23513): upgrader: instantiated.
I/chatty  (23513): uid=10154(com.onecliquesystems.one_click_app) 1.ui identical 6 lines
2
I/flutter (23513): upgrader: instantiated.

pubspec.lock:
  upgrader:
    dependency: "direct main"
    description:
      name: upgrader
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.1.1"

the debug console goes in infinite loop.

**Comment by larryaasen** [comment]
@ziyadmansy Could you add `debugLogging: true` so it outputs the log, and attach the log here?

**Comment by larryaasen** [comment]
@ziyadmansy
Can you share the code you used for upgrader?
Also, you may want to upgrade to version 4.2.0 now.

**Comment by AlexPopaUpcode** [comment]
I believe he is talking about the following line of code which prints this message every time we build the application

`  print("upgrader: instantiated."); // TODO: remove this! `

This is line 176 from `upgrader.dart`

I also upgraded to 4.2.0, but this line is still there
