### ISSUE TITLE
launchUrl launches webview in default mode.

### ISSUE THREAD

**Issue by azharxes** [larryaasen/upgrader#173]
Can't update app because `launchUrl` in `_sendUserToAppStore()`  should open store app but it launches a webview.

**Comment by larryaasen** [comment]
@azharxes Can you include your upgrader log? It looks like this: https://github.com/larryaasen/upgrader#reporting-issues

**Comment by azharxes** [comment]
@larryaasen upgrader is working perfectly, it's the launchurl which is opening up a webview instead of store app. The new version of launchurl has the option to select mode.

**Comment by larryaasen** [comment]
@azharxes Should this issue be closed now?

**Comment by azharxes** [comment]
did you set non-broswer application mode in launchUrl ?

**Comment by hieugia3030** [comment]
I am also facing this issue

**Comment by larryaasen** [comment]
Does anyone have an upgrader log that shows this problem? If so, please attach it here.
https://github.com/larryaasen/upgrader#reporting-issues

**Comment by jaskiratAtNexG** [comment]
@larryaasen Attaching the upgrader log here.
I/flutter (25205): upgrader: instantiated.
I/flutter (25205): upgrader: build UpgradeAlert
I/flutter (25205): upgrader: languageCode: en
I/flutter (25205): upgrader: default operatingSystem: android RMX1921_11_F.06
I/flutter (25205): upgrader: operatingSystem: android
I/flutter (25205): upgrader: platform: TargetPlatform.android
I/flutter (25205): upgrader: isAndroid: true, isIOS: false, isLinux: false, isMacOS: false, isWindows: false, isFuchsia: false, isWeb: false
I/flutter (25205): upgrader: package info packageName: com.nispand.com
I/flutter (25205): upgrader: package info appName: Nispand
I/flutter (25205): upgrader: package info version: 1.0.0
I/flutter (25205): upgrader: appcast is available for this platform
I/flutter (25205): upgrader: appcast item count: 1
I/flutter (25205): upgrader: appcast best item version: 1.1.0
I/flutter (25205): upgrader: blocked: false
I/flutter (25205): upgrader: debugDisplayAlways: true
I/flutter (25205): upgrader: debugDisplayOnce: false
I/flutter (25205): upgrader: hasAlerted: false
I/flutter (25205): upgrader: shouldDisplayUpgrade: true
I/flutter (25205): upgrader: shouldDisplayReleaseNotes: true
I/flutter (25205): upgrader: showDialog title: Update App?
I/flutter (25205): upgrader: showDialog message: A new version of Nispand is available! Version 1.1.0 is now available-you have 1.0.0.
I/flutter (25205): upgrader: showDialog releaseNotes: Minor updates and improvements.
I/flutter (25205): upgrader: button tapped: update now
I/flutter (25205): upgrader: launching: https://play.google.com/store/apps/details?id=com.snapchat.android

**Comment by azharxes** [comment]
Fixed it in this.

https://github.com/larryaasen/upgrader/pull/185
