### ISSUE TITLE
Playstore updated layout

### ISSUE THREAD

**Issue by JHBitencourt** [larryaasen/upgrader#179]
The PlayStore has changed its layout page, or at least is in the process of changing it (releasing partially the new visual).
So I guess the [play_store_search_api.dart](https://github.com/larryaasen/upgrader/blob/master/lib/src/play_store_search_api.dart) will no longer work, since the classes searched on the page no longer exists.
This requires an update to the API.

Page from [waybackmachine](https://web.archive.org/web/20220514071800/https://play.google.com/store/apps/details?id=com.google.android.gm):

<details>
  <summary>Image</summary>
  <img src="https://user-images.githubusercontent.com/9002831/170135352-0d4abb87-169c-42b3-94da-d86b97c686fc.png" width="800" />
</details>

The new layout:

<details>
  <summary>Image</summary>
  <img src="https://user-images.githubusercontent.com/9002831/170135766-bb5e178c-85a1-40d5-850f-c3f22ac47e64.png" width="800" />
</details>

The app version is now inside the `About this app` dialog.

<details>
  <summary>Image</summary>
  <img src="https://user-images.githubusercontent.com/9002831/170136075-4ea27014-b1bc-4183-9231-9f92c4eac747.png" width="600" />
</details>

**Comment by humanolaranja** [comment]
I'm facing the same issue

**Comment by jvMori** [comment]
I also have this issue.

**Comment by abcdenis18** [comment]
This methos is no longer work, so u should try another way, create and setup a remote config using _firebase_remote_config_ package and put about your app new version, release note, etc as JSON param.

**Comment by bouncydragon** [comment]
will there be any fix here sooner? or should we migrate to _firebase_remote_config_ for the meantime?

**Comment by humanolaranja** [comment]
@larryaasen, are you guys looking for this?

**Comment by appstute-sachin** [comment]
Same issue for me too, can't find the playstore version. Can we expect this issue to be resolved in latest plugin version?

**Comment by larryaasen** [comment]
@JHBitencourt  Thanks for reporting this issue with so much detail. After looking at the update HTML for the Play Store page for an app, I don't yet see an easy way to parse the data. So far, I know that the version is inside a section that looks like this:
```
AF_initDataCallback(
    {key: 'ds:5', hash: '14', data: ... })
```
Deep inside that complex data structure is the release date, version, and other attributes specific to the app. The version is no longer contained inside HTML tags.
I will keep looking at this, but if anyone else has specific details on parsing this new page, please post it here.

**Comment by humanolaranja** [comment]
@larryaasen I found this crawler that works with the new google play layout, but it's not dart code: https://stackoverflow.com/a/39790287

I'm also trying to find a way to parse this new data structure, I already forked the repo and doing my best here to find a solution

**Comment by humanolaranja** [comment]
I changed the `version` function and it's working now, I followed this pattern to filter the app version

- Find the `appName` inside the response
- Get all `AF_initDataCallback` content
- Find the `AF_initDataCallback` that contains the version using the `appName`
- Get the version by using the correct `AF_initDataCallback` and some data structure patterns that I found

I can try to fix the `description` and `releaseNotes` later, any help are welcome

PR #183

**Comment by humanolaranja** [comment]
We need to update the `test_play_store_page1`, `test_play_store_page2` and `test_play_store_page3` snapshots to the new play store layout.
The tests in #183 will break until `description` and `releaseNotes` functions be fixed too.
I'm working with this items.

**Comment by humanolaranja** [comment]
I updated the `test_play_store_page1` but I have no ideia how to update `test_play_store_page2` and `test_play_store_page3` snapshots. Could you help me @larryaasen?

**Comment by humanolaranja** [comment]
Fixed this in #183, waiting for review and new release

**Comment by larryaasen** [comment]
I just published version [4.2.1-alpha.1](https://pub.dev/packages/upgrader/versions/4.2.1-alpha.1) on pub.dev with a fix for this thanks to @humanolaranja. Please test out this pre-release version ASAP and provide feedback. After it has been determined that this solution works well, I will release a normal version.

**Comment by humanolaranja** [comment]
I tested here and it worked very well in my application =D

**Comment by larryaasen** [comment]
@humanolaranja I've noticed that these exceptions are logged now for each access to the Play Store, even when it returns the version correctly. You can see them when you run this from the command line:
```
$ cd bin
$ dart playstore_lookup.dart id=com.moonwink.treasury
```
Output:
```
upgrader: PlayStoreResults.description exception, trying redesignedVersion: RangeError (index): Invalid value: Valid value range is empty: 0
upgrader: PlayStoreResults.description exception, trying redesignedVersion: RangeError (index): Invalid value: Valid value range is empty: 0
upgrader: PlayStoreResults.releaseNotes exception, trying redesignedVersion: RangeError (index): Invalid value: Valid value range is empty: 0
upgrader: PlayStoreResults.version exception, trying redesignedVersion: Bad state: No element
```
I am going to remove those exception messages to avoid confusion.

**Comment by humanolaranja** [comment]
@larryaasen sure, it makes sense, I changed the log message but I agree that it can be a little confusing. For me it's important just to keep the exception and throw both of them if we have an error in the redesigned version, so we can have a better stack trace in case of error. Another suggestion is to use the redesigned version before the old one, since the new layout is already released as default play store, so we can optimize the output response time.

**Comment by larryaasen** [comment]
I just published version [4.2.1-alpha.2](https://pub.dev/packages/upgrader/versions/4.2.1-alpha.2) to allow for more testing, and removed the noisy exception messages from the log. Please test this new version.

**Comment by larryaasen** [comment]
Version [4.2.1](https://pub.dev/packages/upgrader) has been released to this fix this issue.

**Comment by MuraliThangavel** [comment]
in future, if they updated [play_store_search_api.dart](https://github.com/larryaasen/upgrader/blob/master/lib/src/play_store_search_api.dart) , then we need to again update this upgrader sdk ?
