### ISSUE TITLE
Where is the full example for android and iOS?

### ISSUE THREAD

**Issue by NTMS2017** [larryaasen/upgrader#19]
Hi, 

Sorry for my English but how to I get my app version from android and iOS. I couldn't find any good example, alse I want to force to update. 

I use your example but I am not sure where to put my android app on google palay and iOS app on appstore.

you have:

**For Android:**
```
final appcast = Appcast();
final items = await appcast.parseAppcastItemsFromUri('https://raw.githubusercontent.com/larryaasen/upgrader/master/test/testappcast.xml');
final bestItem = appcast.bestItem();
```

**For iOS:**
```
final iTunes = ITunesSearchAPI();
final resultsFuture = iTunes.lookupByBundleId('com.google.Maps');
resultsFuture.then((results) {
    print('results: $results');
});
```

For iOS I think I will replace this **com.google.Maps** to my app but for android how to do it?
Also for Android you said 'On Android, setup the Appcast.' how can I set the app cast and where?

If you can created a step by step example it will be good for us

Thanks

**Comment by prashantspandey** [comment]
Any answers for this one?

**Comment by larryaasen** [comment]
The example folder has a main.dart file that contains an example of using both Android with Appcast, and iOS.

**Comment by larryaasen** [comment]
Here is the example:
```dart
  @override
  Widget build(BuildContext context) {
    Upgrader().clearSavedSettings();

    // On Android, setup the Appcast.
    // On iOS, the default behavior will be to use the App Store version of
    // the app, so update the Bundle Identifier in example/ios/Runner with a
    // valid identifier already in the App Store.
    final appcastURL = 'https://www.mydomain.com/myappcast.xml';
    final cfg = AppcastConfiguration(url: appcastURL, supportedOS: ['android']);

    return MaterialApp(
      title: 'Upgrader Example',
      home: Scaffold(
          appBar: AppBar(
            title: Text('Upgrader Example'),
          ),
          body: UpgradeAlert(
            appcastConfig: cfg,
            debugLogging: true,
            child: Center(child: Text('Checking...')),
          )),
    );
  }
```

**Comment by NiyatiKhandelwal-99** [comment]
I still did not understand that for Android, how can I setup the Appcast. (Reference to the comment in the above stated example- // On Android, setup the Appcast.)

**Comment by larryaasen** [comment]
Here is the README example for both Android and iOS: https://pub.dev/packages/upgrader#combined-android--ios-example

**Comment by larryaasen** [comment]
Did you setup the Appcast file as in the example: https://pub.dev/packages/upgrader#appcast-sample-file ?

**Comment by ug2454** [comment]
hi,
do i have to put this xml file in my project directory? and change the version manually everytime i build a new version of the app?

**Comment by larryaasen** [comment]
The Appcast file should be located on a publicly available remote server that can be accessed by the app. Then, you update the file manually on the remote server for each app update.
