### ISSUE TITLE
Appstore not loading after Update button pressed

### ISSUE THREAD

**Issue by developerflutter** [larryaasen/upgrader#190]
await launchUrl(Uri.parse(_appStoreListingURL!),
   mode: LaunchMode.externalNonBrowserApplication);

is not working. 

Logs:

flutter: FormatException: Unexpected character (at character 1)
You need an authentication code to access this API endpoint, as per https:/...

**Comment by larryaasen** [comment]
@developerflutter Hi. Thanks for the report. Can you include the entire upgrader log?

**Comment by larryaasen** [comment]
@developerflutter Is this still an issue?

**Comment by Perveev** [comment]
Also faced this problem

**Comment by larryaasen** [comment]
> Also faced this problem

@Perveev Can you include the entire upgrader log?

**Comment by Perveev** [comment]
> > Also faced this problem
> 
> @Perveev Can you include the entire upgrader log?

 upgrader: instantiated.
 upgrader: build UpgradeAlert
 upgrader: languageCode: uk
 upgrader: default operatingSystem: ios Version 15.5 (Build 19F70)
 upgrader: operatingSystem: ios
 upgrader: platform: TargetPlatform.iOS
 upgrader: isAndroid: false, isIOS: true, isLinux: false, isMacOS: false, isWindows: false, isFuchsia: false, isWeb: false
 upgrader: package info packageName: ua.com.baly4docs
 upgrader: package info appName: Baly4Docs
 upgrader: package info version: 1.2.11
 upgrader: countryCode: US
 upgrader: ITunesResults.minAppVersion: 1.2.12
 upgrader: blocked: true
 upgrader: debugDisplayAlways: false
 upgrader: debugDisplayOnce: false
 upgrader: hasAlerted: false
 upgrader: appStoreVersion: 1.2.12
 upgrader: installedVersion: 1.2.11
 upgrader: minAppVersion: 1.2.12
 upgrader: isUpdateAvailable: true
 upgrader: shouldDisplayUpgrade: true
 upgrader: shouldDisplayReleaseNotes: true

**Comment by larryaasen** [comment]
This should be fixed now. Are you using version 4.6.0 of this package?
