### ISSUE TITLE
What happens if we remove the mav tag from the description fields?

### ISSUE THREAD

**Issue by minoesteban** [larryaasen/upgrader#192]
As far as I understood, if this tag is not added to the description fields, an update is forced every time a new version is found in each store (Play / App)

So, when we add this tag in the description fields, this "always up to date" strategy gets overriden by whatever version is indicated in the tag

Question is, what happens if we remove that tag from the description fields? The upgrader goes back to "always latest version" strategy? Or gets stuck with the latest version it could fetch from the tag before it was removed?

Thank you

**Comment by larryaasen** [comment]
Removing the mav tag from the description field will still allow Upgrader to recommend upgrading when a newer version is found. Using the mav tag just prevents users from running older versions of the app without upgrading.

**Comment by minoesteban** [comment]
thank you @larryaasen ! Sorry for the delay in the reaction. Closing
