### ISSUE TITLE
Support to different release notes languages

### ISSUE THREAD

**Issue by humanolaranja** [larryaasen/upgrader#195]
Today we can provide the country code that makes ios release notes be translated if it have translation in the store of this country. But in Android we don't have this translation available, it's always the english one. I see that google play have the `&hl=:country` param to specify the country, so it's possible to use this param to get release notes translations. I see that the google play parser uses the keyword "What's new" to get the release notes, maybe we can find a way to change it and use the `hl` param for Android just like the `countryCode` for iOS

**Comment by humanolaranja** [comment]
If you agree with this @larryaasen you can assign this issue to me and I develop this feature and open a PR

**Comment by larryaasen** [comment]
@humanolaranja Feel free to open a PR for this and I will review it. Thanks.

**Comment by humanolaranja** [comment]
Just created the #217 PR to solve this

**Comment by humanolaranja** [comment]
@larryaasen

**Comment by humanolaranja** [comment]
@larryaasen ?

**Comment by humanolaranja** [comment]
Since the PR with this feature was merged, can we have a new release with this and close this issue @larryaasen ?

**Comment by humanolaranja** [comment]
I see that 4.8.0 was released, closing the issue

**Comment by humanolaranja** [comment]
I found a bug in this, maybe some merge problem
Opening #227 with the fix

**Comment by larryaasen** [comment]
Fixed in 4.8.1
