### ISSUE TITLE
Where to put the UpgradeAlert

### ISSUE THREAD

**Issue by jasonlaw** [larryaasen/upgrader#2]
Hi @larryaasen ,

In my app, before the MaterialApp, I have long initializing process, which including the user authentication as well.  During the initializing process, there will be a loading screen display. After the initialization, MaterialApp will be called and home is routed to a Login page. In the Login page, it checks if user has been successfully authenticated (during initialization) so it would re-route to the App main page.
So my question is, where should I apply the UpgradeAlert?

Thanks in advance.

**Comment by larryaasen** [comment]
The UpgradeAlert widget can be placed into any part of the widget tree just like any other widget. It will not begin the upgrade checks until after its first build. If you add the UpgradeAlert widget in the App main page after your Login page, it will not appear on your Login page, and will appear after user has been successfully authenticated.

You could also add it into your Login page if that is necessary to block the user from Login until they are using the correct version. Your decision of where to place the UpgradeAlert widget is based on when you want the user to see the prompt, and if you plan to block them out of the app.

You should be able to place the UpgradeAlert widget any place in the widget tree.

**Comment by jasonlaw** [comment]
Clear now, thank you!

**Comment by larryaasen** [comment]
I am closing this issue now that the explanation seems to be clear.

**Comment by tiagohbalves** [comment]
I have a problem with place of Upgrader, because I use login page and a AutoLogin function. This causes that when realizes the autologin and navigate to a other screen the Dialog is showed briefly but is dismissed after that. There is a soluction?  I'm using the 2.8.3 version.

**Comment by larryaasen** [comment]
@tiagohbalves  You could put Upgrade in both places. You could put it on the login screen, and if the autologin is being used, it could skip the login screen, and put it on the screen after autologin.
