### ISSUE TITLE
flutter: upgrader.ITunesResults.version: RangeError (index): Invalid value: Valid value range is empty: 0 .. this error show just when I run project on mac 

### ISSUE THREAD

**Issue by Fatima995** [larryaasen/upgrader#200]

**Comment by Fatima995** [comment]
flutter: upgrader.ITunesResults.version: RangeError (index): Invalid value: Valid value range is empty: 0
this error shows me when I run a project on a mac.

**Comment by JoDeveloper** [comment]
same issue here



```
flutter: upgrader.ITunesResults.version: RangeError (index): Invalid value: Valid value range is empty: 0
flutter: upgrader.ITunesResults.trackViewUrl: RangeError (index): Invalid value: Valid value range is empty: 0
flutter: upgrader.ITunesResults.releaseNotes: RangeError (index): Invalid value: Valid value range is empty: 0
flutter: upgrader.ITunesResults.description: RangeError (index): Invalid value: Valid value range is empty: 0
```

**Comment by larryaasen** [comment]
@JoDeveloper Thanks for the report. Can you include the entire upgrader log? See the README for instructions.

**Comment by JoDeveloper** [comment]
> @JoDeveloper Thanks for the report. Can you include the entire upgrader log? See the README for instructions.

Ok, it seems that the problem comes from [itunes](https://itunes.apple.com/lookup?), it always returns 

```json
{
 "resultCount":0,
 "results": []
}

```

**Comment by larryaasen** [comment]
Has the app been released on the App Store?

**Comment by JoDeveloper** [comment]
> Has the app been released on the App Store?

yeah [Athmany POS](https://apps.apple.com/sa/app/athmany-pos/id1583755282)

**Comment by larryaasen** [comment]
Can you include the entire upgrader log so that I can determine what's wrong?

**Comment by cheadevit** [comment]
I also got some errors when I run or IOS


```
022-08-18 11:11:50.134926+0700 Runner[22301:1439640] flutter: upgrader: package info appName: GMS Mobile Stage
2022-08-18 11:11:50.134979+0700 Runner[22301:1439640] flutter: upgrader: package info version: 1.21.14
2022-08-18 11:11:50.135093+0700 Runner[22301:1439640] flutter: upgrader: countryCode: kh
2022-08-18 11:11:50.171731+0700 Runner[22301:1439640] flutter: Failed to load a banner ad: Request Error: No ad to show.
2022-08-18 11:11:50.665304+0700 Runner[22301:1439640] flutter: upgrader.ITunesResults.version: RangeError (index): Invalid value: Valid value range is empty: 0
2022-08-18 11:11:50.665810+0700 Runner[22301:1439640] flutter: upgrader.ITunesResults.trackViewUrl: RangeError (index): Invalid value: Valid value range is empty: 0
2022-08-18 11:11:50.666227+0700 Runner[22301:1439640] flutter: upgrader.ITunesResults.releaseNotes: RangeError (index): Invalid value: Valid value range is empty: 0
2022-08-18 11:11:50.667133+0700 Runner[22301:1439640] flutter: upgrader.ITunesResults.description: RangeError (index): Invalid value: Valid value range is empty: 0
2022-08-18 11:11:50.670251+0700 Runner[22301:1439640] flutter: upgrader: blocked: false
2022-08-18 11:11:50.670447+0700 Runner[22301:1439640] flutter: upgrader: debugDisplayAlways: false
2022-08-18 11:11:50.670664+0700 Runner[22301:1439640] flutter: upgrader: debugDisplayOnce: false
2022-08-18 11:11:50.672028+0700 Runner[22301:1439640] flutter: upgrader: hasAlerted: false
2022-08-18 11:11:50.673716+0700 Runner[22301:1439640] flutter: upgrader: appStoreVersion: null
2022-08-18 11:11:50.674518+0700 Runner[22301:1439640] flutter: upgrader: installedVersion: 1.21.14
2022-08-18 11:11:50.675077+0700 Runner[22301:1439640] flutter: upgrader: minAppVersion: null
2022-08-18 11:11:50.675431+0700 Runner[22301:1439640] flutter: upgrader: isUpdateAvailable: false
2022-08-18 11:11:50.675679+0700 Runner[22301:1439640] flutter: upgrader: shouldDisplayUpgrade: false
2022-08-18 11:11:50.676545+0700 Runner[22301:1439640] flutter: upgrader: shouldDisplayReleaseNotes: false
2022-08-18 11:11:50.694820+0700 Runner[22301:1439640] flutter: upgrader.ITunesResults.version: RangeError (index): Invalid value: Valid value range is empty: 0
2022-08-18 11:11:50.695006+0700 Runner[22301:1439640] flutter: upgrader.ITunesResults.trackViewUrl: RangeError (index): Invalid value: Valid value range is empty: 0
2022-08-18 11:11:50.695642+0700 Runner[22301:1439640] flutter: upgrader.ITunesResults.releaseNotes: RangeError (index): Invalid value: Valid value range is empty: 0
2022-08-18 11:11:50.695755+0700 Runner[22301:1439640] flutter: upgrader.ITunesResults.description: RangeError (index): Invalid value: Valid value range is empty: 0
```

**Comment by larryaasen** [comment]
@cheadevit I don't think com.gms.gmsmobilekh has been released on the App Store. Do you have a link to the app on the App Store? It would look something like this: https://apps.apple.com/us/app/us-debt-now-national-debt/id903781928

**Comment by larryaasen** [comment]
@JoDeveloper I found the app using country code SA instead of US. It must not have been released on the US App Store. Try using the Upgrader parameter: `countryCode`.

**Comment by JoDeveloper** [comment]
> @JoDeveloper I found the app using country code SA instead of US. It must not have been released on the US App Store. Try using the Upgrader parameter: `countryCode`.

Ok I'll try it

**Comment by ebadebo** [comment]
Same here 
bundleid: mn.clubi.eway

`flutter: upgrader.ITunesResults.version: RangeError (index): Invalid value: Valid value range is empty: 0
flutter: upgrader.ITunesResults.trackViewUrl: RangeError (index): Invalid value: Valid value range is empty: 0
flutter: upgrader.ITunesResults.releaseNotes: RangeError (index): Invalid value: Valid value range is empty: 0
flutter: upgrader.ITunesResults.description: RangeError (index): Invalid value: Valid value range is empty: 0
flutter: upgrader: blocked: false
flutter: upgrader: debugDisplayAlways: false
flutter: upgrader: debugDisplayOnce: false
flutter: upgrader: hasAlerted: false
flutter: upgrader: appStoreVersion: null
flutter: upgrader: installedVersion: 1.22.1200
flutter: upgrader: minAppVersion: null
flutter: upgrader: isUpdateAvailable: false
flutter: upgrader: shouldDisplayUpgrade: false
flutter: upgrader: shouldDisplayReleaseNotes: false`


iTunes.lookupByBundleId result:
`{resultCount: 1, results: [{artworkUrl512: https://is1-ssl.mzstatic.com/image/thumb/Purple112/v4/8a/51/e2/8a51e2b3-8f57-d4fd-5b64-1f2deaa96693/AppIcon-0-0-1x_U007emarketing-0-0-0-10-0-0-sRGB-0-0-0-GLES2_U002c0-512MB-85-220-0-0.png/512x512bb.jpg, artworkUrl100: https://is1-ssl.mzstatic.com/image/thumb/Purple112/v4/8a/51/e2/8a51e2b3-8f57-d4fd-5b64-1f2deaa96693/AppIcon-0-0-1x_U007emarketing-0-0-0-10-0-0-sRGB-0-0-0-GLES2_U002c0-512MB-85-220-0-0.png/100x100bb.jpg, ipadScreenshotUrls: [https://is5-ssl.mzstatic.com/image/thumb/PurpleSource112/v4/a8/4b/1e/a84b1e3e-fa84-548a-aee5-2d687de86a26/610751eb-f2bd-49ee-adb0-94509626bb14_ipad-1.png/576x768bb.png, https://is4-ssl.mzstatic.com/image/thumb/PurpleSource112/v4/ef/ca/89/efca89ac-648a-7ee3-81bc-dfa506afd957/3184b93f-69c6-4515-9478-132aae20ef5b_ipad-2.png/576x768bb.png, https://is1-ssl.mzstatic.com/image/thumb/PurpleSource122/v4/0a/0b/fb/0a0bfbff-7bb4-bcfa-6805-022ac888f7f7/51eda6d7-162d-465f-bb0c-fa76e257dc3a_ipad-3.png/576x768bb.png], artworkUrl60: https://is1-ssl.mzstatic.com/image/thumb/Purple112/v4/8a/51/e2/8a51e2b3-8f57-d4fd-5b64-1f2deaa96693/AppIcon-0-0-1x_U007emarketing-0-0-0-10-0-0-sRGB-0-0-0-GLES2_U002c0-512MB-85-220-0-0.png/60x60bb.jpg, screenshotUrls: [https://is5-ssl.mzstatic.com/image/thumb/PurpleSource122/v4/03/3b/a1/033ba126-781a-fb1b-17c2-e5d324a75cc6/ed6de6c4-dd69-45ec-b23b-5d434f5e5ec8_ios8max-1.png/392x696bb.png, https://is3-ssl.mzstatic.com/image/thumb/PurpleSource122/v4/3e/8a/01/3e8a0102-ab57-94a1-4935-75d62063d3df/04b2d934-2132-4004-a4e8-3bf704420d8c_ios8max-2.png/392x696bb.png, https://is5-ssl.mzstatic.com/image/thumb/PurpleSource112/v4/46/77/8c/46778c63-baac-3bdc-a8e9-46d615d51b62/06265cf3-d685-42a9-965e-7246793d8e9e_ios8max-3.png/392x696bb.png, https://is3-ssl.mzstatic.com/image/thumb/PurpleSource112/v4/e1/61/fe/e161feca-c9b6-1065-4f2e-e236746b29c7/39c2e243-194d-4188-95eb-0721f4090441_ios8max-4.png/392x696bb.png], artistViewUrl: https://apps.apple.com/us/developer/efficient-way/id1630740468?uo=4, isGameCenterEnabled: false, supportedDevices: [iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax, iPhoneSESecondGen-iPhoneSESecondGen, iPadProSecondGen-iPadProSecondGen, iPadProSecondGenCellular-iPadProSecondGenCellular, iPadProFourthGen-iPadProFourthGen, iPadProFourthGenCellular-iPadProFourthGenCellular, iPhone12Mini-iPhone12Mini, iPhone12-iPhone12, iPhone12Pro-iPhone12Pro, iPhone12ProMax-iPhone12ProMax, iPadAir4-iPadAir4, iPadAir4Cellular-iPadAir4Cellular, iPadEighthGen-iPadEighthGen, iPadEighthGenCellular-iPadEighthGenCellular, iPadProThirdGen-iPadProThirdGen, iPadProThirdGenCellular-iPadProThirdGenCellular, iPadProFifthGen-iPadProFifthGen, iPadProFifthGenCellular-iPadProFifthGenCellular, iPhone13Pro-iPhone13Pro, iPhone13ProMax-iPhone13ProMax, iPhone13Mini-iPhone13Mini, iPhone13-iPhone13, iPadMiniSixthGen-iPadMiniSixthGen, iPadMiniSixthGenCellular-iPadMiniSixthGenCellular, iPadNinthGen-iPadNinthGen, iPadNinthGenCellular-iPadNinthGenCellular, iPhoneSEThirdGen-iPhoneSEThirdGen, iPadAirFifthGen-iPadAirFifthGen, iPadAirFifthGenCellular-iPadAirFifthGenCellular, iPhone14-iPhone14, iPhone14Plus-iPhone14Plus, iPhone14Pro-iPhone14Pro, iPhone14ProMax-iPhone14ProMax, iPadTenthGen-iPadTenthGen, iPadTenthGenCellular-iPadTenthGenCellular, iPadPro11FourthGen-iPadPro11FourthGen, iPadPro11FourthGenCellular-iPadPro11FourthGenCellular, iPadProSixthGen-iPadProSixthGen, iPadProSixthGenCellular-iPadProSixthGenCellular], appletvScreenshotUrls: [], features: [iosUniversal], advisories: [], kind: software, currentVersionReleaseDate: 2022-12-03T14:59:19Z, releaseNotes: сайжруулалт, releaseDate: 2022-07-28T07:00:00Z, description: CLEW is eway service app
-Service brief introduction
-Enroll our services
-Service history
-Schedule, fileSizeBytes: 43567104, formattedPrice: Free, contentAdvisoryRating: 4+, trackId: 1630740466, trackName: CLEW MN, primaryGenreName: Business, primaryGenreId: 6000, bundleId: mn.clubi.eway, userRatingCountForCurrentVersion: 0, averageUserRating: 0, trackViewUrl: https://apps.apple.com/us/app/clew-mn/id1630740466?uo=4, trackContentRating: 4+, minimumOsVersion: 10.0, averageUserRatingForCurrentVersion: 0, currency: USD, trackCensoredName: CLEW MN, languageCodesISO2A: [EN], isVppDeviceBasedLicensingEnabled: true, genreIds: [6000], sellerName: Efficient Way LLC, artistId: 1630740468, artistName: Efficient Way, genres: [Business], price: 0.0, version: 1.22.1201, wrapperType: software, userRatingCount: 0}]}`

**Comment by larryaasen** [comment]
Is anyone still seeing this issue? If so, please provide more recent details.

**Comment by larryaasen** [comment]
Closed for lack of information.
