### ISSUE TITLE
PlayStoreResults.redesignedVersion exception: FormatException: Not a properly formatted version string. And also, will it work for updates with VersionCode Changes or do have to update Version Name as well ?

### ISSUE THREAD

**Issue by Kishan-Somaiya** [larryaasen/upgrader#201]
To better assist in analyzing issues, please include all of the upgrader log, which should look something like this:
```
upgrader: build UpgradeAlert
I/flutter (27502): upgrader: languageCode: en
I/flutter (27502): upgrader: default operatingSystem: android QKQ1.190828.002 test-keys
I/flutter (27502): upgrader: operatingSystem: android
I/flutter (27502): upgrader: platform: TargetPlatform.android
I/flutter (27502): upgrader: isAndroid: true, isIOS: false, isLinux: false, isMacOS: false, isWindows: false, isFuchsia: false, isWeb: false
I/flutter (27502): upgrader: instantiated.
I/flutter (27502): upgrader: build UpgradeAlert
I/flutter (27502): upgrader: languageCode: en
I/flutter (27502): upgrader: default operatingSystem: android QKQ1.190828.002 test-keys
I/flutter (27502): upgrader: operatingSystem: android
I/flutter (27502): upgrader: platform: TargetPlatform.android
I/flutter (27502): upgrader: isAndroid: true, isIOS: false, isLinux: false, isMacOS: false, isWindows: false, isFuchsia: false, isWeb: false
I/flutter (27502): upgrader: package info packageName: com.searchmi.da
I/flutter (27502): upgrader: package info appName: SearchMI
I/flutter (27502): upgrader: package info version: 1.0.0
I/flutter (27502): upgrader: countryCode: IN
I/flutter (27502): upgrader: package info packageName: com.searchmi.da
I/flutter (27502): upgrader: package info appName: SearchMI
I/flutter (27502): upgrader: package info version: 1.0.0
I/flutter (27502): upgrader: countryCode: IN
I/flutter (27502): upgrader: instantiated.
I/flutter (27502): upgrader: build UpgradeAlert
I/flutter (27502): upgrader: languageCode: en
I/flutter (27502): upgrader: default operatingSystem: android QKQ1.190828.002 test-keys
I/flutter (27502): upgrader: operatingSystem: android
I/flutter (27502): upgrader: platform: TargetPlatform.android
I/flutter (27502): upgrader: isAndroid: true, isIOS: false, isLinux: false, isMacOS: false, isWindows: false, isFuchsia: false, isWeb: false
I/flutter (27502): upgrader: package info packageName: com.searchmi.da
I/flutter (27502): upgrader: package info appName: SearchMI
I/flutter (27502): upgrader: package info version: 1.0.0
I/flutter (27502): upgrader: countryCode: IN
I/flutter (27502): upgrader: instantiated.
I/flutter (27502): upgrader: build UpgradeAlert
I/flutter (27502): upgrader: languageCode: en
I/flutter (27502): upgrader: default operatingSystem: android QKQ1.190828.002 test-keys
I/flutter (27502): upgrader: operatingSystem: android
I/flutter (27502): upgrader: platform: TargetPlatform.android
I/flutter (27502): upgrader: isAndroid: true, isIOS: false, isLinux: false, isMacOS: false, isWindows: false, isFuchsia: false, isWeb: false
I/flutter (27502): upgrader: package info packageName: com.searchmi.da
I/flutter (27502): upgrader: package info appName: SearchMI
I/flutter (27502): upgrader: package info version: 1.0.0
I/flutter (27502): upgrader: countryCode: IN
I/flutter (27502): upgrader: PlayStoreResults.redesignedVersion exception: FormatException: Not a properly formatted version string
I/flutter (27502): upgrader: PlayStoreResults.redesignedVersion exception: FormatException: Not a properly formatted version string
I/flutter (27502): upgrader: PlayStoreResults.redesignedVersion exception: FormatException: Not a properly formatted version string
I/flutter (27502): upgrader: blocked: false
I/flutter (27502): upgrader: debugDisplayAlways: true
I/flutter (27502): upgrader: debugDisplayOnce: false
I/flutter (27502): upgrader: hasAlerted: false
I/flutter (27502): upgrader: shouldDisplayUpgrade: true
I/flutter (27502): upgrader: shouldDisplayReleaseNotes: true
I/flutter (27502): upgrader: showDialog title: Update App?
I/flutter (27502): upgrader: showDialog message: A new version of SearchMI is available! Version  is now available-you have 1.0.0.
I/flutter (27502): upgrader: showDialog releaseNotes: Get the best business out of your area !
I/flutter (27502): upgrader: PlayStoreResults.redesignedVersion exception: FormatException: Not a properly formatted version string
```
Also, please include the upgrader version number from the pubspec.lock file, which should look something like this:
```
   upgrader:
    dependency: "direct main"
    description:
      name: upgrader
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.4.2"
```
--> Also Latest Version From Play Store is Missing. My App is in Internal Testing but it is Available on Play Store

![image](https://user-images.githubusercontent.com/62096591/181445462-9e9ea8ef-038d-4857-88cb-79a22ab0585f.png)

**Comment by larryaasen** [comment]
I see that Upgrader is instantiated more than once which is not a good idea. Can you post the code here where you use Upgrader()?
Also, I see that the Play Store results were not found. I ran this in a terminal window:
```
$ dart bin/playstore_lookup.dart id=com.searchmi.da
upgrader: Can't find an app in the Play Store with the id: com.searchmi.da
```
Is you app published on the Play Store?

**Comment by Kishan-Somaiya** [comment]
Yes it's available on Play Store but it's only available in my Country for now. @larryaasen Is that an issue ?

![image](https://user-images.githubusercontent.com/62096591/181502912-49e1180e-163a-420b-bf42-32861b74870f.png)

**Comment by larryaasen** [comment]
@Kishan-Somaiya  It looks like we don't support other countries with the Android Play Store. We do support all countries on iOS.

Can you share a link to your app in the Play Store?

**Comment by Kishan-Somaiya** [comment]
Thanks for your reply @larryaasen. Does that mean this package won't work for me ? Here's the [link](https://play.google.com/store/apps/details?id=com.searchmi.da)

**Comment by larryaasen** [comment]
@Kishan-Somaiya What is the country code?

**Comment by larryaasen** [comment]
I think I found it: https://play.google.com/store/apps/details?id=com.searchmi.da&gl=IN

**Comment by Kishan-Somaiya** [comment]
Hey @larryaasen can you confirm if Upgrader will work or Do I have to look for another alternatives ?

And to test it in release env, I've to upload it to Play store right ?

**Comment by larryaasen** [comment]
I am looking at this issue now, but I don't have a fix yet.

**Comment by Kishan-Somaiya** [comment]
Okay, waiting for a fix and thanks for all your support @larryaasen, appreciated.

**Comment by Kishan-Somaiya** [comment]
Hey @larryaasen did you find a solution ? I was thinking if we can use the supplied Country code ? Like in this example https://play.google.com/store/apps/details?id=com.searchmi.da&gl=IN, we pass IN and then it use that in URL, default being US. Will this work ?

**Comment by larryaasen** [comment]
I have a solution and I am testing now and for the next few days.

**Comment by Kishan-Somaiya** [comment]
Thanks for the update @larryaasen, looking forward to it and much appreciated.

**Comment by larryaasen** [comment]
Released version 4.6.0 of [upgrader] package. Updated Play Store API request to include the country code. @Kishan-Somaiya  Please check it out.

**Comment by Kishan-Somaiya** [comment]
Thanks @larryaasen will test this and let you know in few days, much appreciated.

**Comment by Kishan-Somaiya** [comment]
Hi @larryaasen I'm still getting the exception in the logs : upgrader: PlayStoreResults.redesignedVersion exception: FormatException: Not a properly formatted version string, will this work in the Play store version of the app ?

**Comment by Kishan-Somaiya** [comment]
`I/flutter ( 4544): upgrader: instantiated.
I/flutter ( 4544): upgrader: build UpgradeAlert
I/flutter ( 4544): upgrader: languageCode: en
I/flutter ( 4544): upgrader: default operatingSystem: android QKQ1.190828.002 test-keys
I/flutter ( 4544): upgrader: operatingSystem: android
I/flutter ( 4544): upgrader: platform: TargetPlatform.android
I/flutter ( 4544): upgrader: isAndroid: true, isIOS: false, isLinux: false, isMacOS: false, isWindows: false, isFuchsia: false, isWeb: false
I/flutter ( 4544): upgrader: package info packageName: com.searchmi.da
I/flutter ( 4544): upgrader: package info appName: SearchMI
I/flutter ( 4544): upgrader: package info version: 1.0.0
I/flutter ( 4544): upgrader: countryCode: IN
I/flutter ( 4544): upgrader: instantiated.
I/flutter ( 4544): Returning Intro Screen
I/flutter ( 4544): upgrader: build UpgradeAlert
I/flutter ( 4544): upgrader: languageCode: en
I/flutter ( 4544): upgrader: default operatingSystem: android QKQ1.190828.002 test-keys
I/flutter ( 4544): upgrader: operatingSystem: android
I/flutter ( 4544): upgrader: platform: TargetPlatform.android
I/flutter ( 4544): upgrader: isAndroid: true, isIOS: false, isLinux: false, isMacOS: false, isWindows: false, isFuchsia: false, isWeb: false
I/flutter ( 4544): upgrader: package info packageName: com.searchmi.da
I/flutter ( 4544): upgrader: package info appName: SearchMI
I/flutter ( 4544): upgrader: package info version: 1.0.0
I/flutter ( 4544): upgrader: countryCode: IN
I/flutter ( 4544): upgrader: instantiated.
I/flutter ( 4544): upgrader: build UpgradeAlert
I/flutter ( 4544): upgrader: languageCode: en
I/flutter ( 4544): upgrader: default operatingSystem: android QKQ1.190828.002 test-keys
I/flutter ( 4544): upgrader: operatingSystem: android
I/flutter ( 4544): upgrader: platform: TargetPlatform.android
I/flutter ( 4544): upgrader: isAndroid: true, isIOS: false, isLinux: false, isMacOS: false, isWindows: false, isFuchsia: false, isWeb: false
I/flutter ( 4544): upgrader: package info packageName: com.searchmi.da
I/flutter ( 4544): upgrader: package info appName: SearchMI
I/flutter ( 4544): upgrader: package info version: 1.0.0
I/flutter ( 4544): upgrader: countryCode: IN
I/flutter ( 4544): upgrader: PlayStoreResults.redesignedVersion exception: FormatException: Not a properly formatted version string
I/flutter ( 4544): upgrader: PlayStoreResults.redesignedVersion exception: FormatException: Not a properly formatted version string
I/flutter ( 4544): upgrader: PlayStoreResults.redesignedVersion exception: FormatException: Not a properly formatted version string
I/flutter ( 4544): upgrader: blocked: false
I/flutter ( 4544): upgrader: debugDisplayAlways: true
I/flutter ( 4544): upgrader: debugDisplayOnce: false
I/flutter ( 4544): upgrader: hasAlerted: false
I/flutter ( 4544): upgrader: shouldDisplayUpgrade: true
I/flutter ( 4544): upgrader: shouldDisplayReleaseNotes: true
I/flutter ( 4544): upgrader: showDialog title: Update App?
I/flutter ( 4544): upgrader: showDialog message: A new version of SearchMI is available! Version  is now available-you have 1.0.0.
I/flutter ( 4544): upgrader: showDialog releaseNotes: Get the best business out of your area !
`

**Comment by Kishan-Somaiya** [comment]
Hi @larryaasen when I use the command terminal app and passing country="IN" I get the following results :

upgrader: PlayStoreResults.redesignedVersion exception: FormatException: Not a properly formatted version string
playstore_lookup description: Searchmi is a India's trusted digital marketing platform that links business vendors and target people.Searchmi is India's first of this kind of digital platform where all kinds of
business have the opportunity to grow and increase customer reachSearchmi has experienced and expert team that is dedicated to help in effective marketing of small, medium and bigger businessOur mission and visi
onOur mission is to provide cheapest, smarter and effective way of marketing to every businessmenOur vision is to create a unique path of marketing through the digital platform and remove all limitations
playstore_lookup minAppVersion: null
playstore_lookup releaseNotes: Get the best business out of your area !
playstore_lookup version: null
playstore_lookup all results:
#document

Here's the app info that's available on Play Store : 

![image](https://user-images.githubusercontent.com/62096591/185055390-5e4ca7d7-37c8-4056-bb19-dbe5790a1e3e.png)

**Comment by larryaasen** [comment]
Looking at the Play Store for this app, https://play.google.com/store/apps/details?id=com.searchmi.da&gl=IN, and looking at the _About this app_ section, there is no app version listed. Looking at the screenshot below, there is no Version listed, so `upgrader` cannot determine the Play Store version of the app.
<img width="706" alt="Screen Shot 2022-08-17 at 9 51 11 AM" src="https://user-images.githubusercontent.com/325973/185151462-66cb8a8d-7576-4c26-bfc5-70bcbcc417e7.png">

**Comment by Kishan-Somaiya** [comment]
Hi @larryaasen thanks for your reply, actually you can see in my above comment, version is showing in play store app, but it's not showing in web. Do you know why it's not showing in web or do you know any to fix it ?

**Comment by larryaasen** [comment]
I don't know why that happens. Do you have more than one version of the app active or available at the same time?

**Comment by larryaasen** [comment]
I don't know if that would cause the issue. Can regular users download the app from the Play Store?

**Comment by Kishan-Somaiya** [comment]
Yes they can now

**Comment by Kishan-Somaiya** [comment]
Our app is still in early access as you can see in below image :

![image](https://user-images.githubusercontent.com/62096591/185296341-c94c60c3-a0ad-4b6a-8381-340ff906d0b5.png)

Could this be an issue ? Users can search and download it. I've checked my other app which is also in early access in play store, version is also not available there. Looking on the other apps which are not in early access, we get the version in all of them. Do you have nay solution for this ? thoughts ?

**Comment by larryaasen** [comment]
Unfortunately, the only way for the `upgrader` package to determine the latest published release of the app, is to use this URL: https://play.google.com/store/apps/details?id=com.searchmi.da&gl=IN
The version must be on that page for this to work.
