### ISSUE TITLE
Please upgrade device_info_plus to latest

### ISSUE THREAD

**Issue by boskokg** [larryaasen/upgrader#207]
please upgrade device_info_plus to latest.

Thanks in advance

**Comment by larryaasen** [comment]
Updated the device_info_plus dependency to include version 4.1.0 and up to <4.2.0 with this commit: 6ccb2384e3cc3da5c4b2d8ad58317815f7674c37. New release coming soon.

**Comment by larryaasen** [comment]
Version 4.6.0 with this change has been released.
https://pub.dev/packages/upgrader/changelog#460
