### ISSUE TITLE
Not supported in Flutter SDK version 1.13.6, help

### ISSUE THREAD

**Issue by topex-psy** [larryaasen/upgrader#21]
I use the latest version from pub.dev: `upgrader: ^0.10.1`
Then I got this
How to solve it? Thank you

```
Running "flutter pub get" in BuangDuit...                       
The current Flutter SDK version is 1.13.6.

Because buangduit depends on upgrader >=0.10.1 which requires Flutter SDK version >=1.12.0 <1.13.0, version solving failed.
pub get failed (1; Because buangduit depends on upgrader >=0.10.1 which requires Flutter SDK version >=1.12.0 <1.13.0, version solving failed.)
exit code 1
```

**Comment by larryaasen** [comment]
Since Flutter SDK version 1.13.6 is not a stable version, the latest version of this package does not officially support it. However, if you use version 0.10.0 of this package, it should work with 1.13.6 with the same features.
