### ISSUE TITLE
Return 'update available' object to show my own widget

### ISSUE THREAD

**Issue by adminant** [larryaasen/upgrader#210]
I want to analyze whether update is available and show my own widget or dialog. Is it possible somehow or there is only pre-defined dialog?

**Comment by larryaasen** [comment]
@adminant  This  might work:
```
final upgrader = Upgrader();
await upgrader.initialize();
final shouldDisplayUpgrade = upgrader.shouldDisplayUpgrade();
```
and maybe use these too:
```
final available = upgrader.isUpdateAvailable();
final tooSoon = upgrader.isTooSoon();
```

**Comment by adminant** [comment]
Thank you! And what should I call when update is available and user agrees to update and taps on update button in my dialog?
