### ISSUE TITLE
A question 

### ISSUE THREAD

**Issue by Oladips** [larryaasen/upgrader#214]
Hi please I'd like your insight on an issue I'm having. I'm using the upgrader package v4.6 and I implemented it on my app. I've uploaded an update on the store but I still get a pop up even on the current version
![IMG_20220907_063024.jpg](https://user-images.githubusercontent.com/45954324/188796458-d813ca31-2988-4957-b446-1b6c6c7468dd.jpg)

Please I need your input on this. Thanks

**Comment by larryaasen** [comment]
Can you attach your upgrader log?

**Comment by Oladips** [comment]
Where can i find that please

**Comment by Oladips** [comment]
flutter: upgrader: languageCode: en
flutter: upgrader: build UpgradeAlert
flutter: upgrader: default operatingSystem: ios 13.0
flutter: upgrader: operatingSystem: ios
flutter: upgrader: platform: TargetPlatform.iOS
flutter: upgrader: package info packageName: ng.apexnetwork.apexNetwork
flutter: upgrader: package info appName: Apex Network
flutter: upgrader: countryCode: NG
flutter: upgrader: blocked: false
flutter: upgrader: debugDisplayAlways: false
flutter: upgrader: debugDisplayOnce: false
flutter: upgrader: hasAlerted: false
flutter: upgrader: appStoreVersion: 1.3.0
flutter: upgrader: installedVersion: 1.3.0
flutter: upgrader: minAppVersion: 1.2.0
flutter: upgrader: isUpdateAvailable: true
flutter: upgrader: shouldDisplayUpgrade: true
flutter: upgrader: shouldDisplayReleaseNotes: true
flutter: upgrader: showDialog title: Update App?
flutter: upgrader: showDialog message: A new version of Apex Network is available! Version 1.3.0 is now available-you have 1.3.0.
flutter: upgrader: showDialog releaseNotes: 
-Bug fixes and Improvement
-You can now verify your email and phone from the app
-Placing gift card trades
-Customer Identity verification check is now available in-app as well
-Airtime recharge available,

**Comment by Oladips** [comment]
![Screen Shot 2022-09-13 at 11 21 18 AM](https://user-images.githubusercontent.com/45954324/189877327-a2854bd2-ea0e-4fe1-b20a-cd5e52ba9d93.png)

**Comment by Oladips** [comment]
This is also a log carried out on the willdisplayUpgrade function, just to print the parameters.

**Comment by larryaasen** [comment]
@Oladips I've looked over this bug report and I cannot explain this behavior. Since the two versions are the same, it should not have showed `isUpdateAvailable: true`. Are you using a fork on the upgrader package, or are you using this package directly from pub.dev?
