### ISSUE TITLE
Is Appcast mandatory

### ISSUE THREAD

**Issue by ameya730** [larryaasen/upgrader#216]
Hi @larryaasen,

I am a bit confused about appcast.

Is it necessary to setup app cast mechanism in order to get the pop-up to upgrade the app ?

or

can I just wrap the body widget with upgrader alert and it will automatically fetch details from playstore and show the pop-up in case a new version is available ?

Regards,
Ameya

**Comment by larryaasen** [comment]
@ameya730  It is not necessary to use AppCast. By default, it works for Android app using the Google Play Store, and iOS apps using the App Store. You could use AppCast but it is not required.
