### ISSUE TITLE
App Rejected by Google Play Store when using MAV

### ISSUE THREAD

**Issue by ryanaidilp** [larryaasen/upgrader#218]
Looks like new Google Play Policy wont allow developer to add minimum app version into description fields.
<img width="787" alt="image" src="https://user-images.githubusercontent.com/43450710/190301528-3b7a618e-c589-479f-8279-3677d4fa5921.png">

**Comment by larryaasen** [comment]
Duplicate: https://github.com/larryaasen/upgrader/issues/188
I just released a Prerelease: [4.7.0-alpha.1](https://pub.dev/packages/upgrader/versions/4.7.0-alpha.1), with a change to resolve this. Please test this out and let me know if this works for an Android Play Store submission.

**Comment by ryanaidilp** [comment]
@larryaasen Okay I'll try it out, thanks
