### ISSUE TITLE
Update app dialog still showing after update the latest version from both Store.

### ISSUE THREAD

**Issue by panchalAlpit** [larryaasen/upgrader#220]
Hello All,
I'm still getting the update App dialog after update the App from Play store and App store. Please help me why I'm getting the update app option when it's already updated app.

Here is my code:

      ` UpgradeAlert(
           upgrader: Upgrader(
            showIgnore: false,
            showLater: false,
            showReleaseNotes: true,
            debugDisplayAlways: true,
            dialogStyle: Platform.isIOS?UpgradeDialogStyle.cupertino:UpgradeDialogStyle.material,
          ),
           child:Container())
          `

Android Screen shot
![android](https://user-images.githubusercontent.com/48007084/192938507-1a7667f4-e2d5-44e5-8a46-993db3f0da70.jpeg)

Play Store version screenshot:- https://prnt.sc/gCAKLw4LwE-K

IOS screen shot:- 

![ios](https://user-images.githubusercontent.com/48007084/192938808-fc594b44-0a94-46f4-8131-063361d14b05.jpeg)

Apple Developer console screenshot:-  https://prnt.sc/wWpQSGGEuI49

Please help me.

**Comment by nylonW** [comment]
I think you should remove this line 
`debugDisplayAlways: true,`

**Comment by panchalAlpit** [comment]
@nylonW Thank you for the response but if I remove the `debugDisplayAlways: true` this line so update dialog show only one time means if user destroy the app and reopen the app so update dialog is not showing and I want to force fully update the app functionality.

**Comment by larryaasen** [comment]
@panchalAlpit Did that solve your problem?

**Comment by panchalAlpit** [comment]
> @panchalAlpit Did that solve your problem?

No @larryaasen still getting same problem.

**Comment by larryaasen** [comment]
@panchalAlpit Please include the upgrader debug log so we can further assess this issue. https://github.com/larryaasen/upgrader#reporting-issues

**Comment by larryaasen** [comment]
Closed for lack of information.
