### ISSUE TITLE
Update Dependencies Package

### ISSUE THREAD

**Issue by SandeepMalviya1999** [larryaasen/upgrader#226]
Currently, max version for few packages are old.

 device_info_plus: ">=3.2.0 <4.2.0"
package_info_plus: ^1.3.0

As, on time of reporting,
device_info_plus = [6.0.0](https://pub.dev/packages/device_info_plus/versions/6.0.0)
package_info_plus=[2.0.0](https://pub.dev/packages/package_info_plus/versions/2.0.0)

Please update the version of dependency package

**Comment by benjamincombes** [comment]
Just for information, device_info_plus is now at version `7.0.0`

**Comment by larryaasen** [comment]
device_info_plus 6.0.0 and package_info_plus 2.0.0 are now supported in version 4.10.0. Also, http 0.13.5 is now supported.

**Comment by nblum37** [comment]
Hi,
would it be possible to also update the dependency for the url_launcher to 6.1.6? However, as you exactly allowed the version to be <=6.1.5 I assume, you faced some issues. Thank you :)

**Comment by larryaasen** [comment]
@nblum37 The upgrader package supports Flutter 2.5+ and url_launcher supports Flutter 2.10+, which will not work with upgrader.

**Comment by nblum37** [comment]
Thanks for the explanation!

**Comment by SandeepMalviya1999** [comment]
Thanks team for solving the issue and helping out.
