### ISSUE TITLE
 upgraded 4.9.0 Pubspec lib compiling issue with device_info_plus, package_info_plus, share_plus and shared_preferences

### ISSUE THREAD

**Issue by parmarravi** [larryaasen/upgrader#229]
Once I update upgraded to 4.9.0 from  upgrader: ^4.4.0 it throws this error.
I am using  shared_preferences: ^2.0.15 version  issue

Because upgrader >=4.9.0 depends on shared_preferences >=2.0.3 <=2.0.7 and example app  depends on shared_preferences ^2.0.15, upgrader >=4.9.0 is forbidden.
So, because example app depends on upgrader ^4.9.0, version solving failed.

Apart from this latest upgraded 4.9.0 does not complies with 
below lib
 device_info_plus: ^7.0.1
 share_plus: ^6.0.1
 package_info_plus: ^3.0.1

Because upgrader >=3.7.0 depends on package_info_plus ^1.3.0 and example app  depends on package_info_plus ^3.0.1, upgrader >=3.7.0 is forbidden.
So, because example app  depends on upgrader ^4.9.0, version solving failed.
pub get failed (1; So, because example app  depends on upgrader ^4.9.0, version solving failed.)

**Comment by larryaasen** [comment]
Version 4.10.0 of upgrader now supports shared_preferences ">=2.0.3 <2.1.0".

**Comment by larryaasen** [comment]
@parmarravi Can this issue be closed?

**Comment by Purus** [comment]
For me, there is still an issue with `package_info_plus`.

```
Because mozhli depends on upgrader ^4.11.0 which depends on package_info_plus >=1.3.0 <3.0.0, package_info_plus >=1.3.0 <3.0.0 is required.
So, because mozhli depends on package_info_plus ^3.0.1, version solving failed.
pub get failed (1; So, because mozhli depends on package_info_plus ^3.0.1, version solving failed.)
```

**Comment by larryaasen** [comment]
@Purus @parmarravi I just created a prerelease version 5.0.0-alpha.1 with all packages updated to the latest version, and requiring Flutter version 3.0.1 or above. Check it out and let me know if it works for you. https://pub.dev/packages/upgrader/versions/5.0.0-alpha.1

**Comment by Purus** [comment]
Looks okay to me.

Thanks,
R.Purusothaman

**Comment by larryaasen** [comment]
Anyone else want to comment on this fix? @parmarravi ?
