### ISSUE TITLE
version solving failed

### ISSUE THREAD

**Issue by boskokg** [larryaasen/upgrader#23]
The current Flutter SDK version is 1.14.3.

Because xXx depends on upgrader >=0.10.1 which requires Flutter SDK version >=1.12.0 <1.13.0, version solving failed.

**Comment by larryaasen** [comment]
Try version 0.10.0 which supports Flutter 1.13 and 1.14.

**Comment by boskokg** [comment]
@larryaasen  your comment is a workaround, not a fix in the latest version. I don't understand why this ticket is closed?

**Comment by larryaasen** [comment]
There is no solution to this problem. The latest version supports Flutter stable which is the version supported by pub.dev. Flutter version 1.14.3 is not on the stable channel/branch, but rather the master or dev branch. You still still use version 0.10.0 of this package with master.

**Comment by boskokg** [comment]
I have one question. My company uses the deb channel and have no plans to move to stable one.

Is there a plan to support dev channel or I need to find some other plugin?

Note: I see that you have some fix for ios in the latest release, and now I cannot use it in the project...

Thanks
