### ISSUE TITLE
Upgrader causes lag on TextField 

### ISSUE THREAD

**Issue by ahndwon** [larryaasen/upgrader#233]
When using upgrader, inputting letters fast by soft keyboard causes lag on TextField widget.
It is more noticeable on Android phones than iPhones.
And if the phone's hardware performance is low, more noticeable.

I found out that only projects that are released on store gets this lag.
Projects that are not released doesn't have this issue.

I tried upgrader: ^4.8.1 and ^4.10.0
all have same problem

I used upgrader as below, with no parameters.
```
UpgradeAlert(
      upgrader: Upgrader(),
     child: TextField()
)
```

**Comment by larryaasen** [comment]
Don't create the Upgrader() instance more than once. You don't even need to create it at all. Just use this:
`UpgradeAlert(child: TextField())`

**Comment by larryaasen** [comment]
Glad that worked for you.

For the shared instance, are you talking about this line?
https://github.com/larryaasen/upgrader/blob/1ca48d2ad485dc02e47f74b704ef121e85ccb982/lib/src/upgrader.dart#L184

**Comment by larryaasen** [comment]
That getter is already typed.
