### ISSUE TITLE
upgrader: Can't find an app in the Play Store with the id

### ISSUE THREAD

**Issue by whateverfast** [larryaasen/upgrader#237]
Hi,

I am getting this error: 

upgrader: Can't find an app in the Play Store with the id: org.concordiahanoi.app

The app is already in Play Store with that id. Is it because I am now testing with the simulator?

**Comment by larryaasen** [comment]
Can you provide the full upgrader log?

**Comment by whateverfast** [comment]
Terminal:

Debug service listening on ws://127.0.0.1:62583/6-uYFv8yLiM=/ws
Syncing files to device sdk gphone64 arm64...
I/flutter (23533): upgrader: Can't find an app in the Play Store with the id: org.concordiahanoi.app
D/EGL_emulation(23533): app_time_stats: avg=501.19ms min=52.35ms max=1588.43ms count=4
I/flutter (23533): It is logged in!
W/FlutterJNI(23533): FlutterJNI.loadLibrary called more than once

Code:

UpgradeAlert(
                upgrader: Upgrader(
                    showIgnore: false,
                    showLater: false,
                    canDismissDialog: false,
                    countryCode: 'en',
                    showReleaseNotes: false,
                    messages: MyUpgraderMessages(),
                    //minAppVersion: "100.0.0",
                    durationUntilAlertAgain: const Duration(minutes: 1),
                    onUpdate: () {


Version:
upgrader: ^4.6.1

**Comment by whateverfast** [comment]
I have update it to the lastest version and still has the same problem.

**Comment by larryaasen** [comment]
@whateverfast Please set `debugLogging` to true and provide the entire upgrader log. Details here: https://pub.dev/packages/upgrader/versions/5.0.0-alpha.1#reporting-issues

**Comment by whateverfast** [comment]
I/flutter ( 5374): upgrader: instantiated.
I/flutter ( 5374): upgrader: build UpgradeAlert
I/flutter ( 5374): upgrader: languageCode: en
I/flutter ( 5374): upgrader: default operatingSystem: android sdk_gphone64_arm64-userdebug 12 S2B2.211203.006 8015633 dev-keys
I/flutter ( 5374): upgrader: operatingSystem: android
I/flutter ( 5374): upgrader: platform: TargetPlatform.android
I/flutter ( 5374): upgrader: isAndroid: true, isIOS: false, isLinux: false, isMacOS: false, isWindows: false, isFuchsia: false, isWeb: false
I/flutter ( 5374): upgrader: package info packageName: org.concordiahanoi.app
I/flutter ( 5374): upgrader: package info appName: Concordia Hanoi
I/flutter ( 5374): upgrader: package info version: 1.0.23
I/flutter ( 5374): upgrader: countryCode: en
I/flutter ( 5374): upgrader: languageCode: en
**I/flutter ( 5374): upgrader: Can't find an app in the Play Store with the id: org.concordiahanoi.app**
I/flutter ( 5374): upgrader: blocked: false
I/flutter ( 5374): upgrader: debugDisplayAlways: false
I/flutter ( 5374): upgrader: debugDisplayOnce: false
I/flutter ( 5374): upgrader: hasAlerted: false
I/flutter ( 5374): upgrader: appStoreVersion: null
I/flutter ( 5374): upgrader: installedVersion: 1.0.23
I/flutter ( 5374): upgrader: minAppVersion: null
I/flutter ( 5374): upgrader: isUpdateAvailable: false
I/flutter ( 5374): upgrader: shouldDisplayUpgrade: false
I/flutter ( 5374): upgrader: shouldDisplayReleaseNotes: false

**Comment by whateverfast** [comment]
I also tried to add the minAppVersion to 1.0.30 and it also does not show the popup

I/flutter ( 5596): upgrader: instantiated.
I/flutter ( 5596): upgrader: build UpgradeAlert
I/flutter ( 5596): upgrader: languageCode: en
I/flutter ( 5596): upgrader: default operatingSystem: android sdk_gphone64_arm64-userdebug 12 S2B2.211203.006 8015633 dev-keys
I/flutter ( 5596): upgrader: operatingSystem: android
I/flutter ( 5596): upgrader: platform: TargetPlatform.android
I/flutter ( 5596): upgrader: isAndroid: true, isIOS: false, isLinux: false, isMacOS: false, isWindows: false, isFuchsia: false, isWeb: false
I/flutter ( 5596): upgrader: package info packageName: org.concordiahanoi.app
I/flutter ( 5596): upgrader: package info appName: Concordia Hanoi
I/flutter ( 5596): upgrader: package info version: 1.0.23
I/flutter ( 5596): upgrader: countryCode: en
I/flutter ( 5596): upgrader: languageCode: en
I/flutter ( 5596): upgrader: Can't find an app in the Play Store with the id: org.concordiahanoi.app
I/flutter ( 5596): upgrader: blocked: true
I/flutter ( 5596): upgrader: debugDisplayAlways: false
I/flutter ( 5596): upgrader: debugDisplayOnce: false
I/flutter ( 5596): upgrader: hasAlerted: false
I/flutter ( 5596): upgrader: appStoreVersion: null
I/flutter ( 5596): upgrader: installedVersion: 1.0.23
I/flutter ( 5596): upgrader: minAppVersion: 1.0.30
I/flutter ( 5596): upgrader: isUpdateAvailable: false
I/flutter ( 5596): upgrader: shouldDisplayUpgrade: false
I/flutter ( 5596): upgrader: shouldDisplayReleaseNotes: false

**Comment by larryaasen** [comment]
I see this country code: `countryCode: 'en',`
What is the country `en`?

**Comment by whateverfast** [comment]
Oh no. Instead of languageCode I wrote CountryCode. :/
Now it is working in Android. Thank you!

I am not sure if I can ask the following questions:

1) How can I make sure that the user is "forced" to update the app. Currently, the alert is only dismissed if they click update (which goes to the play store or Apple Store). However, when they click to update the alert windows disappears and the user can still use the app.  Is there any way to make sure the alert window is not dismissed even when clicked?

2) If 1) not possible, is it possible to make the alert show up again 5min later after it is "dismissed"?

I have this setting: durationUntilAlertAgain: const Duration(minutes: 1)
However only when the user closes and opens the app again the alert shows up again.

Thank you!

**Comment by daumienebi** [comment]
@whateverfast Hey there, i think you can use the "minAppVersion" parameter of the Upgrader. According to the docs, users with version prior to the minimum version will be forced to update the app.
----------------------------------------------------------------------------------------------
/// The minimum app version supported by this app. Earlier versions of this app
/// will be forced to update to the current version. Optional.
String? minAppVersion; 
---------------------------------------------------------------------------------------------

**Comment by larryaasen** [comment]
@whateverfast If you are still having issues, please open a new issue.
