### ISSUE TITLE
How can I change the message texts. I tried I don't see any option for that

### ISSUE THREAD

**Issue by arammarm** [larryaasen/upgrader#240]

**Comment by DanilKarasev** [comment]
class MyUpgraderMessages extends UpgraderMessages {
  @override
  String get buttonTitleIgnore => 'My Ignore';
}

UpgradeAlert(Upgrader(messages: MyUpgraderMessages()));

**Comment by raphaeldivine3028** [comment]
This is simple, just like @DanilKarasev said, create a custom class, say MyOwnUpgraderMessage, name it whatever you want to, and override the texts you want to change.  

You can currently override the following texts: body, buttonTitleIgnore, buttonTitleLater, buttonTitleUpdate, prompt, releaseNotes, and title;

Sample:
```
 @override
  String get releaseNotes => "What's New?";
```

2. Then in your widget, your "messages" will now be the name of your new class, MyOwnUpgraderMessage.

Viola!
