### ISSUE TITLE
dialog getting dismissed

### ISSUE THREAD

**Issue by KallepalliTirumalesh** [larryaasen/upgrader#243]
Hi,
Thanks for the plugin
I am facing this issue on clicking update now the dialog is getting dismissed how to show persistent dialog until user updates the application.
```
class AppUpdate extends StatelessWidget{
  @override
  Widget build(BuildContext context) {
    // TODO: implement build
   return UpgradeAlert(
     upgrader: Upgrader(
         debugLogging: true,
         canDismissDialog: false,
         showIgnore: false,
         showLater: false,
         onUpdate: ()=>false,
         durationUntilAlertAgain: const Duration(seconds: 1)),

   );
  }

}
```

**Comment by Navil** [comment]
Did you find a solution? I have the same issue

**Comment by larryaasen** [comment]
@KallepalliTirumalesh @Navil Is this still an issue?

**Comment by sharathguvvala** [comment]
Hi, I have the same issue, The update needs to be persisted, upon clicking update now and coming back to app without updating and then clicking on update now is closing the modal.
