### ISSUE TITLE
Google Play description not working

### ISSUE THREAD

**Issue by Jip1912** [larryaasen/upgrader#249]
Currently using `upgrader: ^4.11.1`. I cannot update it since a package is interfering with another package.
I put this in my Google Play description:
![image](https://user-images.githubusercontent.com/8480593/209239681-b854516c-1a88-4b99-bd96-2f228c779695.png)

This is my code:
```dart
home: UpgradeAlert(
    upgrader: Upgrader(
        showLater: true,
        showIgnore: false,
        //debugDisplayAlways: true,
        messages: DutchUpgrader()),
    child: AuthenticationWrapper()),
```
My app version is currently 0.2.4.

I'm getting this error:
![image](https://user-images.githubusercontent.com/8480593/209239968-cb3629b1-01d0-4168-a262-b1e54cc1dd63.png)

When I continue in the debugger I get to this:
![image](https://user-images.githubusercontent.com/8480593/209240030-62d3cc0d-4fb2-446b-8c8f-e6f1aac52d82.png)
So weirdly enough it is taking the category tag as version.

Also getting this exception:
![image](https://user-images.githubusercontent.com/8480593/209240180-e9914ada-70e8-4ae1-902f-8beea055189a.png)

And this:
![image](https://user-images.githubusercontent.com/8480593/209240221-5fab7350-bfc6-4feb-a9a1-39c24c5032cc.png)

Can anyone help me solve this?

**Comment by larryaasen** [comment]
@Jip1912 Is this still an issue?

**Comment by Jip1912** [comment]
> @Jip1912 Is this still an issue?

Not for me
