### ISSUE TITLE
Its possible to use it without appstore or playstore?

### ISSUE THREAD

**Issue by geekz-reno** [larryaasen/upgrader#251]
Hi, its possible to use it without any store app or play store?  i mean if i host my own ipa or apk to my private server?

**Comment by jaasaria** [comment]
same question. also during development and don't yet have the store versions.

**Comment by ulisseshen** [comment]
You will need to configure the appcast for your app.

See
https://github.com/larryaasen/upgrader#appcast-example
https://github.com/larryaasen/upgrader#appcast-sample-file

**Comment by pankaj-nikam** [comment]
It's still not clear to me how to create XML for just apk file. Can you please share a sample?

**Comment by larryaasen** [comment]
@geekz-reno There is a good example that shows how to use the UpgraderStoreController to configure how each platform utilizes a store. You can create a class similar to UpgraderAppcastStore and use it with UpgraderStoreController.
https://github.com/larryaasen/upgrader/blob/master/example/lib/main_appcast.dart

**Comment by geekz-reno** [comment]
thank you @larryaasen , I will try it. I'll close for now.
