### ISSUE TITLE
These 3 variables [debugLogging, debugAlways, debugDisplayOnce] behavior is unexpected in Production

### ISSUE THREAD

**Issue by ndungudedan** [larryaasen/upgrader#258]
As the naming of these variables [`debugLogging`, `debugAlways`, `debugDisplayOnce`] communicates, it is expected that they should only be effective in `debug` mode. However, that's not the case, and if you forget to toggle back to `false` when releasing your app, they still affect whether the Upgrader should display or not.

**Comment by larryaasen** [comment]
@ndungudedan The term debug does not imply a debug build of the app. An app can be debugged using a release build. The term debug implies debugging and diagnosing problems.
