### ISSUE TITLE
Support flutter 1.17.0 stable

### ISSUE THREAD

**Issue by dfdgsdfg** [larryaasen/upgrader#26]
```
Because app depends on upgrader >=0.10.1 which requires Flutter SDK version >=1.12.0 <1.13.0, version solving failed.
```

### Workaround
Add this your `pubspec.yaml`
```yaml
dependency_overrides:
  upgrader: ^0.10.4
```

By the way, many thanks for the nice work. 👍

**Comment by larryaasen** [comment]
I see that Flutter stable is now 1.17.0. I can upgrade the SDK version.

**Comment by larryaasen** [comment]
@dfdgsdfg Thanks for pointing out this issue. I have updated this package on pub.dev to version 0.11.0 which now works with Flutter 1.17.0.
https://pub.dev/packages/upgrader#0110
