### ISSUE TITLE
Release notes not scrollable

### ISSUE THREAD

**Issue by OutdatedGuy** [larryaasen/upgrader#262]
For big release notes, upgrader dialog only shows starting portion of it. i.e. it it not scrollable.

<table>
  <tr>
    <td>Shown release notes</td>
    <td>Actual release notes</td>
  </tr>
  <tr>
    <td>
      <img src="https://user-images.githubusercontent.com/74326345/215681039-3c91ee56-b466-4705-b773-e057e22f49a0.jpeg" width="300px" />
    </td>
    <td><p>
    NEW:

- Introducing the new Global Subgroup. Meet 2 new people everyday.
  Nurture strong, trusting relationships for better mental health.

ADDED:

- Support for tablets.
- Onboarding screen to give a walkthrough to new users.

OTHER:

- Made some UI adjustments.
- Increased form interactivity and easy of use.
- Minor bug fixes and performance improvements.
</p></td>
  </tr>
</table>

**pubspec.lock:**
```lock
upgrader:
  dependency: "direct main"
  description:
    name: upgrader
    sha256: "600eec301fd27b985a7cf223c0d8f70f1bca6290b959fa970e399bb4da6e8c8e"
    url: "https://pub.dev"
  source: hosted
  version: "6.0.1"
```

**Code:**
```dart
UpgradeAlert(
  upgrader: Upgrader(
    showIgnore: false,
    showLater: false,
    durationUntilAlertAgain: const Duration(),
    dialogStyle: Theme.of(context).platform == TargetPlatform.iOS ||
            Theme.of(context).platform == TargetPlatform.macOS
        ? UpgradeDialogStyle.cupertino
        : UpgradeDialogStyle.material,
  ),
  child: const MainScreen(),
),
```

**Comment by larryaasen** [comment]
Thanks for reporting this issue. I fixed this on the main branch and will release it soon.

**Comment by OutdatedGuy** [comment]
@larryaasen, thanks for the fix. Just a small doubt though.

https://github.com/larryaasen/upgrader/commit/9858ae923bc0eefa90b40ef8c70739e7403f66e5#diff-3582f7c844a505f168907afb3f612b1c66a4406701a3bee046b0330a9436ff3bR641-R654

Instead of wrapping the scrollable content inside a constrained `Container` why not just set the `scrollable` property of `AlertDialog` to true.

<img width="245" alt="image" src="https://user-images.githubusercontent.com/74326345/221792472-de1d6446-3410-4005-9f60-4cf45a7276a1.png">

```dart
AlertDialog(
  scrollable: true,
);
```

**Comment by larryaasen** [comment]
@OutdatedGuy Yes that also works, but has the downside that the height of the dialog extends to the SafeArea, and I wanted to constrain the height to a reasonable value so it wouldn't take up the entire screen.
