### ISSUE TITLE
Message not compatible with flutter 3.7 l10N

### ISSUE THREAD

**Issue by EArminjon** [larryaasen/upgrader#264]
UpgraderMessage.body

"upgrader_message_body": "En ny version av '{{appName}}' app! Version {{currentAppStoreVersion}} finns tillgänglig - du har version {{currentInstalledVersion}}.",

 ICU Syntax Error: Expected "identifier" but found "{".
 
Management of Double "{" or "}" seems to not be anymore correct.

**Comment by EArminjon** [comment]
With flutter 3.7.1 / 3.7.0, the usage of the double '{' seems to not work. {{appName}} is used here for example :
https://github.com/larryaasen/upgrader/blob/master/lib/src/upgrade_messages.dart

Maybe 3.7.2 fix that, need to test

**Comment by larryaasen** [comment]
Seems to work here on 3.7.0: https://github.com/larryaasen/upgrader/actions/runs/4015075928/jobs/6896372252

**Comment by larryaasen** [comment]
Can you provide specific details on the errors you are seeing?

**Comment by omarfaroke** [comment]
To avoid the localization problem with Flutter 3.7, you can use Escaping syntax.
Like this:

![flutter-localization-use-escaping](https://user-images.githubusercontent.com/11462969/218972423-e876f322-a76d-4154-9c55-1a240c36f8e6.jpg)

See this for more information:
[Escaping syntax](https://docs.flutter.dev/development/accessibility-and-localization/internationalization#escaping-syntax)

**Comment by EArminjon** [comment]
Wondering if this package should warn developer about it or not ? You can close @larryaasen  ;)

**Comment by larryaasen** [comment]
@EArminjon You seem to be showing specific issues with your own code. Do you have any examples of specific issues with the upgrader code?

**Comment by EArminjon** [comment]
@larryaasen The omarfaroke's answer is correct. 

When I opened this issue his suggestion was not working but it was in reality because of an other issue that flutter have fixed. So i think it was related to this package but hopefully no :) !

I suggest to add in the package readme a line to use `use-escaping: true` if developer plan to override your translation ;).
