### ISSUE TITLE
Will it work for the already installed apps with out implemented the upgrader?

### ISSUE THREAD

**Issue by HarishBirlangi242** [larryaasen/upgrader#274]
In play store I already have the app version 1.0.0, and now I implemented upgrader in my 2.0.0 version. will it give an app upgrade alert to the users who are using 1.0.0 version app? I think it will not work right?

**Comment by larryaasen** [comment]
It will not show in the 1.0.0 version because the code was not in that version. If you add upgrader in 2.0.0, it will show on the next update after 2.0.0.
