### ISSUE TITLE
Appcast different version for iOS vs. web

### ISSUE THREAD

**Issue by mattostanik** [larryaasen/upgrader#277]
I really like this package. I am using it in a Flutter app published on web, iOS and Android, and I am using an appcast file. Here is my Appcast.xml content:

```
<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0"
  xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle">
  <channel>
    <title>Releases</title>
    <item>
      <title>Android Release</title>
      <enclosure sparkle:version="2.4.4" sparkle:os="android"/>
    </item>
    <item>
      <title>iOS Release</title>
      <enclosure sparkle:version="2.4.4" sparkle:os="ios"/>
    </item>
    <item>
      <title>Web Release</title>
      <enclosure sparkle:version="2.4.5" />
    </item>
  </channel>
</rss>
```

Recently I needed to require a different minimum version (2.4.5) on web vs. the minimum version for iOS (2.4.4).

When I published the above Appcast.xml, the iOS app then started showing the upgrade alert and requiring users to install 2.4.5 even though the iOS version in the file was supposed to be 2.4.4. This was a problem because I had not yet released 2.4.5 on iOS.

Is it possible to have different minimum versions for web vs. iOS vs. Android?

Here is how I have implemented the package in my main.dart:

```
  final appCastConfiguration =
      AppcastConfiguration(url: "https://appcast.mydomain.org/appcast.xml");

[...]

          home: UpgradeAlert(
            upgrader: Upgrader(
                appcastConfig: appCastConfiguration,
                canDismissDialog: false,
                showIgnore: false,
                showLater: false,
                durationUntilAlertAgain: Duration.zero,
                onUpdate: () {

```

Is there a way to modify either my Appcast.xml content or my Flutter implementation to support different minimum versions per platform? Or is it only possible to have one minimum version across all platforms with this package?

Thank you.

**Comment by larryaasen** [comment]
@mattostanik Your Appcast file is missing the OS:
`<enclosure sparkle:version="2.4.5" />`
Perhaps you should add the web OS to avoid iOS picking up that version:
`<enclosure sparkle:version="2.4.5" sparkle:os="web" />`

**Comment by larryaasen** [comment]
@mattostanik Did my suggestion above work for you?
