### ISSUE TITLE
Theme.of(context).textTheme.headline6

### ISSUE THREAD

**Issue by xie438305665** [larryaasen/upgrader#28]
pub-cache/hosted/pub.flutter-io.cn/upgrader-0.11.1/lib/src/upgrade_alert.dart:388:46: Error: The getter 'headline6' isn't defined for the class 'TextTheme'.

**Comment by xie438305665** [comment]
update  upgrader_alert

**Comment by hacksics** [comment]
How did you fix this issue? I had to use the version 0.10.2 to get this issue fixed. However I cannot use the latest release 

My Flutter version as follows:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E287)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Android Studio (version 3.6)

**Comment by larryaasen** [comment]
@hacksics There are no issues using Flutter: 1.17.0, which is the stable release after v1.12.13+hotfix.9. Are you not able to use 1.17.0?

**Comment by DennisMuchiri** [comment]
> 
> 
> @hacksics There are no issues using Flutter: 1.17.0, which is the stable release after v1.12.13+hotfix.9. Are you not able to use 1.17.0?

This is not a solution

**Comment by DennisMuchiri** [comment]
> 
> 
> @hacksics There are no issues using Flutter: 1.17.0, which is the stable release after v1.12.13+hotfix.9. Are you not able to use 1.17.0?

@larryaasen Facing the same issue

**Comment by larryaasen** [comment]
@DennisMuchiri What version of Flutter are you using? What version of upgrader are you using? What error message are you seeing?
