### ISSUE TITLE
Null check operator on nullable value

### ISSUE THREAD

**Issue by Jblew** [larryaasen/upgrader#284]
Hi! I've experienced a crash of upgrader with the following error: `_CastError upgrader.dart in Upgrader._showDialog: Null check operator used on a null value`

I have indeed found a mistake in that function. It's located in the `/lib/src/upgrader.dart` on lines 621 and 622. In the `_showDialog` function definition there is a `String? title` type yet on lines 621 & 622 you use non-null assertion `title!`. I think this could be replaced with `title ?? ''`

Link to code: https://github.com/larryaasen/upgrader/blob/f48fd39f2498767d518f42f62d13726b58c77828/lib/src/upgrader.dart#L621

Thank you! :)

**Comment by larryaasen** [comment]
@Jblew Thanks for pointing that out. I have a fix in the works now. Can you share with me your use case for this so I can properly test it?

**Comment by Jblew** [comment]
Well, my usecase turnus out to be my mistake honestly. I have wrapped MaterialApp inside the UpgradeAlert and not the other way. So actually looks like this situation happens only when the app is outside of the scope of MaterialLocalizations

**Comment by larryaasen** [comment]
@Jblew Good to know, I will try that. Thanks.

**Comment by larryaasen** [comment]
Fixed in version [6.5.0](https://pub.dev/packages/upgrader/versions/6.5.0).
