### ISSUE TITLE
Release notes getting clipped to 14 lines for `UpgradeDialogStyle.cupertino`

### ISSUE THREAD

**Issue by utkarsh1097** [larryaasen/upgrader#287]
#262 and the [subsequent commit](https://github.com/larryaasen/upgrader/commit/9858ae923bc0eefa90b40ef8c70739e7403f66e5) fixes the scrollability issue for `AlertDialog`, which is used when `dialogStyle = UpgradeDialogStyle.material`, but even as of today, the text gets truncated to the first 14 lines in case of `dialogStyle = UpgradeDialogStyle.cupertino`.

Source: 
https://github.com/larryaasen/upgrader/blob/081b98f94340aed38fafc4824e91bbd7dd082cc7/lib/src/upgrader.dart#L698-L750

**Comment by utkarsh1097** [comment]
@larryaasen Any approximate ETA for this? Or can I take this up?

**Comment by larryaasen** [comment]
@utkarsh1097 I have not looked at this yet and don't have an ETA. Feel free to look at this if you are interested.

**Comment by larryaasen** [comment]
@utkarsh1097 I have a fix for this now on the master branch. Will be releasing a new version soon.
