### ISSUE TITLE
Is there a function in Upgrader to install the app directly after downloading the application via appcast?

### ISSUE THREAD

**Issue by kenboi** [larryaasen/upgrader#29]
I assumed that when an update is available, it redirects to a link where the user can download the application. But can Upgrader detect if the app finishes downloading and can it be installed via some function in the Upgrader package?

**Comment by larryaasen** [comment]
For iOS, the UPDATE NOW button takes the user to the App Store where the update process can be started. For Android, the UPDATE NOW button takes the user to the URL located in the Appcast file, which is normally the Play Store URL. Both OS'es handle the case of the downloading and installing of the update. See this section in the README file for more details on the [Android Appcast file](https://pub.dev/packages/upgrader#appcast-sample-file).
