### ISSUE TITLE
Please consider upgrading the dependencies to Dart3/Flutter 3.10.x, e.g. http -> 1.0.0

### ISSUE THREAD

**Issue by MagnusJohansson** [larryaasen/upgrader#290]
Upgrader v7.0.0 has a dependency on the older http v0.13.6.
Now with Flutter 3.10/Dart3 we have a new http v1.0.0

Please consider upgrading to use that instead.
```
Because upgrader >=7.0.0 depends on http ^0.13.6 and my_app depends on http ^1.0.0, upgrader >=7.0.0 is forbidden.
So, because my_app depends on upgrader ^7.0.0, version solving failed.
exit code 1
```

**Comment by larryaasen** [comment]
Since package_info_plus depends on http: ">=0.13.5 <2.0.0", the http dependency cannot be upgraded to 1.0.0 yet.

**Comment by MagnusJohansson** [comment]
1.0.0 falls in between >= 0.13.5  and < 2.0.0 , so that shouldn't be a problem?

**Comment by larryaasen** [comment]
@MagnusJohansson
After changing the upgrader pub.dev:
```
  http: ^1.0.0
  package_info_plus: ^4.0.1
```
This is what I get:
```
> flutter pub get
Resolving dependencies...
Because package_info_plus 4.0.1 depends on http ^0.13.5 and no versions of package_info_plus match >4.0.1 <5.0.0, package_info_plus ^4.0.1 requires http ^0.13.5.
So, because upgrader depends on both http 1.0.0 and package_info_plus ^4.0.1, version solving failed.
```

**Comment by larryaasen** [comment]
Actually, just upgrading these worked:
```
  device_info_plus: ^9.0.1
  package_info_plus: ^4.0.1
```

**Comment by larryaasen** [comment]
Version 7.0.1 is out with this change. https://pub.dev/packages/upgrader/versions/7.0.1

**Comment by larryaasen** [comment]
Version 7.0.2 should fix this, hopefully.
