### ISSUE TITLE
cant access the flutter Plugin while running Flutter pub get

### ISSUE THREAD

**Issue by don-k-jacob** [larryaasen/upgrader#291]
Git error. Command: `git clone --mirror https://github.com/MarkOSullivan94/dart_config.git /Users/don_k_jacob/.pub-cache/git/cache/dart_config-d2db83fa92bb229094789c5489c5e2d3cc175814`
stdout: 
stderr: Cloning into bare repository '/Users/don_k_jacob/.pub-cache/git/cache/dart_config-d2db83fa92bb229094789c5489c5e2d3cc175814'...
remote: Repository not found.
fatal: repository 'https://github.com/MarkOSullivan94/dart_config.git/' not found
exit code: 128
pub get failed
command: "/Users/don_k_jacob/flutter/bin/cache/dart-sdk/bin/dart __deprecated_pub --directory . get --example"
pub env: {
  "FLUTTER_ROOT": "/Users/don_k_jacob/flutter",
  "PUB_ENVIRONMENT": "vscode.dart-code:flutter_cli:get",
  "PUB_CACHE": "/Users/don_k_jacob/.pub-cache",
}
exit code: 69

exit code 69

**Comment by larryaasen** [comment]
@don-k-jacob What does this error have to do with the upgrader package?
