### ISSUE TITLE
Debug shows update available but no Dialog opens

### ISSUE THREAD

**Issue by byteripper** [larryaasen/upgrader#296]
The debuglog shows that there is an update available, but no AlertDialog is displayed.
Why is shouldDisplayUpgrade: false when isUpdateAvailable: true?
What does isTooSoon: true mean?

I hope someone can help me.

I/flutter (15413): upgrader: instantiated.
I/flutter (15413): upgrader: build UpgradeAlert
I/flutter (15413): upgrader: initialize called
I/flutter (15413): upgrader: initializing
I/flutter (15413): upgrader: languageCode: de
I/flutter (15413): upgrader: default operatingSystem: android sdk_gphone_x86-userdebug 8.1.0 OSM1.180201.037 6739391 dev-keys
I/flutter (15413): upgrader: operatingSystem: android
I/flutter (15413): upgrader: isAndroid: true, isIOS: false, isLinux: false, isMacOS: false, isWindows: false, isFuchsia: false, isWeb: false
I/flutter (15413): upgrader: package info packageName: de.asvwoelfersheim.kontrolle
I/flutter (15413): upgrader: package info appName: Kontrolle
I/flutter (15413): upgrader: package info version: 1.0.0
I/flutter (15413): upgrader: appcast is available for this platform
I/flutter (15413): upgrader: appcast item count: 2
I/flutter (15413): upgrader: appcast best item version: 1.0.1
I/flutter (15413): upgrader: appcast critical update item version: null
I/flutter (15413): upgrader: blocked: false
I/flutter (15413): upgrader: debugDisplayAlways: false
I/flutter (15413): upgrader: debugDisplayOnce: false
I/flutter (15413): upgrader: hasAlerted: false
I/flutter (15413): upgrader: appStoreVersion: 1.0.1
I/flutter (15413): upgrader: installedVersion: 1.0.0
I/flutter (15413): upgrader: minAppVersion: null
I/flutter (15413): upgrader: isUpdateAvailable: true
I/flutter (15413): upgrader: isTooSoon: true
I/flutter (15413): upgrader: shouldDisplayUpgrade: false
I/flutter (15413): upgrader: shouldDisplayReleaseNotes: true

  upgrader:
    dependency: "direct main"
    description:
      name: upgrader
      sha256: "71cb887dbaec121b63950d4e5d368a4b9e2079f6d8fef6f358728eb7a63d9f29"
      url: "https://pub.dev"
    source: hosted
    version: "7.1.0"

**Comment by larryaasen** [comment]
isTooSoon: true

You must have tapped ignore. Just reset the settings as you see in the example code for debugging.

**Comment by byteripper** [comment]
Thanks for the response.
That did the trick, working fine now.

**Comment by byteripper** [comment]
Working now.
