### ISSUE TITLE
Message localization.

### ISSUE THREAD

**Issue by awaik** [larryaasen/upgrader#30]
Hi, thank you for the great package!

Do I understand correctly that there is no way to make localization for the message with version number? 

```  
String message() {
    return 'A new version of ${appName()} is available! Version ${currentAppStoreVersion()} is now available-you have ${currentInstalledVersion()}.';
  }
```
(file upgrader.dart)

If not possible can you please make the property with this String for customization, please?

**Comment by awaik** [comment]
This issue solved in the pull request, can you please check
https://github.com/larryaasen/upgrader/pull/35

**Comment by larryaasen** [comment]
The latest upgrade to this package adds support for localizations and custom messages. Please see [Customizing the display](https://github.com/larryaasen/upgrader#customizing-the-display) section on README for more details. This was added by PR https://github.com/larryaasen/upgrader/pull/38.
