### ISSUE TITLE
Right-to-Left direction

### ISSUE THREAD

**Issue by samialfattani** [larryaasen/upgrader#305]
**I'm using localization of "ar_SA" , and the Arabic reading context actually written is Right-to-Left direction, but it seems this tool dose not support this feature , is there anyway to workarround and change the directionality of the upgrader box?**

**Comment by larryaasen** [comment]
Seems like this should work. Can you share a screenshot of this issue?

**Comment by larryaasen** [comment]
@samialfattani  I think RTL support works well in the latest version [8.3.0](https://pub.dev/packages/upgrader), so please try that version and see if it works for you.
