### ISSUE TITLE
Upgrader dont show because outdated shared_preferences

### ISSUE THREAD

**Issue by DarkArlekin** [larryaasen/upgrader#311]
Hello,

Error in Flutter 3.10.6 (dart 3.0.6) while use upgrader 7.1.0
Where: in upgrader.dart, line:787, function _getSavedPrefs
How I fix: dependency_overrides: shared_preferences: ^2.2.0

Purpose: Update the version of the shared_preferences to the latest

Please let me know if you need any additional information or if there are any modifications I should make.

Thank you!

**Comment by larryaasen** [comment]
This was fixed in version 8.3.0
