### ISSUE TITLE
Bad state: Stream has already been listened to.

### ISSUE THREAD

**Issue by fotiDim** [larryaasen/upgrader#312]
After upgrading to 8.0.0 I am getting:
```
════════ Exception caught by widgets library ═══════════════════════════════════
The following StateError was thrown building UpgradeAlert-[<'ua_1'>](state: UpgradeBaseState#4656c):
Bad state: Stream has already been listened to.
```
My app uses `UpgradeAlert` in two separate places and the exceptions is thrown during the second UpgradeAlert. I tried passing `key` with the same and also different values but makes no difference.

**Comment by markalroberts** [comment]
I get the same problem where I use onGenerateRoute to create a new MaterialPageRoute - it displays fine the first time but then breaks whenever I try to navigate to a different route - guessing somewhere it needs to dispose/stop listening to the stream?

**Comment by sgrodzicki** [comment]
This for me only happens with the shared instance, so I guess including logs is not possible in that case.

```dart
return UpgradeAlert(
  child: Scaffold(),
);
```

**Comment by adar2378** [comment]
Same issue. The stacktrace has no reference to code but rather to only stream controller library of dart

**Comment by adar2378** [comment]
I guess this should be a broadcast stream 
  final _streamController = StreamController<UpgraderEvaluateNeed>(); // should be StreamController<UpgraderEvaluateNeed>.broadcast()
  
  https://github.com/larryaasen/upgrader/blob/db563d2b8f9648358ddc0456a114d99898fbe908/lib/src/upgrader.dart#L160

**Comment by larryaasen** [comment]
The use of upgrader has far surpassed what I had envisioned for this package, and it is being used in cases where I had never imagined. This particular issue was never a case I had anticipated: instantiating more than one UpgradeAlert.

Thanks for pointing out this issue and suggesting changes. I will get a fix out as soon as possible.

**Comment by larryaasen** [comment]
I created a branch with a fix and posted this new pre-release version: https://pub.dev/packages/upgrader/versions/8.1.0-alpha.1
Please check it out and let me know if this solves your issues.

**Comment by larryaasen** [comment]
Version 8.1.0 has been published with this fix.
