### ISSUE TITLE
Upgrader has a hard requirement version of less than 1.18.0

### ISSUE THREAD

**Issue by themobilecoder** [larryaasen/upgrader#32]
Hi,

Is this requirement necessary for this package? Just wondering because the version in master and dev channel at the moment is at 1.20.0 now.

**Comment by larryaasen** [comment]
I removed the restriction for Flutter SDK <1.18.0 and published version 0.11.2 in pub.dev, so try that out.

**Comment by themobilecoder** [comment]
@larryaasen cheers mate!
