### ISSUE TITLE
Not working on Play store alpha channel, updated appbundle on play store on Closed Testing (alpha channel),

### ISSUE THREAD

**Issue by dhiren-basra** [larryaasen/upgrader#321]
upgrader:
    dependency: "direct main"
    description:
      name: upgrader
      url: "https://pub.dev"
    source: hosted
    version: "6.5.0"

Not working on "Play Store Closed Testing" Channel release : 
updated appbundle on play store on Closed Testing (alpha channel),
but not available for testes existing app.

Added like this in code : on home screen (homePage.dart -> HomeScreen) at top widget in build method : 

UpgradeAlert(
          upgrader: Upgrader(
            dialogStyle: UpgradeDialogStyle.cupertino,
          ), child : someWidget());

**Comment by tejpalSinghRathore** [comment]
Did it work any other way around @dhiren-basra

**Comment by larryaasen** [comment]
The upgrader package will only work with Google Play apps release in production. The app must be visible here: https://play.google.com/store/apps

**Comment by dhiren-basra** [comment]
okay @larryaasen, your app should be publicly available, only then upgrader package will works, noted, and it will not works in other testing channels, like Closed, Internal, Beta Testing etc.
@tejpalSinghRathore it will works only in production release mode.

**Comment by dhiren-basra** [comment]
Close
