### ISSUE TITLE
Dont show dialog on IOS device

### ISSUE THREAD

**Issue by phudqph09495** [larryaasen/upgrader#331]
I use upgrader, this works well on Android but upgrade dialog not show on IOS device

My version in Appstore is
![image](https://github.com/larryaasen/upgrader/assets/71993940/30f100d8-8669-45b7-88d5-89efc7afeb75)
![image](https://github.com/larryaasen/upgrader/assets/71993940/f0f862d7-7d14-4c6b-b94c-cbb8b274fd0e)

My code simply is

 ```
home: UpgradeAlert(

          child: MyHomePage(),
          upgrader: Upgrader(dialogStyle: UpgradeDialogStyle.cupertino, showLater: false,

            showIgnore: false),
        ),

```

**Comment by larryaasen** [comment]
@phudqph09495 To better assist in analyzing issues, please include all of the upgrader log, which can be enabled by setting debugLogging to true.

**Comment by larryaasen** [comment]
@phudqph09495 Are you still having issues?

**Comment by phudqph09495** [comment]
> @phudqph09495 Are you still having issues?

i'm done. Because the version number in my YAML file does not match the version on App Store Connect.
