### ISSUE TITLE
Dependency Conflict: upgrader v8.1.0 Requires device_info_plus ^9.0.1

### ISSUE THREAD

**Issue by Shahidbangash** [larryaasen/upgrader#336]
### Dependency Conflict with Upgrader v8.1.0

Hello,

I recently encountered a dependency conflict while trying to use the `upgrader` package version `8.1.0`. The package specifically requires `device_info_plus ^9.0.1`, which seems to be causing compatibility issues.

#### Error Message:
```dart
upgrader 8.1.0 depends on device_info_plus ^9.0.1 and no versions of upgrader match >8.1.0 <9.0.0, upgrader ^8.1.0 requires device_info_plus ^9.0.1.
```
This conflict is preventing the successful integration of the `upgrader` package in my Flutter project.

### Suggestion:
To the author/maintainer of the `upgrader` package, it would be beneficial for users if the package could either:

1. Incorporate the latest version of the dependent package (`device_info_plus`) to ensure compatibility.
2. Or, consider using `any` for the dependency version, allowing users more flexibility in upgrading their transitive packages.

It would be greatly appreciated if this could be looked into and resolved.

**Comment by larryaasen** [comment]
This has been resolved in version 8.2.0 on pub.dev.
