### ISSUE TITLE
Custom Upgrader won't work

### ISSUE THREAD

**Issue by emirua** [larryaasen/upgrader#337]
Hi, if you use a custom Upgrader, even if it's the default constructor, the notification or the upgradeCard won't show.However, if you use Upgrader.sharedInstance it works.

**Comment by emirua** [comment]
I see now that you need to create an instance that doesn't get recreated if a widget is updated. Maybe it would be good to document this case in the README as it's a common case in flutter.

**Comment by dwainetrain** [comment]
@emirua, Can you give an example of what worked for you?
