### ISSUE TITLE
UpdateAlert not working properly

### ISSUE THREAD

**Issue by KevinYan12138** [larryaasen/upgrader#34]
I used updateAlert as the way the example uses. However, when I download the app version 1.01 from App Store, it still asks me to update even though I have the newest version. Why did that happen?

**Comment by larryaasen** [comment]
Could that be a semantic versioning problem? What is the bundle ID for the app?

**Comment by KevinYan12138** [comment]
> Could that be a semantic versioning problem? What is the bundle ID for the app?

com.guanwenyan.organizer

**Comment by larryaasen** [comment]
When I used com.guanwenyan.organizer in the example app, it works properly. Do you have any other details you can provide to diagnose this problem?

**Comment by KevinYan12138** [comment]
Then I do not know what went wrong. It is possible it happens because I published a newer version of the app that is waiting in review? ![image](https://user-images.githubusercontent.com/38302673/85179194-3165fe00-b235-11ea-9026-99e0e739b7e5.jpeg)

**Comment by KevinYan12138** [comment]
Or is there a method I can use to check the version of my app manually?

**Comment by larryaasen** [comment]
The unpublished update in review will not have any impact on this process.

The app store version of your app is: 1.01
The running app version is: 1.0.1
The running app has an older version because 1.0.1 is older than 1.01

I see in that alert message that the app name is null. That is a problem. It should display the `Display Name`, or the `Bundle display name`. Any idea why the name is null?

**Comment by KevinYan12138** [comment]
I already solve the app name issue. Are you saying that in order to solve this issue, I should now make version number in the format of 1.01 1.02 etc?

**Comment by larryaasen** [comment]
Version `1.01` is the same as `1.1`. Normally, after `1.1` you would increment the minor version and use `1.2`.

**Comment by KevinYan12138** [comment]
Ok, thanks. I will see if that works! Thanks for your help and your effort of making this package!

**Comment by larryaasen** [comment]
Closing this issue as it seems to have been resolved without the need for code changes.
