### ISSUE TITLE
Upgrader dialog doesn't show

### ISSUE THREAD

**Issue by Kedmanee** [larryaasen/upgrader#346]
![image](https://github.com/larryaasen/upgrader/assets/73660985/a77c55a0-63ce-47f9-908a-c80fdfa843fa)
I just copied code form example but no dialog show. Im not sure is there any cause by upgrader: blocked: true in log
Here's log
flutter: upgrader: blocked: true
flutter: upgrader: debugDisplayAlways: false
flutter: upgrader: debugDisplayOnce: false
flutter: upgrader: hasAlerted: false
flutter: upgrader: appStoreVersion: null
flutter: upgrader: installedVersion: 1.0.0
flutter: upgrader: minAppVersion: 15.5.5
flutter: upgrader: isUpdateAvailable: false
flutter: upgrader: shouldDisplayUpgrade: false
flutter: upgrader: shouldDisplayReleaseNotes: false

  upgrader:
    dependency: "direct main"
    description:
      name: upgrader
      sha256: "85496acfa024eb9e0c3c835d4c2358a000b21e021e9ca8835f56519ffa5e84f2"
      url: "https://pub.dev"
    source: hosted
    version: "8.2.0"

**Comment by markusrut** [comment]
i think `isUpdateAvailable` is your issue, even if you specify minAppVersion it still checks for available version befor showing prompt unless forced by debug flags

```
    if (debugDisplayAlways || (debugDisplayOnce && !_hasAlerted)) {
      rv = true;
    } else if (!isUpdateAvailable()) {
      rv = false;
    } else if (isBlocked) {
      rv = true;
    } else if (isTooSoon() || alreadyIgnoredThisVersion()) {
      rv = false;
    }
```

**Comment by Kedmanee** [comment]
how could i fix it

**Comment by larryaasen** [comment]
It says in the log: _flutter: upgrader: appStoreVersion: null_
That means there was no app store version found. Has the app been published? Does the bundle ID match what is on the App Store?

**Comment by iaohtdev** [comment]
Just added     await Upgrader.clearSavedSettings();
 in main.dart

**Comment by larryaasen** [comment]
@iaohtdev You don't normally call `clearSavedSettings()` unless you are using it for testing.

**Comment by ozancamur** [comment]
@Kedmanee  Is there any solution?
