### ISSUE TITLE
Store VersionCode control

### ISSUE THREAD

**Issue by EcenurOzal** [larryaasen/upgrader#355]
Is it only based on versionName?, I want to use it also based on versionCode. When my version is 1.0.0+1 and my store version is 1.0.0+2 , it only checks 1.0.0, does not compare +2 part. Is there any way to control it ?

**Comment by larryaasen** [comment]
The `upgrader` package follows the [semver.org](https://semver.org/) versioning strategy and the comparison of versions is spelled out in their specification. It specifically states: "Build metadata MUST be ignored when determining version precedence." in [section #10](https://semver.org/#spec-item-10). That is why upgrader does not show your version 1.0.0+2 as greater than 1.0.0+1.

**Comment by EcenurOzal** [comment]
Thanks for answering
