### ISSUE TITLE
[Feature Request] Add dialogKey parameter to the alert dialog

### ISSUE THREAD

**Issue by AhmedLSayed9** [larryaasen/upgrader#371]
It'd be helpful if we can add a key to the alert dialog that's used internally.

This allows us to check whether the dialog is shown or not to be able to prevent pushing to new screens. It's also a possible solution for #269

I can open a PR if this is cool.

**Comment by larryaasen** [comment]
@AhmedLSayed9 Good idea. I just added the key upgrader_alert_dialog and you can now use it in this new version that is under test: https://pub.dev/packages/upgrader/versions/9.0.0-alpha.2

**Comment by AhmedLSayed9** [comment]
@larryaasen 

The update provided doesn't fit with the issue's request. It just adds an internal key to the dialog.

What I proposed is to set the dialog key from client's code so that he can check if the dialog is open or not, basically something like:
```dart
// Global key
final GlobalKey dialogKey = GlobalKey();

// Inject the dialogKey
UpgradeAlert(
dialogKey: UpgradeAlertData.dialogKey,
);

// Use that key to determine if the dialog is open
dialogKey.currentContext != null
```

**Comment by AhmedLSayed9** [comment]
I've implemented it at a fork if it can help: https://github.com/AhmedLSayed9/upgrader/commit/998b54c4de1bd2868b31e0ca479d3f4d066d7ca6

**Comment by larryaasen** [comment]
@AhmedLSayed9 I see what you are saying now and that makes sense. Let me see what I can do.

**Comment by larryaasen** [comment]
@AhmedLSayed9 I added the dialogKey parameter to UpgradeAlert as you suggested and that seems to work well. You can try it in this new prerelease: https://pub.dev/packages/upgrader/versions/9.0.0-alpha.3
