### ISSUE TITLE
Is there a way to change the theme of the Alert or override it?

### ISSUE THREAD

**Issue by Kontrano** [larryaasen/upgrader#382]
I customized my app theme to work for my app's layout. However, if i want to use the upgrader package this results in an alert dialog with giant text. Is there a way to change which font styles it uses or overwrite the theme? See my image below:

![image](https://github.com/larryaasen/upgrader/assets/80490564/3dfb4ade-afe9-442c-8846-f3edc4b1e34e)

**Comment by RaadShariat** [comment]
You can wrap `UpgradeAlert` with a `Theme` widget and override your app's default style by providing a `ThemeData`.

**Comment by Kontrano** [comment]
> You can wrap `UpgradeAlert` with a `Theme` widget and override your app's default style by providing a `ThemeData`.

Thanks, not sure why i didn't think of that, will give it a try as soon as possible

**Comment by larryaasen** [comment]
@Kontrano Did that work?

**Comment by Kontrano** [comment]
> @Kontrano Did that work?

@larryaasen  Yes i just tested it, Wrapping it in a theme widget makes it look proper again, The thing to watch out for is to wrap the child in another Theme widget to set the theme back to what it should be.
