### ISSUE TITLE
debugDisplayOnce = true  always shows the upgrader dialog even in RELEASE MODE

### ISSUE THREAD

**Issue by RoberRaf** [larryaasen/upgrader#389]
**Problem description:** 
if  debugDisplayOnce  is set to true, an upgrader dialog will always show up even in release mode, even there is no newer version in the store or both versions are the same.

**Expected behavior:**
upgrader dialog only shows in debug mode as long as there is no a newer version.

============================
my code:

Scaffold(
        body: UpgradeAlert(
          upgrader: Upgrader(
              debugDisplayAlways: false,
              debugDisplayOnce: true,
              debugLogging: true,
              durationUntilAlertAgain: const Duration(hours: 2),
              messages:
                  UpgraderMessages(code: L10n.isAr(context) ? 'ar' : 'en'),
              willDisplayUpgrade: (
                  {appStoreVersion,
                  required bool display,
                  installedVersion,
                  minAppVersion}) {
                if (!display) fetchAndRedirect();
              }),
          dialogStyle: Platform.isAndroid
              ? UpgradeDialogStyle.material
              : UpgradeDialogStyle.cupertino,
          showIgnore: false,
          canDismissDialog: false,
          onLater: () {
            fetchAndRedirect();
            return true;
          },
          child: SizedBox(),);

==================================
my log :

upgrader: instantiated
upgrader: initialize called
upgrader: build UpgradeAlert
upgrader: initializing
upgrader: default operatingSystem: android TE1A.220922.010
upgrader: operatingSystem: android
upgrader: isAndroid: true, isIOS: false, isLinux: false, isMacOS: false, isWindows: false, isFuchsia: false, isWeb: false
package info packageName: *****
package info appName: ****
package info version: 1.1.3
countryCode: US
languageCode: en
lookupById url: https://play.google.com/store/apps/details?id=*******&gl=US&hl=en&_cb=1709561649413980
upgrader: need to evaluate version
upgrader: blocked: false
upgrader: debugDisplayAlways: false
upgrader: debugDisplayOnce: false
upgrader: hasAlerted: false
upgrader: appStoreVersion: 1.1.2
upgrader: installedVersion: 1.1.3
upgrader: minAppVersion: null
upgrader: isUpdateAvailable: false
upgrader: shouldDisplayUpgrade: false
upgrader: shouldDisplayReleaseNotes: shouldDisplayReleaseNotes

===========================================
pubspec.lock

upgrader:
    dependency: "direct main"
    description:
      name: upgrader
      sha256: "0c5fe8101b9d3017aebcb5175b49c382699725ffcf477afbe93fc3351491f6e8"
      url: "https://pub.dev"
    source: hosted
    version: "9.0.0"

**Comment by larryaasen** [comment]
@RoberRaf The term debug does not imply a debug build of the app. An app can be debugged using a release build. The term debug implies debugging and diagnosing problems. See https://en.wikipedia.org/wiki/Debugging.

**Comment by FadiAljabrii** [comment]
@RoberRaf how did you resolve this problem?
the Upgraderalert is being displayed even if there is no newer version in app store!

**Comment by RoberRaf** [comment]
@FadiAljabrii 
**Just set `debugDisplayOnce ` and `debugDisplayAlways` values to false.**

 as the author said. He didn't mean by debugging "a debug build". instead, it reflects the debugging process itself in any build (release, profile, or debug build), so it will always appear as long as you keep the boolean value of `debugDisplayOnce ` or `debugDisplayAlways`   true.

so you need to set those  `debugDisplayOnce ` and `debugDisplayAlways` values to false.
