### ISSUE TITLE
checkVersion 

### ISSUE THREAD

**Issue by ktnishide** [larryaasen/upgrader#391]
Upgrader checkVersion is removed? what is the alternative? 

Upgrader version 9.0.0

thanks

**Comment by larryaasen** [comment]
I see checkVersion right here: https://github.com/larryaasen/upgrader/blob/76e31311b87c453cd4c230708e7bff2535932ad9/lib/src/upgrade_alert.dart#L134

**Comment by ktnishide** [comment]
Sorry, let me clarify.

We were using `upgrader.checkVersion()` to programmatically check and display alert when app return to foreground on Upgrader version 6.5.0 but now we realized the package implemented the feature.

Sorry for the misunderstanding.

**Comment by vladchuk** [comment]
I am still not quite clear on how to check version at will: `checkVersion()` is no longer on the `Upgrader`, but on AlertDialog state. What if I can't/don't want to inject the alert into my widget hierarchy?..

**Comment by vladchuk** [comment]
I ended up bastardizing ```UpgradeAlert``` as follows:

- make  ```UpgradeAlert``` a plain class (not a widget)
- conflate ```UpgradeAlertState``` with it, exposing ```checkVersion()```, etc.
- instantiate alert right after upgrader and use it as before (in v. 8.x.x)

All in all, this feels like a bad regression. Please consider bringing the original functionality back.
