### ISSUE TITLE
Please upgrade the package_info_plus dependency to the latest

### ISSUE THREAD

**Issue by jusuf-el** [larryaasen/upgrader#396]
I am not able to depend on the latest package_info_plus version in my project, since upgrader requires package_info_plus >=4.0.1 <6.0.0.

Here is the complete error message I get when trying to pub get:
```
Because upgrader 10.0.0 depends on package_info_plus >=4.0.1 <6.0.0 and no versions of upgrader match >10.0.0 <11.0.0, upgrader ^10.0.0 requires package_info_plus >=4.0.1 <6.0.0.
So, because <MY_PROJECT_NAME> depends on both package_info_plus ^6.0.0 and upgrader ^10.0.0, version solving failed.


You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on package_info_plus: flutter pub add package_info_plus:^5.0.1
``` 

Thank you!

**Comment by larryaasen** [comment]
This was fixed in version [10.0.1](https://pub.dev/packages/upgrader/changelog#1001).

**Comment by michaelmairegger** [comment]
@jusuf-el same issue now with package_info_plus v7 which was released on monday

**Comment by orevial** [comment]
In the meantime you can use my fork mentionned in the PR above
