### ISSUE TITLE
Example to use the Appcast for Android

### ISSUE THREAD

**Issue by jasonlaw** [larryaasen/upgrader#4]
Hi @larryaasen ,

Do you mind add the Appcast for android implementation into your example? I have no idea how to start with that.

Thanks in advance.

**Comment by larryaasen** [comment]
@jasonlaw There is an Appcast file in the test folder: test/testappcast.xml

**Comment by jasonlaw** [comment]
Hi @larryaasen ,

Sorry for not being clear to you. What I mean is how to use the Appcast in the app.
Your 2 examples seems targeting for IOS.

![image](https://user-images.githubusercontent.com/107820/57202704-068dfb80-6fdb-11e9-9186-28e65234da37.png)

**Comment by larryaasen** [comment]
I see. I will setup an example that better explains how to use appcast on Android.

**Comment by larryaasen** [comment]
@jasonlaw I updated the examples with an Appcast for Android. It is now in version 0.5.1+1 of the package here: 822d52fc53a409e7be2c8085d05628f33f5e52f9

**Comment by aamirpadder** [comment]
Hey @larryaasen it's giving an error in the build

Compiler message:
/Users/macpc/Flutter/FlutterSDK/flutter/.pub-cache/hosted/pub.dartlang.org/upgrader-2.5.0/lib/src/appcast.dart:86:36: Error: Method not found: 'XmlDocument.parse'.
      final document = XmlDocument.parse(xmlString);

**Comment by larryaasen** [comment]
You need to make sure the xml package is updated to 4.2.x. Check your pubspec.lock file and see if the xml package version is 4.2.x. If not, use `flutter pub outdated` and `flutter pub upgrade` to get the compatible version of xml.
