### ISSUE TITLE
Tag for CriticalIssue should not pop the alert dialog

### ISSUE THREAD

**Issue by supposedlysam-bb** [larryaasen/upgrader#40]
When an item includes a critical issue tag in the RSS feed for android the alert dialog should not pop after pressing the "Update Now" button. 

If the user presses this button and goes back to the app without upgrading, they are no longer gated by the alert dialog (because it was popped).

Expected:
Alert dialog gates the user if they haven't upgraded.

Actual:
Alert dialog goes away after clicking the "Upgrade Now" button.

**Comment by larryaasen** [comment]
@supposedlysam-bb I created a PR that intends to prevent the dialog and card from being closed when in a blocked state. Please review this PR https://github.com/larryaasen/upgrader/pull/43 for me.
