### ISSUE TITLE
_updateVersionInfo doesn't pass in mocked client

### ISSUE THREAD

**Issue by supposedlysam-bb** [larryaasen/upgrader#41]
Mocking the rss feed for this package isn't currently possible without alteration to the `upgrader.dart` file. Although you can override the client on the `Upgrader` class, a new instance of the `Appcast` class is created inside of the `_updateVersionInfo` method. Since the `Upgrader`s `client` isn't passed into the `Appcast` constructor, a new `Client` is created and the mocked client is not used.

### Suggestion

Alter line 155 of the `upgrader.dart` from this:
```final appcast = Appcast();```
to this:
```final appcast = Appcast(client: client);```

**Comment by larryaasen** [comment]
@supposedlysam-bb That is a very good suggestion. Update coming soon.

**Comment by larryaasen** [comment]
https://github.com/larryaasen/upgrader/commit/e6cc93add7affb4b636898166963caf822d4b33a has been committed and released in version 2.2.1.
