### ISSUE TITLE
Add privacy manifest file for iOS

### ISSUE THREAD

**Issue by FaiazRahman100** [larryaasen/upgrader#411]
# Feature Request

You need to add PrivacyInfo.xcprivacy file following the new apple policy.

Describe the feature
Refer link: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files

Platforms affected
✅ 📱 iOS

**Comment by larryaasen** [comment]
@FaiazRahman100 Did the upgrader package get flagged by Apple? If so, can you show the rejection text here for review?

**Comment by carlo-prodigys** [comment]
Hi, the message is:

TMS-91061: Missing privacy manifest - Your app includes “Frameworks/device_info_plus.framework/device_info_plus”, which includes device_info_plus, an SDK that was identified in the documentation as a privacy-impacting third-party SDK. Starting November 12, 2024, if a new app includes a privacy-impacting SDK, or an app update adds a new privacy-impacting SDK, the SDK must include a privacy manifest file. Please contact the provider of the SDK that includes this file to get an updated SDK version with a privacy manifest. For more details about this policy, including a list of SDKs that are required to include signatures and manifests, visit: https://developer.apple.com/support/third-party-SDK-requirements.

How we can solve this?

**Comment by larryaasen** [comment]
The upgrader package does not contain any iOS code and thus would never need a privacy manifest. Perhaps other dependencies need one.

**Comment by carlo-prodigys** [comment]
The problem is with the dependency package_info_plus: '>=4.0.1 <9.0.0'
The version should be at least "10.0.1"

**Comment by larryaasen** [comment]
The latest version for package_info_plus is 8.0.2.
https://pub.dev/packages/package_info_plus

**Comment by jdve** [comment]
package_info_plus version 8.0.3 is now out which fixes this issue.

**Comment by jdve** [comment]
device_info_plus 11.0.0 is also out now which also includes the same fix. However, because pubspec explicitly requires a version less than 11.0.0, it's not getting picked up. This is related to https://github.com/larryaasen/upgrader/issues/459.

**Comment by larryaasen** [comment]
This is not a valid issue.
