### ISSUE TITLE
Pressing Upgrade doesn't open link.

### ISSUE THREAD

**Issue by Kontrano** [larryaasen/upgrader#412]
I encountered an issue where pressing the upgrade button doesn't open the link, I do get an error from UrlLauncher while doing so so maybe something needs to be updated in this package but I'm not sure. In this case, the link works fine on its own, I have included the error message below

```
I/UrlLauncher(11119): component name for https://play.google.com/store/apps/details?id=com.johankleijnit.eventvault&gl=US&hl=en&_cb=1714729902666612 is null
I/UrlLauncher(11119): component name for https://flutter.dev is null
```

The 2 dependencies 
```

upgrader: ^10.3.0
url_launcher: ^6.2.6
```

Does anyone have any ideas?

**Comment by PedroHenrique-42** [comment]
Same problem here

**Comment by Kontrano** [comment]
@PedroHenrique-42  Can confirm. it does work on a physical device. Very strange

**Comment by larryaasen** [comment]
@Kontrano When you copy that link to the emulator browser and enter it, does it open the Play Store?

**Comment by miraquel** [comment]
I think I have the same problem, instead of opening a new issue, I will add more information in here.

I am using physical device and using AppCast. I want to redirect to the landing page of the update when the user tap the Update Now button.

here is the XML of the AppCast

```
<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0">
  <channel xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle">
    <title>AXFinMobile</title>
    <description />
    <item>
      <title>Version 1.1.2</title>
      <description>Update fix for idempotency key</description>
      <pubDate>Wed, 29 May 2024 00:00:00 +0700</pubDate>
      <enclosure sparkle:version="1.1.2" sparkle:os="android" url="https://www.google.com/" />
    </item>
    <item>
      <title>Version 1.1.1</title>
      <description>update feature add invoice line indicator</description>
      <pubDate>Mon, 27 May 2024 00:00:00 +0700</pubDate>
      <enclosure sparkle:version="1.1.1" sparkle:os="android" url="https://www.google.com/" />
    </item>
    <item>
      <title>Version 1.1.3</title>
      <description>update test upgrader</description>
      <pubDate>Thu, 30 May 2024 00:00:00 +0700</pubDate>
      <enclosure sparkle:version="1.1.3" sparkle:os="android" url="https://www.google.com/" />
    </item>
  </channel>
</rss>
```

and here are the logs when the user tap the Update Now button.

```
I/UrlLauncher(11833): component name for https://www.google.com/ is null
I/UrlLauncher(11833): component name for https://flutter.dev is null
```

**Comment by larryaasen** [comment]
I added this to my AndroidManifest.xml file and it solved this issue. Add this at the bottom of the file just above the closing `</manifest>` tag.
```
    <queries>
      <intent>
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data android:scheme="https" />
      </intent>
    </queries>
```

**Comment by Kontrano** [comment]
> @Kontrano When you copy that link to the emulator browser and enter it, does it open the Play Store?

Hi sorry for the late response, I missed the email but yes link works perfectly fine on its own

**Comment by miraquel** [comment]
Hi @larryaasen,

Thank you for the solution, I can confirm the Update Now button is now working after I added the `<queries>` tag in the "AndroidManifest.xml" file.

**Comment by larryaasen** [comment]
@miraquel  I am going to add this to the README. Does this make sense?

> **Tapping UPDATE NOW button issue on Android**
> 
> Seeing an error similar to this on Android after tapping the UPDATE NOW button?
> 
> ```
> I/UrlLauncher(11833): component name for https://www.google.com/ is null
> ```
> 
> Adding this to the AndroidManifest.xml file will solve this issue. Add this at the bottom of the file just above the closing </manifest> tag.
> 
>     <queries>
>       <intent>
>         <action android:name="android.intent.action.VIEW" />
>         <category android:name="android.intent.category.BROWSABLE" />
>         <data android:scheme="https" />
>       </intent>
>     </queries>
> This was taken from this Android documentation: https://developer.android.com/training/package-visibility/use-cases#check-browser-available
