### ISSUE TITLE
auto_route support

### ISSUE THREAD

**Issue by alfie-tribaco** [larryaasen/upgrader#430]
In the documentation only go_router is supported. I can't see any auto_route example or documentation about it or am I missing something? 

My goal is to push a page using auto_route when there is no update available under UpgradeAlert Widget. Is upgrader supported auto_route package?

**Comment by alfie-tribaco** [comment]
Closing this issue, I already figured it out

**Comment by manandharsudhir** [comment]
@alfie-tribaco  could you specify what did you figure?

**Comment by alkaitagi** [comment]
@manandharsudhir to make the updater dialogue work with Auto Route, simply use the `navigatorKey` property from your `AppRouter` object:

```dart
final appRouter = AppRouter();
...

MaterialApp.router(
  builder: (context, child) {
    return UpgradeAlert(
      navigatorKey: appRouter.navigatorKey, // <--
      child: child,
    );
  },
  routerConfig: appRouter.config(
  ...
```
