### ISSUE TITLE
How to hide Ignore and Later Button? I am Using the Latest Version of Upgrader.Its seems like these showIgnore: false, // Hide the "Ignore" button           showLater: false, functions are depreciated

### ISSUE THREAD

**Issue by DeepakYiron** [larryaasen/upgrader#442]
Please suggest me how to hide these button , i just want to use this package for Force to Update app, so that user can not dismiss this dialog at any case.

**Comment by larryaasen** [comment]
@DeepakYiron Did you solve your issue?

**Comment by DeepakYiron** [comment]
Yes @larryaasen , Its working perfectly.
Thank you.
