### ISSUE TITLE
_appStoreVersion & _installedVersion always null at the First Time app running

### ISSUE THREAD

**Issue by taufiqtab** [larryaasen/upgrader#46]
when isUpdateAvailable() called at the first time app running, 
_appStoreVersion & _installedVersion always null, so the dialog will not show,

in my case, i put UpgradeAlert as a child of scaffold in my Home view,.
when application run, and load the home view, i debug the _appStoreVersion & _installedVersion always null
but, when i switch to other page in my app, and back to Home, the _appStoreVersion & _installedVersion filled, and the Popup Alert show..

how to solve this ?

**Comment by larryaasen** [comment]
Does the example app in example/lib/main.dart work for you? Android or iOS? What is your app bundle id?

**Comment by taufiqtab** [comment]
> Does the example app in example/lib/main.dart work for you? Android or iOS? What is your app bundle id?

i got this problem in Android build using Appcast xml and put it on website,. i'll try the example/lib/main.dart soon, and report it here

**Comment by larryaasen** [comment]
Did it work?

**Comment by larryaasen** [comment]
Closing this as a stale issue. If you see it now, please open a new one. Thanks.
