### ISSUE TITLE
First timer facing XML Document issue

### ISSUE THREAD

**Issue by mystarhub** [larryaasen/upgrader#47]
Hello there!

I am new to this package and tried installing upgrader 2.4.0 following the tutorial, but got the following error after "Flutter Run": 

Compiler message:
../../sdk/flutter/.pub-cache/hosted/pub.dartlang.org/upgrader-2.4.0/lib/src/appcas
t.dart:86:36: Error: Method not found: 'XmlDocument.parse'.
      final document = XmlDocument.parse(xmlString);                    
                                   ^^^^^                   

Could you kindly guide me in the right direction?

Thanks for your contribution!

**Comment by larryaasen** [comment]
Which version of Flutter are you using?

**Comment by larryaasen** [comment]
Are you sure the command `flutter pub get` completed properly?

**Comment by mystarhub** [comment]
Yes, I ran the pub get both in VS Code and also in terminal and both were successful.
If it helps, the error comes on the moment i add "import 'package:upgrader/upgrader.dart';" to my dart file.

**Comment by gustavobrian** [comment]
hi, solutions?

**Comment by stevenspiel** [comment]
I'm also getting this. 

Flutter 1.20.1
Upgrader 2.4.0

**Comment by larryaasen** [comment]
Sorry for this XML issue. I'm sure it is related to this change in 2.4.0:
_Updated the Appcast class to support a newer version of the Xml package._
I'm working on a fix.

**Comment by larryaasen** [comment]
The example works for me and I am using:

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.0, on Mac OS X 10.15.5 19F101, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.47.1)
[✓] Connected device (2 available)

• No issues found!

```
In my pubspec.lock file, I see version 4.2.0 for xml:
```
  xml:
    dependency: transitive
    description:
      name: xml
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.2.0"
```
What version of xml do you have in your pubspec.lock file?

**Comment by bereanu99** [comment]
The same issue here    
upgrader: ^2.1.0 to    upgrader: ^2.4.0 
Flutter version 1.17.0-4.0.pre.9

**Comment by sinanfarokm** [comment]
Hi dude
Just upgrade your flutter to latest stable version and do a **pub get**, then everything will work

**Comment by nguyenhuutinh** [comment]
downgrade to 2.1.0 first

**Comment by larryaasen** [comment]
Using upgrader 2.5.0 and xml 4.2.0 will work with Flutter 1.20.0.

**Comment by larryaasen** [comment]
@bereanu99 @stevenspiel @mystarhub Any more issues?

**Comment by larryaasen** [comment]
Closing this as a stale issue. If you see it now, please open a new one. Thanks.

**Comment by abdulrojak288** [comment]
> Menggunakan upgrader 2.5.0 dan xml 4.2.x akan bekerja dengan Flutter 1.20.x.

I'm using flutter channel master and upgrader: ^ 2.7.3 has the same problem. do you have a solution?

**Comment by larryaasen** [comment]
@abdulrojak288 What errors do you see?

**Comment by fzyzcjy** [comment]
This works for me with latest flutter
```
  upgrader: ^2.7.3
  xml: ^4.5.1
```

**Comment by larryaasen** [comment]
@fzyzcjy Glad it works. Which flutter channel?

**Comment by fzyzcjy** [comment]
@fzyzcjy stable

**Comment by tj4702** [comment]
my error is that I am using upgrader for the automatic update of play store and I cannot delete the import but I am still getting the same issue. 
Thank you for your  help.
