### ISSUE TITLE
Initial Setup

### ISSUE THREAD

**Issue by sinanfarokm** [larryaasen/upgrader#50]
I want to use this lib in my app
could you please tell me the steps?
should I need change anything in xCode runner?
where should i add or change versions?
I recieved this error: **upgrader.ITunesResults.version: RangeError (index): Invalid value: Valid value range is empty: 0**
and this: **upgrader.ITunesResults.trackViewUrl: RangeError (index): Invalid value: Valid value range is empty: 0**
I just wraped my **Splash Screen Widget** with **UpgradeAlert** widget.

**Comment by larryaasen** [comment]
Are you using version 2.5.0 of upgrader? Is your app published in the US App Store? What is the bundle id of your app?

**Comment by larryaasen** [comment]
Closing this as a stale issue. If you see it now, please open a new one. Thanks.
