### ISSUE TITLE
Debug Issue

### ISSUE THREAD

**Issue by dominhgiangbboy** [larryaasen/upgrader#53]
Hi,
Im currently developing an app using flutter with your library. With debug version the Upgrade Alert still not appear in my app even it printed out build UpgradeAlert in the debug console (my app bundle is already on app store with the version of 1.1.3 and my current xcode build version is 0.0.1). This is my code: 

`body: UpgradeAlert(
            debugLogging: true,
            debugDisplayOnce: true,
            debugAlwaysUpgrade: true,
            child: SizedBox.expand(
              child: PageView(
                controller: _pageController,
                onPageChanged: (index) {
                  setState(() => _currentIndex = index);
                },
                children: buildListContentPageView(context),
              ),
            ),
          ),`
and this is my debug console result:
![Screenshot 2020-08-21 at 12 59 55](https://user-images.githubusercontent.com/50373183/90857370-36b70480-e3ae-11ea-8963-ba87abfe55f4.png)
Is it not working with non-realease version if it does how can i debug it and use it in my code? 
Thanks for your support.
Edit 1: Im using upgrader version 2.2.0 due to version coflict with xml version.

**Comment by larryaasen** [comment]
@dominhgiangbboy The country code detected was: `VN`. Is that the country code where the app is located in the App Store?

**Comment by larryaasen** [comment]
Try the latest version 2.7.2 and see if that works.
