### ISSUE TITLE
Dismiss on press back button android

### ISSUE THREAD

**Issue by malvinpratama** [larryaasen/upgrader#54]
can you add parameter for dismiss on press back button?
canDismissDialog is parameter for tap outside alert dialog but if use android we also can dismiss dialog with back button

**Comment by larryaasen** [comment]
This PR https://github.com/larryaasen/upgrader/pull/58 was created to address this enhancement.

**Comment by Ruqoyah549** [comment]
Has this been fixed yet

**Comment by bean5** [comment]
@Ruqoyah549 #58 is still open. I do not think this if fixed.

**Comment by bean5** [comment]
@Ruqoyah549 It is the only pull request present, so perhaps it will be fixed soon.

@AbdOoSaed do you have timeline on this?

**Comment by AbdOoSaed** [comment]
@bean5 
I think I fixed it since 6 months 
look to my fork with this commit
https://github.com/AbdOoSaed/upgrader/tree/c455f1ca351bf1e4f0680ce2274185802f1a6b49

**Comment by malvinpratama** [comment]
@larryaasen can you check for this pr #58 ?
@AbdOoSaed say this has been fixed since 6 months

**Comment by Basher7** [comment]
Including @AbdOoSaed modification I add few extra line.

By this fork you can disable Android device back button by setting ```disableBackButton=true```
Also, For critical update set below line in your xml file

> ```<sparkle:tags><sparkle:criticalUpdate/></sparkle:tags>```

this will hide ```IGNORE``` and ```LATER``` button. Also set ```canDismissDialog=false``` and ```disableBackButton=true```. By this user must be update application if he want to use it.

> N.B: this functionality works only for UpgraderAlert

**Comment by AbdOoSaed** [comment]
@Basher7 
Good features 
but why u made as I made since 8 months
"remove extension and add a wrapper class"
I made this change because the package was not supported extensions at the time
but now I think  it supports extensions

**Comment by malvinpratama** [comment]
@larryaasen so when we can release this feature?
do you have check that?

**Comment by larryaasen** [comment]
PR https://github.com/larryaasen/upgrader/pull/106 should address this issue.
When using the ```UpgradeAlert``` widget, the Android back button will not dismiss the alert dialog by default anymore. To allow the back button to dismiss the dialog, use ```shouldPopScope``` and return true.

**Comment by Basher7** [comment]
@larryaasen please upgrade all pubspec.yaml packages to latest version in next release.

**Comment by larryaasen** [comment]
@Basher7 Is there a problem?

<img width="762" alt="Screen Shot 2021-05-17 at 7 39 52 AM" src="https://user-images.githubusercontent.com/325973/118482733-22a4f700-b6e3-11eb-8c70-939f92a43b97.png">

**Comment by Basher7** [comment]
@larryaasen  For current version, no issue in package related. In future, if throw any dependency error, That's why I request keep packages at latest version. Nothing else.

Thank you for your effort and sorry for bother you.
