### ISSUE TITLE
Publish to AppStore

### ISSUE THREAD

**Issue by sinanfarokm** [larryaasen/upgrader#56]
I used this useful pub, and now i want to publish my app to the appstore,
is there any setting that i should do before publish
for example I think I should add notification to my app id in app store pannel
could you please guide me about this issue?

**Comment by larryaasen** [comment]
Once this package is correctly integrated into your app, you do not need to do anything else for iOS. For Android, if you are using the Appcast file, you will need to make sure it contains the latest app version in the store.
In your question `notification to my app id in app store pannel`, I did not understand that part. Can you explain more about that?

**Comment by sinanfarokm** [comment]
thanks @larryaasen 
I uploaded my app to appstroe, they said that I'm using push notification in my app, but I didn't
the only library I used is uploader, so I think this library needs push notification service to be enabled in app store connect page, is that true?
and this is the message I recieved from AppStore reviewer team.

ITMS-90078: Missing Push Notification Entitlement - Your app appears to register with the Apple Push Notification service, but the app signature's entitlements do not include the 'aps-environment' entitlement. If your app uses the Apple Push Notification service, make sure your App ID is enabled for Push Notification in the Provisioning Portal, and resubmit after signing your app with a Distribution provisioning profile that includes the 'aps-environment' entitlement. Xcode does not automatically copy the aps-environment entitlement from provisioning profiles at build time. This behavior is intentional. To use this entitlement, either enable Push Notifications in the project editor's Capabilities pane, or manually add the entitlement to your entitlements file.

**Comment by larryaasen** [comment]
The upgrader package does not use push notifications. You can inspect the folder for this package and see the contents to ensure that it does not contain any native code. There may be other Flutter packages included that require the use of notifications. If you post your pubspec.lock file here, we can inspect it.

**Comment by sinanfarokm** [comment]
Sure
this is the link on [google drive](https://drive.google.com/file/d/1Qd7qHi_2HMQ4pJ4-Xm1fm1bi7Ks0Z8Wn/view?usp=sharing)

**Comment by larryaasen** [comment]
I looked at the long list of packages listed in the pubspec.lock file you posted on Google Drive and I don't see any packages that obviously use notifications. With that said, I know that upgrader does not use notifications. I don't see how the upgrade package could have caused this issue: _Missing Push Notification Entitlement_.

Can I close this issue now?
