### ISSUE TITLE
bug help  systemName":"iOS","systemVersion":"13.6.1","utsname.machine:":"iPhone11,2", AND systemName":"iOS","systemVersion":"13.6","utsname.machine:":"iPhone12,1","

### ISSUE THREAD

**Issue by gustavobrian** [larryaasen/upgrader#57]
MESSAGE:#0      _StringBase.replaceAll (dart:core-patch/string_patch.dart:637)
#1      Upgrader.message (package:upgrader/src/upgrader.dart:248)
#2      Upgrader.checkVersion.<anonymous closure> (package:upgrader/src/upgrader.dart:264)
#3      new Future.delayed.<anonymous closure> (dart:async/future.dart:325)
#4      _rootRun (dart:async/zone.dart:1182)
#5      _CustomZone.run (dart:async/zone.dart:1093)
#6      _CustomZone.runGuarded (dart:async/zone.dart:997)
#7      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037)
#8      _rootRun (dart:async/zone.dart:1190)
#9      _CustomZone.run (dart:async/zone.dart:1093)
#10     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021)
#11     SemanticsConfiguration._addArgumentlessAction.<anonymous closure> (package:flutter/src/semantics/semantics.dart:2847)
#12     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397)
#13     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168)

**Comment by larryaasen** [comment]
I don't have enough details to help you. What version of upgrader are you using?

**Comment by larryaasen** [comment]
Try version 2.7.2 and see if that works for you.
