### ISSUE TITLE
Parse data?

### ISSUE THREAD

**Issue by amandhiraj** [larryaasen/upgrader#59]
![image](https://user-images.githubusercontent.com/40723562/92990087-165b0100-f4a7-11ea-970e-3fc6e7c878b2.png)
How can we parse this data?

I was to check if the bool value of `isUpdateAvailable`

If `true` then open updater card 
if `false` open main page

**Comment by larryaasen** [comment]
@amandhiraj This might work, although I have not tried it.
```
Upgrader().initialize().then((value) {
  if (Upgrader().shouldDisplayUpgrade()) {
    return UpgradeCard();
  } else {
    return MainPage();
  }
});
```
