### ISSUE TITLE
Method not found XmlDocument.parseString(xmlString) 

### ISSUE THREAD

**Issue by Mashood97** [larryaasen/upgrader#61]
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/upgrader-2.6.0/lib/src/appcast.dart:86:36: Error: Method not found: 'XmlDocument.parse'. final document = XmlDocument.parse(xmlString);

**Comment by larryaasen** [comment]
Are you using version 4.2.0+ for the xml package?
