### ISSUE TITLE
The alert is not shown on iOS

### ISSUE THREAD

**Issue by zjamshidi** [larryaasen/upgrader#67]
I'm using the latest version and have integrated UpgradeAlert to my home screen:
```
UpgradeAlert(
      debugLogging: true,
      minAppVersion: leastIosVersion,
      child: _buildBody(),
    )
```

when the app version is lower than minAppVersion, the alert is shown and the update is forced.
when the app is higher than minAppVersion, despite I see an update is available in logs, the alert is not shown:

```
flutter: upgrader: package info packageName: com.xxx.app
flutter: upgrader: package info version: 0.00.30
flutter: upgrader: countryCode: MY
 flutter: upgrader: appStoreVersion: 0.00.50
flutter: upgrader: installedVersion: 0.00.30
 flutter: upgrader: isUpdateAvailable: true
```

**Comment by zjamshidi** [comment]
Is this bug fixed in the new versions? If no, do you have any ETA?

**Comment by larryaasen** [comment]
@zjamshidi I was not able to reproduce this issue you stated above. I did not know the `minAppVersion` you had used, so I used 0.00.20 and the alert was displayed. I tested this by using the `example/main.dart` file and forcing `appStoreVersion` to be `0.00.50`. Do you have any other details I could use to reproduce this issue? Here is my log.
```
flutter: upgrader: build UpgradeAlert
flutter: upgrader: package info packageName: com.google.maps
flutter: upgrader: package info version: 0.00.30
flutter: upgrader: countryCode: US
flutter: upgrader: blocked: false
flutter: upgrader: debugDisplayAlways: false
flutter: upgrader: debugDisplayOnce: false
flutter: upgrader: hasAlerted: false
flutter: upgrader: appStoreVersion: 0.00.50
flutter: upgrader: installedVersion: 0.00.30
flutter: upgrader: minAppVersion: 0.00.20
flutter: upgrader: isUpdateAvailable: true
flutter: upgrader: shouldDisplayUpgrade: true
flutter: upgrader: showDialog title: Update App?
flutter: upgrader: showDialog message: A new version of Upgrader is available! Version 0.00.50 is now available-you have 0.00.30.
```

**Comment by larryaasen** [comment]
@zjamshidi I published a new version (2.7.1) of this package with extra debug logging to help you with this issue. Check [it out](https://pub.dev/packages/upgrader/changelog).

**Comment by zjamshidi** [comment]
Thanks @larryaasen, I will check the recent version today or tomorrow and let you know.

**Comment by zjamshidi** [comment]
The recent version is working fine. It might be a false alarm or bug fixed.
