### ISSUE TITLE
Alert style

### ISSUE THREAD

**Issue by ShengjieGeng** [larryaasen/upgrader#68]
Hi, Is there a style of iOS alert?
![image](https://user-images.githubusercontent.com/18364968/98102928-33241b80-1ecf-11eb-8385-fbf7ac7da9a3.png)

**Comment by larryaasen** [comment]
I just implemented a Cupertino style dialog alert in this package, and publish it in version 2.7.0. There is a new parameter dialogStyle that can be set to UpgradeDialogStyle.cupertino. Download the updated [Flutter package](https://pub.dev/packages/upgrader) and try it out.
