### ISSUE TITLE
I still don't know to use it

### ISSUE THREAD

**Issue by rickyreza12** [larryaasen/upgrader#70]
I still don't know to use it after i take it on Upgrade alert, it's just shown "checking"'
here is the isues on my problem 
https://stackoverflow.com/questions/64916505/how-to-use-upgrader-plugin-on-flutter

**Comment by larryaasen** [comment]
I put an answer on [StackOverflow](https://stackoverflow.com/a/64929702/1490196), but will also post that answer here.

To use upgrader on Android, you must setup an Appcast file and provide the configuration. Here is an example Appcast file you need to place on a server somewhere, such as GitHub. The Appcast file contains the details about the latest version of the app:

```
    <?xml version="1.0" encoding="utf-8"?>
    <rss version="2.0" xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle">
        <channel>
            <title>Debt Now App - Appcast</title>
            <item>
                <title>Version 1.15.0</title>
                <description>desc</description>
                <pubDate>Sun, 30 Dec 2018 12:00:00 +0000</pubDate>
                <enclosure url="https://play.google.com/store/apps/details?id=com.moonwink.treasury" sparkle:version="1.15.0" sparkle:os="android" />
            </item>
        </channel>
    </rss>

```
Here is a build method that will use the Appcast file on Android, and provide the AppcastConfiguration. This configuration will not apply to iOS, but iOS will continue to work.

```
      @override
      Widget build(BuildContext context) {
        final appcastURL =
            'https://raw.githubusercontent.com/larryaasen/upgrader/master/test/testappcast.xml';
        final cfg = AppcastConfiguration(url: appcastURL, supportedOS: ['android']);
    
        return MaterialApp(
          title: 'Upgrader Example',
          home: Scaffold(
              appBar: AppBar(
                title: Text('Upgrader Example'),
              ),
              body: UpgradeAlert(
                appcastConfig: cfg,
                child: Center(child: Text('Checking...')),
              )),
        );
      }
```

**Comment by larryaasen** [comment]
@rickyreza12 Are you still having issues?

**Comment by rickyreza12** [comment]
sorry for not tagged my question with solved issue, i can use it now, thank
you
