### ISSUE TITLE
is minAppVersion compulsary?

### ISSUE THREAD

**Issue by xylim666** [larryaasen/upgrader#72]
If i didn't set minAppVersion, will the updater ask to update?
Currently i didn't pass this and the updater is not working.
Any workaround or is this intended behavior?

**Comment by larryaasen** [comment]
Setting `minAppVersion` is not required for upgrader to work. Do you have any other details you can provide, such as a log?

**Comment by xylim666** [comment]
Sorry i figured my issue already. It's because i clicked anywhere behind the card to dismiss it and it won't pop out again any more. Once i changed daysToAlertAgain to 0 then it appear again.
