### ISSUE TITLE
Compilation Error in latest version 2.7.3

### ISSUE THREAD

**Issue by dineshsheoran24** [larryaasen/upgrader#73]
../../flutter/.pub-cache/hosted/pub.dartlang.org/upgrader-2.7.3/lib/src/appcast.dart:86:36: Error: Method not found: 'XmlDocument.parse'.
      final document = XmlDocument.parse(xmlString);

**Comment by larryaasen** [comment]
What version of the `xml` package are you using? My pubspec.lock file has version `4.5.1`.

**Comment by jonathangull** [comment]
@larryaasen I got same error when using 2.7.3 , my pubspec.lock file shows xml version as 3.6.1. The error went away when I downgraded upgraded package to 2.2.0. Could you please advise how can I use latest version of 2.7.3 ? do I have to add xml package to pub spec.yaml to 4.5.1 (will it break other things?)

**Comment by larryaasen** [comment]
@jonathangull Is there any reason you cannot upgrade your `xml` package to a later version? Maybe run `flutter pub outdated` and see if that helps you upgrade some of your packages.

**Comment by jonathangull** [comment]
@larryaasen Thank you I am able to use latest version of upgrader after I upgraded my xml package. Can you unblock me ? I am stuck when using upgrader package, below is relevant code and questions I have - 
 
1. when I don't have debugAlwaysUpgrade = true , alert box never shows. is this mandatory for alert box to show?
2. I set onUpdate: to true, but my log shows following lines

I/flutter ( 3873): upgrader: blocked: false
I/flutter ( 3873): upgrader: debugDisplayAlways: true
I/flutter ( 3873): upgrader: debugDisplayOnce: false
I/flutter ( 3873): upgrader: hasAlerted: true
I/flutter ( 3873): upgrader: shouldDisplayUpgrade: true
I/flutter ( 3873): upgrader: build UpgradeAlert
I/flutter ( 3873): upgrader: showDialog title: Update App?
I/flutter ( 3873): upgrader: showDialog message: A new version of MarketSetu Seller is available! Version  is now available-you have 1.0.1.
I/flutter ( 3873): upgrader: button tapped: update now
I/flutter ( 3873): upgrader: empty _appStoreListingURL


Do I have to use url_launcher and implement a method to take me to playstore or upgrader will. handle that? why is _appStoreListingURL is coming empty? I have that in my app cast xml. Kindly advise me.

My code

 Widget build(BuildContext context) {
    final appcastURL =
        'https://drive.google.com/file/d/XXX/view?usp=sharing';
    final cfg = AppcastConfiguration(url: appcastURL, supportedOS: ['android']);

 body: UpgradeAlert(
          debugAlwaysUpgrade: true,
          showIgnore: true,
          showLater: true,
          appcastConfig: cfg,
          debugLogging: true,
          onUpdate: () => true,
          child: Padding(

**Comment by larryaasen** [comment]
I see in the log that `hasAlerted: true` which means that it has already been displayed, and will not be displayed again until

**Comment by larryaasen** [comment]
@jonathangull 
1. You do not need to have `debugAlwaysUpgrade` set to `true`. That is just for debugging. It should normally be `false`.
2. You do not need to set onUpdate. Do you need to see that?
3. What does your appcast file look like? Does it have a line like this:
`<enclosure url="https://play.google.com/store/apps/details?id=com.moonwink.treasury" sparkle:version="1.15.0" sparkle:os="android" />`
