### ISSUE TITLE
appName not showing on iOS but shows on Android

### ISSUE THREAD

**Issue by Ruqoyah549** [larryaasen/upgrader#75]

**Comment by larryaasen** [comment]
Can you share a portion of your code so it can be reviewed? Also, can you provide the upgrader log?

**Comment by MaximeDelhorme** [comment]
I think I have a similar issue when trying to test on iOS.

Here is the code:
final appcastURL = '';
final cfg = AppcastConfiguration(url: appcastURL, supportedOS: ['ios']);

...
child:Scaffold(
          backgroundColor: Colors.transparent,
          body: UpgradeAlert(
            appcastConfig: cfg,
            debugLogging: true,
            debugAlwaysUpgrade: true,
            showIgnore: false,
            showLater: false,
            canDismissDialog: false,
            minAppVersion: "1.0.1",
            child: ...
))

Here is the log (removed the private infos)
flutter: upgrader: build UpgradeAlert
flutter: upgrader: package info packageName: com.****.****
flutter: upgrader: package info version: *.*.*
flutter: upgrader: countryCode: **
flutter: upgrader: build UpgradeAlert
flutter: ----------------FIREBASE CRASHLYTICS----------------
flutter: Invalid argument(s) (replacement): Must not be null
flutter: 
#0      _StringBase.replaceAll (dart:core-patch/string_patch.dart:637:30)
#1      Upgrader.message (package:upgrader/src/upgrader.dart:248:15)
#2      Upgrader.checkVersion.<anonymous closure> (package:upgrader/src/upgrader.dart:264:24)
#3      new Future.delayed.<anonymous closure> (dart:async/future.dart:326:39)
#4      _rootRun (dart:async/zone.dart:1182:47)
#5      _CustomZone.run (dart:async/zone.dart:1093:19)
#6      _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#7      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#8      _rootRun (dart:async/zone.dart:1190:13)
#9      _CustomZone.run (dart:async/zone.dart:1093:19)
#10     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021:23)
#11     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#12     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
#13     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

Any idea?

**Comment by MaximeDelhorme** [comment]
I have the same issue. All app related info are not shown on ios:
<img width="222" alt="Screenshot 2020-12-05 at 15 52 06" src="https://user-images.githubusercontent.com/17178134/101246246-5d593b00-3712-11eb-94b3-a64ea30e3393.png">

Code:
Upgrader().clearSavedSettings();


    // On iOS, the default behavior will be to use the App Store version of
    // the app, so update the Bundle Identifier in example/ios/Runner with a
    // valid identifier already in the App Store.
    final appcastURL = '';
    final cfg = AppcastConfiguration(url: appcastURL, supportedOS: ['ios']);

    return Container(
      child: Scaffold(
          backgroundColor: Colors.transparent,
          body: UpgradeAlert(
            appcastConfig: cfg,
            debugLogging: false,
            showIgnore: false,
            showLater: false,
            canDismissDialog: false,
            debugAlwaysUpgrade: true,
            dialogStyle: UpgradeDialogStyle.cupertino,
            child: ...
            minAppVersion: '1.0.0',
          )),
    );
  }

**Comment by larryaasen** [comment]
@MaximeDelhorme Your AppcastConfiguration is only supporting iOS and not Android. Normally, iOS does not need to use AppcastConfiguration. Did you intend that for Android? Can you post your Appcast file here for review?

**Comment by MaximeDelhorme** [comment]
@larryaasen I intend to use another library for Android. Therefore I didn't create an appcast. Is that where the problem comes from?

**Comment by larryaasen** [comment]
@MaximeDelhorme You don't need the Appcast for iOS, normally. Here is the example without an Appcast:
```
import 'package:flutter/material.dart';
import 'package:upgrader/upgrader.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  MyApp({
    Key key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Upgrader Example',
      home: Scaffold(
          appBar: AppBar(
            title: Text('Upgrader Example'),
          ),
          body: UpgradeAlert(
            child: Center(child: Text('Checking...')),
          )
      ),
    );
  }
}
```

**Comment by MaximeDelhorme** [comment]
My app structure is a bit more complex than the example you're providing, but I tried to move the hierarchy at which the UpgradeAlert widget is called. Nevertheless, I always end up with the same error. Any idea where it could originate?

**Comment by larryaasen** [comment]
@MaximeDelhorme Did you remove the ios appcast?

**Comment by MaximeDelhorme** [comment]
I did. Current code is:
body: UpgradeAlert(
            debugLogging: false,
            showIgnore: false,
            showLater: false,
            canDismissDialog: false,
            dialogStyle: UpgradeDialogStyle.cupertino,
            minAppVersion: '1.0.0',
           child: ...
)

**Comment by larryaasen** [comment]
@MaximeDelhorme I'm not sure what's going on here. Can you send the log using the latest code changes?

**Comment by MaximeDelhorme** [comment]
Here it is:

flutter: upgrader: build UpgradeAlert
flutter: upgrader: package info packageName: ...
flutter: upgrader: package info version: 1.0.0
flutter: upgrader: countryCode: US
flutter: upgrader: build UpgradeAlert
flutter: FormatException: Cannot parse empty string into version
flutter: upgrader: blocked: false
flutter: upgrader: debugDisplayAlways: true
flutter: upgrader: debugDisplayOnce: false
flutter: upgrader: hasAlerted: false
flutter: upgrader: shouldDisplayUpgrade: true
flutter: upgrader: showDialog title: Update App?
flutter: upgrader: showDialog message: A new version of  is available! Version  is now available-you have .

**Comment by MaximeDelhorme** [comment]
Would it help if I give you the list of packages and versions I use?

**Comment by larryaasen** [comment]
@MaximeDelhorme  If you are using the latest version of upgrader, version 2.7.3, you should see these additional log statements:
```
flutter: upgrader: appStoreVersion: 5.58
flutter: upgrader: installedVersion: 1.0
flutter: upgrader: minAppVersion: 1.0.0
flutter: upgrader: isUpdateAvailable: true

```
What version are you using?
Your package info packageName is `...` which seems wrong. Did you hide that or is that a problem?

**Comment by MaximeDelhorme** [comment]
I am using 2.7.3. And indeed I just hide my packageName, it appears normally in the logs.

**Comment by larryaasen** [comment]
In your log I expect to see the app name like this, but I don't see it:
```
flutter: upgrader: packageinfo appName: Upgrader
```
That is the same value that should be displayed in the log like this:
```
flutter: upgrader: showDialog message: A new version of Upgrader is available! Version 5.58 is now available-you have 1.0.
```
In your log I see this:
```
flutter: upgrader: showDialog message: A new version of is available! Version is now available-you have .
```
So, the app name is missing from that string, and {{appName}} is in the body template message. That may explain why you do not see the app name in the alert dialog.

Can you send me any more log or details that may help me understand why it is not working?

**Comment by MaximeDelhorme** [comment]
Just tested in production. It works like a charm! Strange these problems came up during development.
Thanks!

**Comment by larryaasen** [comment]
@MaximeDelhorme Glad it worked out.

**Comment by nhingo-312** [comment]
@larryaasen Hi, I've got the same issue but the appName still shows in message while the version number does not, the logcat shows no error and this issue only happens for every first time I run the app. Is it an error?
