### ISSUE TITLE
how to get appStoreVersion from upgrader or how to check dialog is showing or not ?

### ISSUE THREAD

**Issue by Bharavi26** [larryaasen/upgrader#79]
i want to stop some background method if there is update dialog, so i need some value for global variable that dialog is showing or not

**Comment by larryaasen** [comment]
At this time there is no easy way to determine if the dialog is showing. You could fork this repo and add that feature.

**Comment by larryaasen** [comment]
@Bharavi26 Look at the latest version of this package with a latest customization options. I think it now meets your needs. If not, please open a new issue with your details.
