### ISSUE TITLE
AVD is good！ MI9 phone  have problem！

### ISSUE THREAD

**Issue by 8108905** [larryaasen/upgrader#80]
Launching lib\main.dart on MI 9 in debug mode...
Running Gradle task 'assembleDebug'...
√ Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...
Waiting for MI 9 to report its views...
Debug service listening on ws://127.0.0.1:63904/-Bn0ctb66Yc=/ws
Syncing files to device MI 9...
I/flutter (19902): upgrader: build UpgradeAlert
I/flutter (19902): upgrader: package info packageName: com.example.flutter_appd
I/flutter (19902): upgrader: package info version: 1.0.0
I/flutter (19902): upgrader: appcast is available for this platform
I/le.flutter_app(19902): ProcessProfilingInfo new_methods=493 is saved saved_to_disk=1 resolve_classes_delay=8000
I/flutter (19902): upgrader: appcast item count: 4
I/flutter (19902): upgrader: appcast best item version: 5.0
I/flutter (19902): upgrader: blocked: true
I/flutter (19902): upgrader: debugDisplayAlways: false
I/flutter (19902): upgrader: debugDisplayOnce: false
I/flutter (19902): upgrader: hasAlerted: false
I/flutter (19902): upgrader: appStoreVersion: 5.0
I/flutter (19902): upgrader: installedVersion: 1.0.0
I/flutter (19902): upgrader: minAppVersion: 1.1.0
I/flutter (19902): upgrader: isUpdateAvailable: true
I/flutter (19902): upgrader: shouldDisplayUpgrade: true
E/flutter (19902): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: The method 'replaceAll' was called on null.
E/flutter (19902): Receiver: null
E/flutter (19902): Tried calling: replaceAll("{{appName}}", "flutter_appd")
E/flutter (19902): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
E/flutter (19902): #1      Upgrader.message (package:upgrader/src/upgrader.dart:258:15)
E/flutter (19902): #2      Upgrader.checkVersion.<anonymous closure> (package:upgrader/src/upgrader.dart:278:24)
E/flutter (19902): #3      new Future.delayed.<anonymous closure> (dart:async/future.dart:326:39)
E/flutter (19902): #4      _rootRun (dart:async/zone.dart:1182:47)
E/flutter (19902): #5      _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (19902): #6      _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (19902): #7      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (19902): #8      _rootRun (dart:async/zone.dart:1190:13)
E/flutter (19902): #9      _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (19902): #10     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021:23)
E/flutter (19902): #11     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
E/flutter (19902): #12     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
E/flutter (19902): #13     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
E/flutter (19902): #14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter (19902): 

--------------------------------------

AVD is good！ MI9 phone  have problem！

**Comment by 8108905** [comment]
import 'package:flutter/material.dart';
import 'package:upgrader/upgrader.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  MyApp({
    Key key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    // Only call clearSavedSettings() during testing to reset internal values.
    Upgrader().clearSavedSettings();

    // On Android, setup the Appcast.
    // On iOS, the default behavior will be to use the App Store version of
    // the app, so update the Bundle Identifier in example/ios/Runner with a
    // valid identifier already in the App Store.
    final appcastURL =
        'https://raw.githubusercontent.com/larryaasen/upgrader/master/test/testappcast.xml';
    final cfg = AppcastConfiguration(url: appcastURL, supportedOS: ['android']);

    return MaterialApp(
      title: 'Upgrader Example',
      home: Scaffold(
          appBar: AppBar(
            title: Text('Upgrader Example'),
          ),
          body: UpgradeAlert(
            appcastConfig: cfg,
            debugLogging: true,
            child: Center(child: Text('Checking...')),
          )),
    );
  }
}

**Comment by 8108905** [comment]
I use Android emulator is good;
when i  'flutter build apk' install my Android phone , display show 'Checking..' ,;

I don't know why ,

**Comment by 8108905** [comment]
Flutter 1.22.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7891006299 (4 weeks ago) • 2020-12-10 11:54:40 -0800
Engine • revision ae90085a84
Tools • Dart 2.10.4

**Comment by larryaasen** [comment]
This may be related to the problem mentioned in https://github.com/larryaasen/upgrader/issues/81. Please take a look at my comments there.

**Comment by larryaasen** [comment]
I just published version 2.8.2 with a fix for this problem. It now defaults to 'en' (English) when it detects an unknown language code.

**Comment by 8108905** [comment]
Think you!
