### ISSUE TITLE
How to use for another market except App Store or Google Play?

### ISSUE THREAD

**Issue by MojtabaTavakkoli** [larryaasen/upgrader#83]
Is there any way to use this package for non-app-store markets?

**Comment by larryaasen** [comment]
Yes, use the Appcast feature.
https://github.com/larryaasen/upgrader#appcast

**Comment by MojtabaTavakkoli** [comment]
Thanks for your response. Since I've got no experience in RSS files, is it possible for you to explain a little bit about the RSS you provided here? [https://raw.githubusercontent.com/larryaasen/upgrader/master/test/testappcast.xml](url)

I tried it in various ways like changing the versions of xml or rss but nothing happened. Should I add the application package name somewhere in that file?

Any help would be appreciated.
Thanks in advance.

**Comment by larryaasen** [comment]
Closed due to lack of activity. You can open a new issue if you have more questions.
