### ISSUE TITLE
Can you change xml format to json format api？

### ISSUE THREAD

**Issue by 8108905** [larryaasen/upgrader#84]
Since the mysql database cannot store xml, a complicated conversion is required!
Thinks！

**Comment by larryaasen** [comment]
The [Appcast](https://github.com/larryaasen/upgrader#appcast) file format is based on the one defined by [Sparkle](https://github.com/sparkle-project/Sparkle), which [does not support JSON](https://github.com/sparkle-project/Sparkle/issues/1080).

**Comment by 8108905** [comment]
Sorry! I just read the Appcast document carefully, it is better
