### ISSUE TITLE
How to add the list of 'new version features' in the dialog?

### ISSUE THREAD

**Issue by MojtabaTavakkoli** [larryaasen/upgrader#86]
Is it possible to add the list of new features released in the next update?  Something like the image below: 
![39094673-64c6fc40-462b-11e8-9ec2-76deef24e73e](https://user-images.githubusercontent.com/18093612/107140002-7067d180-6934-11eb-92e8-723a56be729c.png)

I've tried using the <description> tag in the RSS file and the appCast feature but I guess there is no receiver for it in the package or at least I cant find it. 
Thank you.

**Comment by larryaasen** [comment]
Including the release notes would be a nice enhancement. I have no plans to add that any time soon.

**Comment by larryaasen** [comment]
@MojtabaTavakkoli Look at the latest version of this package with a latest customization options. I think it now meets your needs. If not, please open a new issue with your details.
