### ISSUE TITLE
Update this library to Darts null safety

### ISSUE THREAD

**Issue by ueman** [larryaasen/upgrader#88]
The next stable release of Flutter is using most probably Darts new null safety feature.
Thus this library should be migrated.

Please see the following links for further information:
https://dart.dev/null-safety/migration-guide
https://medium.com/flutter/announcing-dart-null-safety-beta-4491da22077a

**Comment by NTMS2017** [comment]
👍🙏👏🏻

**Comment by larryaasen** [comment]
There will be a null safety version of this package available soon that should resolve this issue. It will let you know when it is available.

**Comment by swarupbhanjachowdhury** [comment]
@larryaasen thank you for this plugin, you saved me today

**Comment by larryaasen** [comment]
Just published a null safety version of this package as a prerelease. Check it out https://pub.dev/packages/upgrader/versions.

**Comment by larryaasen** [comment]
Just release version 3.0.0 of this package with full support for null safety.
