### ISSUE TITLE
appcast for iOS and Android

### ISSUE THREAD

**Issue by elioDeMarinis** [larryaasen/upgrader#90]
First of all, many thanks for your library. I'd ask you if it could be possible to use the appcast file both for Android and iOS in order to manage the app versioning from a unique file without using the Bundle Identifier. If it is possible, could give me an example? Thanks in advance.

**Comment by larryaasen** [comment]
Did you try an appcast file?

**Comment by DzonaTheSymbol** [comment]
@elioDeMarinis Did you ever find a solution for this?
