### ISSUE TITLE
3.0.0-nullsafety.2 conflict package

### ISSUE THREAD

**Issue by dangbh1002** [larryaasen/upgrader#92]
I can't run `flutter pub get` because of conflict package:

`
Because upgrader >=3.0.0-nullsafety.2 depends on url_launcher ^6.0.2 and pubspecFile depends on url_launcher ^5.7.10, upgrader >=3.0.0-nullsafety.2 is forbidden.
So, because pubspecFile depends on upgrader 3.0.0-nullsafety.2, version solving failed.
`

**Comment by larryaasen** [comment]
Can you remove the version number from url_launcher line in your pubspec.yaml file and see if it resolves?
`  url_launcher:
`
Then if it does, grab the version number for url_launcher from the pubspec.lock file and use that in your pubspec.yaml file.

**Comment by larryaasen** [comment]
Closed due to lack of activity. You can open a new issue if you have more questions.
