### ISSUE TITLE
upgrader unable to detect update

### ISSUE THREAD

**Issue by danearg** [larryaasen/upgrader#94]
The debug shows that there are no available updates even though my pubspec version is lower than the minimum app version that I set in the dart and XML.

dart:

final appcastURL = 'https://raw.githubusercontent.com/jeejaykim/apispa/jeejaykim-test/test.xml';
final cfg = AppcastConfiguration(url: appcastURL, supportedOS: ['android']);

return Scaffold(
        body: UpgradeAlert(
            dialogStyle: UpgradeDialogStyle.cupertino,
            appcastConfig: cfg,
            debugLogging: true,
            showLater: false,
            showIgnore: false,
            minAppVersion: '120.0.0',
            child: Container(width: 0, height: 0)),
      );
Debug:

I/flutter ( 8444): upgrader: build UpgradeAlert
I/flutter ( 8444): FormatException: Cannot parse empty string into version
I/flutter ( 8444): upgrader: blocked: false
I/flutter ( 8444): upgrader: debugDisplayAlways: false
I/flutter ( 8444): upgrader: debugDisplayOnce: false
I/flutter ( 8444): upgrader: hasAlerted: false
I/flutter ( 8444): upgrader: appStoreVersion: null
I/flutter ( 8444): upgrader: installedVersion: null
I/flutter ( 8444): upgrader: minAppVersion: 120.0.0
I/flutter ( 8444): upgrader: isUpdateAvailable: false
I/flutter ( 8444): upgrader: shouldDisplayUpgrade: false
I/flutter ( 8444): upgrader: appcast item count: 4
I/flutter ( 8444): upgrader: appcast best item version: 200.0.0

pubspec:
version: 110.00.05+5

**Comment by larryaasen** [comment]
I see that the installedVersion is null and I don't see any logs for package info which is logged immediately after initialization. Is there more log that was not attached here?

**Comment by danearg** [comment]
I'm sorry for the late reply but here is my updated debug log.

I/flutter ( 4729): upgrader: package info packageName: com.example.stackoverflow
I/flutter ( 4729): upgrader: package info appName: test
I/flutter ( 4729): upgrader: package info version: 110.00.05
I/flutter ( 4729): upgrader: blocked: true
I/flutter ( 4729): upgrader: debugDisplayAlways: false
I/flutter ( 4729): upgrader: debugDisplayOnce: false
I/flutter ( 4729): upgrader: hasAlerted: false
I/flutter ( 4729): upgrader: appStoreVersion: null
I/flutter ( 4729): upgrader: installedVersion: 110.00.05
I/flutter ( 4729): upgrader: minAppVersion: 120.0.0
I/flutter ( 4729): upgrader: isUpdateAvailable: false
I/flutter ( 4729): upgrader: shouldDisplayUpgrade: false

**Comment by larryaasen** [comment]
I don't see this line in the log so I don't think it is using your appcast.
`upgrader: appcast is available for this platform`
Try placing a breakpoint in this method to determine why it is not using your appcast:
`_isAppcastThisPlatform()`

**Comment by danearg** [comment]
I/flutter ( 7546): upgrader: appcast best item version: 200.0.0
I/flutter ( 7546): upgrader: appcast item count: 4
I/flutter ( 7546): upgrader: shouldDisplayUpgrade: false
I/flutter ( 7546): upgrader: isUpdateAvailable: false
I/flutter ( 7546): upgrader: minAppVersion: 120.0.0
I/flutter ( 7546): upgrader: installedVersion: null
I/flutter ( 7546): upgrader: appStoreVersion: null
I/flutter ( 7546): upgrader: hasAlerted: false
I/flutter ( 7546): upgrader: debugDisplayOnce: false
I/flutter ( 7546): upgrader: debugDisplayAlways: false
I/flutter ( 7546): upgrader: blocked: false
I/flutter ( 7546): upgrader: build UpgradeAlert
I/flutter ( 7546): upgrader: appcast is available for this platform
I/flutter ( 7546): upgrader: package info version: 110.00.05
I/flutter ( 7546): upgrader: package info appName: test
I/flutter ( 7546): upgrader: package info packageName: com.example.stackoverflow
I/flutter ( 7546): upgrader: languageCode: en
I/flutter ( 7546): upgrader: build UpgradeAlert

I'm using an android emulator

**Comment by larryaasen** [comment]
I just published version 3.4.1 to resolve this issue.
