### ISSUE TITLE
can we hide & show buttons using appcast xml file parameter

### ISSUE THREAD

**Issue by Vikasosian** [larryaasen/upgrader#95]
Hi, this plugin very useful to me. but I want to show & hide 'Ignore' & 'Later' buttons using appcast xml file parameter. Because when some time needs to allow users to use the app without update & sometimes need to update forcefully. so I want to handle this using appcast xml. thanks in advance.

**Comment by larryaasen** [comment]
In your Appcast XML file use `sparkle:criticalUpdate` like this to disable the Ignore and Later buttons.
```
    <item>
        <title>Version 2.0</title>
        <description>desc</description>
        <pubDate>Sat, 26 Jul 2014 15:20:11 +0000</pubDate>
        <enclosure url="http://localhost:1337/Sparkle_Test_App.zip" sparkle:version="2.0" />
        <sparkle:tags> <sparkle:criticalUpdate /> </sparkle:tags> 
    </item>
```

**Comment by Vikasosian** [comment]
@larryaasen thank you so much, its working.
