### ISSUE TITLE
dio ^3.0.10 and upgrader ^3.1.0 version solving failed

### ISSUE THREAD

**Issue by Nitingadhiya** [larryaasen/upgrader#96]
pub get failed (1; So, because X application depends on both dio ^3.0.10 and upgrader ^3.1.0, version solving failed.)

**Comment by larryaasen** [comment]
Try removing the version for upgrader in your `pubspec.yaml` file, and see if it can be resolved. If it does, then add the version from the `pubspec.lock` file into your `pubspec.yaml` file. Try this:
```
  upgrader: 
```
