### ISSUE TITLE
Update available and seen in debugging logs, but dialog doesn't show up as long as version in not below minAppVersion 

### ISSUE THREAD

**Issue by AdhamSaheb** [larryaasen/upgrader#97]
![Screen Shot 2021-03-25 at 12 05 27](https://user-images.githubusercontent.com/46823438/112455474-6bcf6f00-8d62-11eb-8411-2ee2f979bcb2.png)

**Comment by larryaasen** [comment]
What version of upgrader?

**Comment by AdhamSaheb** [comment]
> What version of upgrader?

upgrader: ^2.8.2 , as my project is a bit large and can't migrate to Flutter 2.0 atm

**Comment by larryaasen** [comment]
I've looked at your debug log and looked over the code, and I don't see why shouldDisplayUpgrade is false. Are you able to put a breakpoint in shouldDisplayUpgrade()? If so, put a breakpoint here and look at this line: `if (isTooSoon() || alreadyIgnoredThisVersion()) {` and see if that causes it to return false.

**Comment by AdhamSaheb** [comment]
> I've looked at your debug log and looked over the code, and I don't see why shouldDisplayUpgrade is false. Are you able to put a breakpoint in shouldDisplayUpgrade()? If so, put a breakpoint here and look at this line: `if (isTooSoon() || alreadyIgnoredThisVersion()) {` and see if that causes it to return false.

I've inserted a small print inside that if statement and yes it does return false, see screenshot below 
![Screen Shot 2021-03-25 at 13 41 51](https://user-images.githubusercontent.com/46823438/112467619-f4084100-8d6f-11eb-8bcd-0a6461ab2a90.png)

**Comment by larryaasen** [comment]
Which one returned false? `isTooSoon()` or `alreadyIgnoredThisVersion()`?

**Comment by AdhamSaheb** [comment]
> Which one returned false? `isTooSoon()` or `alreadyIgnoredThisVersion()`?

Too soon

![Uploading Screen Shot 2021-03-25 at 13.48.55.png…]()

**Comment by AdhamSaheb** [comment]
The only way I managed to get it to show up is to set : 
`durationToAlertAgain: Duration(seconds: 2) ;`
Im not sure if this will cause any issues or I'm missing something here but i'll give it a shot in the next update, would you like me to close the issue ?

**Comment by larryaasen** [comment]
Put this code in the build method of your main app widget only for debugging. This will clear all saved values.
```
    // Only call clearSavedSettings() during testing to reset internal values.
    Upgrader().clearSavedSettings(); // Remove this for release builds
```

**Comment by AdhamSaheb** [comment]
Thank you very much, closed.
