### ISSUE TITLE
Upgrade Alert Still Appear After Updated

### ISSUE THREAD

**Issue by aJuhari** [larryaasen/upgrader#98]
I used, upgrader: version 2.8.2

Why does the Upgrade Alert Still Appear since user already updated the latest version of the app ? 
is the version have a issue ? 

![Simulator Screen Shot - iPhone 12 Pro - 2021-04-02 at 10 16 38](https://user-images.githubusercontent.com/79817203/113373456-6cd55180-939d-11eb-870d-cd610d350811.png)

<img width="367" alt="Screenshot 2021-04-02 at 3 24 30 PM" src="https://user-images.githubusercontent.com/79817203/113392347-91deba00-93c7-11eb-9777-da0aae8a437f.png">

**Comment by bean5** [comment]
Perhaps if the build number of the version in the store is higher?

**Comment by larryaasen** [comment]
I see two things in your log:
`shouldDisplayUpgrade: false`
Which means it should not display.
However, I also see `debugDisplayOnce: true`
Which means that for debugging, it should display once. Try setting debugDisplayOnce to false and try again.

**Comment by aJuhari** [comment]
I set debugDisplayOnce to false and it works..!

Thank you very much..
