### ISSUE TITLE
How to make an AppCast file and show the release notes

### ISSUE THREAD

**Issue by codinglifeprogram** [larryaasen/upgrader#99]
I am having trouble showing release notes and making an appcast file for android and ios

**Comment by larryaasen** [comment]
What have you tried so far?

**Comment by MlecznyU** [comment]
I have the same problem. I tried following configurations:
![image](https://user-images.githubusercontent.com/59980382/114182294-c19b3e00-9942-11eb-89cc-c6f40ccbda2d.png)
and 
![image](https://user-images.githubusercontent.com/59980382/114182422-e1326680-9942-11eb-9b2e-17d71e990e42.png)

**Comment by larryaasen** [comment]
Can you share your upgrader log?

**Comment by MlecznyU** [comment]
If you ask for console logs when the popup appears, I don't have any logs

**Comment by larryaasen** [comment]
Thanks for attaching the log. After the line `upgrader: showDialog message: ...` , you should see `upgrader: showDialog releaseNotes: ...`. What version of upgrader are you using? Make sure you are using version 3.1.0 or greater.

**Comment by MlecznyU** [comment]
I was using the previous version. Thanks for the explanation :)

**Comment by larryaasen** [comment]
@MlecznyU Is this issue resolved?
